// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/http/SendableObject.h"
#include "accelbyte/common/DateTime.h"
#include "accelbyte/utils/JsonObjectString.h"
#include "accelbyte/common/Optional.h"
#include "accelbyte/seasonpass/seasonpass_export.h"

#include "accelbyte/common/String.h"
#include "accelbyte/common/Map.h"
#include "accelbyte/common/Vector.h"


namespace accelbyte {
namespace seasonpass {
namespace season {

/**
* @brief This API is used to get user exp acquisition history, season only located in non-publisher namespace.&lt;p&gt;Other detail info: &lt;ul&gt;&lt;li&gt;default will query from current active season&lt;/li&gt;&lt;li&gt;&lt;i&gt;Returns&lt;/i&gt;: paginated grant history&lt;/li&gt;&lt;/ul&gt;
*/
class AdminQueryUserExpGrantHistory : public accelbyte::http::SendableObject
{
public:
    
    enum class Source : uint32_t {
        UNKNOWN,
        PAID_FOR,
        SWEAT
    };
    
    /**
    * @brief default constructor.
    **/
	AB_seasonpass_EXPORT AdminQueryUserExpGrantHistory() = default;
	
    /**
    * @brief destrutor.
    **/
    AB_seasonpass_EXPORT virtual ~AdminQueryUserExpGrantHistory() = default;
	
	/**
    * @brief Return the object unique id (used for serialization)
    **/
    AB_seasonpass_EXPORT const String& sendable_id() const override;
	
	/**
    * @brief Return the unique id that can be used to determine this class (used for serialization)
    **/
    AB_seasonpass_EXPORT static const String& sendable_object_id();
	
    // usefull parameters    
     /**
     * @brief Namespace
if not set the user namespace will be used.
    **/
    accelbyte::Optional<accelbyte::String> ab_namespace{};
     /**
     * @brief None
    **/
    accelbyte::String user_id{};
     /**
     * @brief section active range time start , using ISO 8601 format e.g. yyyy-MM-dd'T'HH:mm:ssZZ
    **/
    accelbyte::Optional<accelbyte::String> from{};
     /**
     * @brief limit
    **/
    accelbyte::Optional<int> limit{};
     /**
     * @brief offset
    **/
    accelbyte::Optional<int> offset{};
     /**
     * @brief if not provide, will query current season
    **/
    accelbyte::Optional<accelbyte::String> season_id{};
     /**
     * @brief exp grant source
    **/
    accelbyte::Optional<Source> source{};
     /**
     * @brief exp grant tags
    **/
    accelbyte::Optional<accelbyte::Vector<accelbyte::String>> tags{};
     /**
     * @brief section active range time end, using ISO 8601 format e.g. yyyy-MM-dd'T'HH:mm:ssZZ
    **/
    accelbyte::Optional<accelbyte::String> to{};
};

}
}
}