// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/login_queue/login_queue_export.h"
#include "accelbyte/login_queue/ticket_v1/CancelTicket.h"
#include "accelbyte/login_queue/ticket_v1/RefreshTicket.h"
#include "accelbyte/login_queue/models/ConfigurationRequest.h"
#include "accelbyte/login_queue/models/Configuration.h"
#include "accelbyte/login_queue/models/CreateTicketRequest.h"
#include "accelbyte/login_queue/models/EmptyBody.h"
#include "accelbyte/login_queue/models/Link.h"
#include "accelbyte/login_queue/models/QueueStatus.h"
#include "accelbyte/login_queue/models/RefreshTicket.h"
#include "accelbyte/login_queue/models/TicketResponse.h"
#include "accelbyte/login_queue/models/TokenValidationRequest.h"
#include "accelbyte/login_queue/models/TokenValidation.h"
#include "accelbyte/login_queue/models/Error.h"
#include "accelbyte/common/Error.h"
#include "accelbyte/tls/SecurityAuthorization.h"

#include <functional>
#include "accelbyte/memory/memory.h"

namespace accelbyte {
namespace login_queue {

class TicketV1
{
public:	
    /**
    * @brief Cancel ticket
    * @details Cancel ticket. This endpoint requires ticket to be placed in the authorization header with this format: &#34;Bearer ticketID&#34;
    * @details /login-queue/v1/namespaces/{namespace}/ticket
    *
    */
    AB_login_queue_EXPORT static void cancel_ticket(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const ticket_v1::CancelTicket& request, 
        const std::function<void()>& on_204,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Refresh ticket
    * @details Refresh ticket. This endpoint requires ticket to be placed in the authorization header with this format: &#34;Bearer ticketID&#34;. When the ticketID is empty or not found the response status will be 401
    * @details /login-queue/v1/namespaces/{namespace}/ticket
    *
    */
    AB_login_queue_EXPORT static void refresh_ticket(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const ticket_v1::RefreshTicket& request, 
        const std::function<void(const model::RefreshTicket&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

};

}
}