// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/http/ModelObject.h"
#include "accelbyte/common/Optional.h"
#include "accelbyte/common/String.h"
#include "accelbyte/common/Map.h"
#include "accelbyte/common/Vector.h"
#include "accelbyte/common/DateTime.h"
#include "accelbyte/memory/memory.h"
#include "accelbyte/utils/JsonObjectString.h"
#include "accelbyte/gametelemetry/gametelemetry_export.h"


namespace accelbyte {
namespace gametelemetry {
namespace model {

class BaseError : public accelbyte::http::ModelObject
{
public:
    /**
    * @brief default constructor.
    **/
	AB_gametelemetry_EXPORT  BaseError() = default;
	
    /**
    * @brief destructor.
    **/
    AB_gametelemetry_EXPORT virtual ~BaseError() = default;
	
	/**
    * @brief Return the object unique id (used for serialization)
    **/
    AB_gametelemetry_EXPORT virtual const String& model_id() const override;
	
	/**
    * @brief Return the unique id that can be used to determine this class (used for serialization)
    **/
    AB_gametelemetry_EXPORT static const String& model_object_id();
    
    // start of usefull parameters
	long error_code{0};
	accelbyte::String error_message{};
};

}
}
}