// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/iam/iam_export.h"
#include "accelbyte/iam/o_auth2_0_extension/UserAuthenticationV3.h"
#include "accelbyte/iam/o_auth2_0_extension/AuthenticationPlatformLinkV3.h"
#include "accelbyte/iam/o_auth2_0_extension/84b89db86739ca3adlessAccountV3.h"
#include "accelbyte/iam/o_auth2_0_extension/OneTimeLinkCodeV3Request.h"
#include "accelbyte/iam/o_auth2_0_extension/ValidateOneTimeLinkCodeV3.h"
#include "accelbyte/iam/o_auth2_0_extension/7a2d0a69aeb9407eTimeLinkCodeV3.h"
#include "accelbyte/iam/o_auth2_0_extension/GetCountryLocationV3.h"
#include "accelbyte/iam/o_auth2_0_extension/Logout.h"
#include "accelbyte/iam/o_auth2_0_extension/RequestTokenExchangeCodeV3.h"
#include "accelbyte/iam/o_auth2_0_extension/GetPlatformAuthenticationV3.h"
#include "accelbyte/iam/o_auth2_0_extension/VerifyPlatformTokenRefreshV3.h"
#include "accelbyte/iam/o_auth2_0_extension/GenerateTargetTokenV3.h"
#include "accelbyte/iam/models/BannedBy.h"
#include "accelbyte/iam/models/Validation.h"
#include "accelbyte/iam/models/ValidationDescription.h"
#include "accelbyte/iam/models/AccountUserActiveBanV4.h"
#include "accelbyte/iam/models/AccountUserPermissionsV4.h"
#include "accelbyte/iam/models/AccountUserV4.h"
#include "accelbyte/iam/models/AccountCreateTestUserRequestV4.h"
#include "accelbyte/iam/models/AccountCreateTestUserV4.h"
#include "accelbyte/iam/models/ce0a453054ff198tUsersRequestV4.h"
#include "accelbyte/iam/models/AccountCreateTestUsersRV4.h"
#include "accelbyte/iam/models/AccountCreateUserRequestV4.h"
#include "accelbyte/iam/models/AccountCreateUserV4.h"
#include "accelbyte/iam/models/e7185571582ba7bccountRequestV4.h"
#include "accelbyte/iam/models/230105d16667ab9onCodeRequestV4.h"
#include "accelbyte/iam/models/AccountUserInfo.h"
#include "accelbyte/iam/models/AllowedPermission.h"
#include "accelbyte/iam/models/AvatarConfig.h"
#include "accelbyte/iam/models/Ban.h"
#include "accelbyte/iam/models/BanReason.h"
#include "accelbyte/iam/models/BanReasonV3.h"
#include "accelbyte/iam/models/BanReasons.h"
#include "accelbyte/iam/models/BanReasonsV3.h"
#include "accelbyte/iam/models/BanV3.h"
#include "accelbyte/iam/models/BannedByV3.h"
#include "accelbyte/iam/models/Bans.h"
#include "accelbyte/iam/models/BansV3.h"
#include "accelbyte/iam/models/ClientModulePermission.h"
#include "accelbyte/iam/models/ClientPermission.h"
#include "accelbyte/iam/models/ClientPermissionSet.h"
#include "accelbyte/iam/models/ClientPermissionV3.h"
#include "accelbyte/iam/models/ClientPermissions.h"
#include "accelbyte/iam/models/ClientPermissionsV3.h"
#include "accelbyte/iam/models/ClientSelectedGroup.h"
#include "accelbyte/iam/models/ConflictedUserPlatformAccounts.h"
#include "accelbyte/iam/models/CountryInfo.h"
#include "accelbyte/iam/models/CountryAgeRestriction.h"
#include "accelbyte/iam/models/Description.h"
#include "accelbyte/iam/models/DistinctLinkedPlatformV3.h"
#include "accelbyte/iam/models/DistinctPlatformV3.h"
#include "accelbyte/iam/models/InputValidationDescription.h"
#include "accelbyte/iam/models/JWTBanV3.h"
#include "accelbyte/iam/models/ea27475110b19faccountsResponse.h"
#include "accelbyte/iam/models/NamespaceRole.h"
#include "accelbyte/iam/models/NetflixCertificates.h"
#include "accelbyte/iam/models/OverrideRolePermission.h"
#include "accelbyte/iam/models/Pagination.h"
#include "accelbyte/iam/models/Pagination.h"
#include "accelbyte/iam/models/Permission.h"
#include "accelbyte/iam/models/PermissionGroup.h"
#include "accelbyte/iam/models/PermissionV3.h"
#include "accelbyte/iam/models/Permissions.h"
#include "accelbyte/iam/models/PermissionsV3.h"
#include "accelbyte/iam/models/PlatformAccount.h"
#include "accelbyte/iam/models/PlatformLinkHistory.h"
#include "accelbyte/iam/models/PlatformUserInfoV3.h"
#include "accelbyte/iam/models/ProfileUpdateConfig.h"
#include "accelbyte/iam/models/RegisteredDomain.h"
#include "accelbyte/iam/models/ReplaceRolePermission.h"
#include "accelbyte/iam/models/Role.h"
#include "accelbyte/iam/models/RoleManager.h"
#include "accelbyte/iam/models/RoleManagerV3.h"
#include "accelbyte/iam/models/RoleMember.h"
#include "accelbyte/iam/models/RoleMemberV3.h"
#include "accelbyte/iam/models/RoleV3.h"
#include "accelbyte/iam/models/SimpleUserPlatformInfoV3.h"
#include "accelbyte/iam/models/AccountUserInformationV3.h"
#include "accelbyte/iam/models/UserLinkedPlatform.h"
#include "accelbyte/iam/models/UserLinkedPlatformV3.h"
#include "accelbyte/iam/models/UserLinkedPlatformsV3.h"
#include "accelbyte/iam/models/AccountUserPlatformInfo.h"
#include "accelbyte/iam/models/UserPlatforms.h"
#include "accelbyte/iam/models/UserSearchByPlatformID.h"
#include "accelbyte/iam/models/UserSearch.h"
#include "accelbyte/iam/models/UserLinkedPlatformAccounts.h"
#include "accelbyte/iam/models/UserPlatformAccounts.h"
#include "accelbyte/iam/models/BloomFilterJSON.h"
#include "accelbyte/iam/models/ClientCreateRequest.h"
#include "accelbyte/iam/models/ClientCreation.h"
#include "accelbyte/iam/models/ClientCreationV3Request.h"
#include "accelbyte/iam/models/Client.h"
#include "accelbyte/iam/models/ClientTemplate.h"
#include "accelbyte/iam/models/ClientUpdateRequest.h"
#include "accelbyte/iam/models/ClientUpdateSecretRequest.h"
#include "accelbyte/iam/models/ClientUpdateV3Request.h"
#include "accelbyte/iam/models/ClientV3.h"
#include "accelbyte/iam/models/ClientsUpdateRequestV3.h"
#include "accelbyte/iam/models/ClientsV3.h"
#include "accelbyte/iam/models/DefaultFieldValue.h"
#include "accelbyte/iam/models/DefaultFieldValueValue.h"
#include "accelbyte/iam/models/GetClientPermissionSets.h"
#include "accelbyte/iam/models/GetTemplates.h"
#include "accelbyte/iam/models/GetUpsertModulesRequest.h"
#include "accelbyte/iam/models/a21421b5ff9bb69eteGroupRequest.h"
#include "accelbyte/iam/models/PermissionSetUpsertRequest.h"
#include "accelbyte/iam/models/V3ClientUpdateSecretRequest.h"
#include "accelbyte/iam/models/LegalAcceptedPoliciesRequest.h"
#include "accelbyte/iam/models/AccountProgressionInfo.h"
#include "accelbyte/iam/models/AddUserRoleV4Request.h"
#include "accelbyte/iam/models/AgeRestrictionRequest.h"
#include "accelbyte/iam/models/AgeRestrictionRequestV3.h"
#include "accelbyte/iam/models/AgeRestriction.h"
#include "accelbyte/iam/models/AgeRestrictionV3.h"
#include "accelbyte/iam/models/AssignUserV4Request.h"
#include "accelbyte/iam/models/AssignedUserV4.h"
#include "accelbyte/iam/models/AuthenticatorKeyV4.h"
#include "accelbyte/iam/models/BackupCodesV4.h"
#include "accelbyte/iam/models/BanCreateRequest.h"
#include "accelbyte/iam/models/BanUpdateRequest.h"
#include "accelbyte/iam/models/AccountTypeUpdateRequestsV4.h"
#include "accelbyte/iam/models/BanCreateRequestsV3.h"
#include "accelbyte/iam/models/UnbanCreateRequestsV3.h"
#include "accelbyte/iam/models/CheckAvailability.h"
#include "accelbyte/iam/models/CheckValidUserIDRequestV4.h"
#include "accelbyte/iam/models/ConfigValueV3.h"
#include "accelbyte/iam/models/AdminCountry.h"
#include "accelbyte/iam/models/CountryAgeRestrictionRequest.h"
#include "accelbyte/iam/models/CountryAgeRestrictionV3Request.h"
#include "accelbyte/iam/models/CountryBlacklistRequest.h"
#include "accelbyte/iam/models/CountryBlacklist.h"
#include "accelbyte/iam/models/CountryResponse.h"
#include "accelbyte/iam/models/CountryV3.h"
#include "accelbyte/iam/models/CreateJusticeUser.h"
#include "accelbyte/iam/models/DeviceBanRequestV4.h"
#include "accelbyte/iam/models/DeviceBanV4.h"
#include "accelbyte/iam/models/DeviceBanUpdateRequestV4.h"
#include "accelbyte/iam/models/DeviceBannedV4.h"
#include "accelbyte/iam/models/DeviceBansV4.h"
#include "accelbyte/iam/models/DeviceIDDecryptV4.h"
#include "accelbyte/iam/models/DeviceV4.h"
#include "accelbyte/iam/models/DeviceTypeV4.h"
#include "accelbyte/iam/models/DeviceTypesV4.h"
#include "accelbyte/iam/models/DeviceUserV4.h"
#include "accelbyte/iam/models/DeviceUsersV4.h"
#include "accelbyte/iam/models/DevicesV4.h"
#include "accelbyte/iam/models/DisableMFARequest.h"
#include "accelbyte/iam/models/DisableUserRequest.h"
#include "accelbyte/iam/models/EmailUpdateRequestV4.h"
#include "accelbyte/iam/models/EnabledFactorsV4.h"
#include "accelbyte/iam/models/FailedBanUnbanUserV3.h"
#include "accelbyte/iam/models/UpdateAllowStatusRequest.h"
#include "accelbyte/iam/models/ForgotPasswordRequestV3.h"
#include "accelbyte/iam/models/AdminGetUsersResponse.h"
#include "accelbyte/iam/models/GetUserBansRequest.h"
#include "accelbyte/iam/models/b78313aa32ea23fonflictResponse.h"
#include "accelbyte/iam/models/GetProfileUpdateStrategyConfig.h"
#include "accelbyte/iam/models/GetPublisherUserResponse.h"
#include "accelbyte/iam/models/GetUserBanSummaryV3.h"
#include "accelbyte/iam/models/GetUserBanV3Response.h"
#include "accelbyte/iam/models/fa17499471c51a2AccountResponse.h"
#include "accelbyte/iam/models/GetUserMappingResponse.h"
#include "accelbyte/iam/models/GetUserMappingV3.h"
#include "accelbyte/iam/models/GetUsersPaginationV3.h"
#include "accelbyte/iam/models/InputValidationConfigVersion.h"
#include "accelbyte/iam/models/InputValidationData.h"
#include "accelbyte/iam/models/InputValidationPublic.h"
#include "accelbyte/iam/models/InputValidationUpdatePayload.h"
#include "accelbyte/iam/models/InputValidations.h"
#include "accelbyte/iam/models/AdminInputValidations.h"
#include "accelbyte/iam/models/InvitationHistory.h"
#include "accelbyte/iam/models/InviteUserRequestV3.h"
#include "accelbyte/iam/models/AdminInviteUserRequestV4.h"
#include "accelbyte/iam/models/InviteUserV3.h"
#include "accelbyte/iam/models/LinkHeadlessAccountRequest.h"
#include "accelbyte/iam/models/LinkPlatformAccountRequest.h"
#include "accelbyte/iam/models/0186368831f34f6gressionRequest.h"
#include "accelbyte/iam/models/LinkRequest.h"
#include "accelbyte/iam/models/LinkHistoryPaginationV3.h"
#include "accelbyte/iam/models/GetAssignedUsersV4sResponse.h"
#include "accelbyte/iam/models/GetUserBanResponsesV3.h"
#include "accelbyte/iam/models/GetUserPlatformsResponse.h"
#include "accelbyte/iam/models/GetUsersResponse.h"
#include "accelbyte/iam/models/GetEmailAddressRequest.h"
#include "accelbyte/iam/models/65af9295f7771f9riesV4sResponse.h"
#include "accelbyte/iam/models/GetRoleV4sResponse.h"
#include "accelbyte/iam/models/GetUserInfoResponse.h"
#include "accelbyte/iam/models/GetUserResponsesV3.h"
#include "accelbyte/iam/models/GetUserRolesV4sResponse.h"
#include "accelbyte/iam/models/GetValidUserIDResponsesV4.h"
#include "accelbyte/iam/models/LoginAllowlistRequest.h"
#include "accelbyte/iam/models/LoginAllowlist.h"
#include "accelbyte/iam/models/LoginHistories.h"
#include "accelbyte/iam/models/2034c64803e77d5onHistoryUserV4.h"
#include "accelbyte/iam/models/NamespaceRoleRequest.h"
#include "accelbyte/iam/models/PermissionDeleteRequest.h"
#include "accelbyte/iam/models/PlatformDomainDeleteRequest.h"
#include "accelbyte/iam/models/PlatformDomain.h"
#include "accelbyte/iam/models/PlatformDomainUpdateRequest.h"
#include "accelbyte/iam/models/PlatformUserIDRequest.h"
#include "accelbyte/iam/models/PlatformUserIDRequestV4.h"
#include "accelbyte/iam/models/PlatformUserInfo.h"
#include "accelbyte/iam/models/InviteUserRequestV4.h"
#include "accelbyte/iam/models/ThirdPartyPlatformInfo.h"
#include "accelbyte/iam/models/UsersInfoV3.h"
#include "accelbyte/iam/models/UserInfoV3.h"
#include "accelbyte/iam/models/User.h"
#include "accelbyte/iam/models/UserV3.h"
#include "accelbyte/iam/models/UserUpdateRequestV3.h"
#include "accelbyte/iam/models/UsersInfo.h"
#include "accelbyte/iam/models/RemoveUserRoleV4Request.h"
#include "accelbyte/iam/models/ResetPasswordRequest.h"
#include "accelbyte/iam/models/ResetPasswordRequestV3.h"
#include "accelbyte/iam/models/RevokeUserV4Request.h"
#include "accelbyte/iam/models/AdminRoleStatus.h"
#include "accelbyte/iam/models/AdminRoleStatusV3.h"
#include "accelbyte/iam/models/RoleCreateRequest.h"
#include "accelbyte/iam/models/RoleCreateV3Request.h"
#include "accelbyte/iam/models/RoleManagersRequest.h"
#include "accelbyte/iam/models/RoleManagersRequestV3.h"
#include "accelbyte/iam/models/RoleManagers.h"
#include "accelbyte/iam/models/RoleManagersV3.h"
#include "accelbyte/iam/models/RoleMembersRequest.h"
#include "accelbyte/iam/models/RoleMembersRequestV3.h"
#include "accelbyte/iam/models/RoleMembers.h"
#include "accelbyte/iam/models/RoleMembersV3.h"
#include "accelbyte/iam/models/RoleNamesV3.h"
#include "accelbyte/iam/models/RoleOverride.h"
#include "accelbyte/iam/models/RoleOverrideSource.h"
#include "accelbyte/iam/models/RoleOverrideStatsUpdateRequest.h"
#include "accelbyte/iam/models/RoleOverrideUpdateRequest.h"
#include "accelbyte/iam/models/RolePermissionV3.h"
#include "accelbyte/iam/models/Role.h"
#include "accelbyte/iam/models/RoleV3.h"
#include "accelbyte/iam/models/RoleManagers.h"
#include "accelbyte/iam/models/RoleManagersPaginationV3.h"
#include "accelbyte/iam/models/RoleManagersV3.h"
#include "accelbyte/iam/models/RoleUpdateRequest.h"
#include "accelbyte/iam/models/RoleUpdateRequestV3.h"
#include "accelbyte/iam/models/RoleV4Request.h"
#include "accelbyte/iam/models/RoleV4.h"
#include "accelbyte/iam/models/SSOPlatformCredentialRequest.h"
#include "accelbyte/iam/models/SSOPlatformCredential.h"
#include "accelbyte/iam/models/SearchUsersByPlatformID.h"
#include "accelbyte/iam/models/SearchUsersResponse.h"
#include "accelbyte/iam/models/SearchUsersPaginationV3.h"
#include "accelbyte/iam/models/9fd939ffadda005tionCodeRequest.h"
#include "accelbyte/iam/models/SendVerificationCodeRequest.h"
#include "accelbyte/iam/models/SendVerificationCodeRequestV3.h"
#include "accelbyte/iam/models/SendVerificationLinkRequest.h"
#include "accelbyte/iam/models/ProfileUpdateStrategyConfigs.h"
#include "accelbyte/iam/models/2c935cf54f37919edentialRequest.h"
#include "accelbyte/iam/models/09fc075eb9a951dtformCredential.h"
#include "accelbyte/iam/models/TokenThirdPartyLinkStatus.h"
#include "accelbyte/iam/models/UnlinkUserPlatformRequest.h"
#include "accelbyte/iam/models/ac832bf27aa6571ScheduleRequest.h"
#include "accelbyte/iam/models/0e9a6ca2c990c1bgyConfigRequest.h"
#include "accelbyte/iam/models/4104530968377c2onStatusRequest.h"
#include "accelbyte/iam/models/UpdateUserStatusRequest.h"
#include "accelbyte/iam/models/UpgradeHeadlessAccountRequest.h"
#include "accelbyte/iam/models/92bf5aca7f82029ccountV3Request.h"
#include "accelbyte/iam/models/0d9361593042ef1tionCodeRequest.h"
#include "accelbyte/iam/models/0e54d9bd37c92cconCodeRequestV3.h"
#include "accelbyte/iam/models/UserActiveBan.h"
#include "accelbyte/iam/models/UserActiveBanV3.h"
#include "accelbyte/iam/models/UserBan.h"
#include "accelbyte/iam/models/UserBanV3.h"
#include "accelbyte/iam/models/UserBanStatus.h"
#include "accelbyte/iam/models/UserBaseInfo.h"
#include "accelbyte/iam/models/UserUpdateRequestsV3.h"
#include "accelbyte/iam/models/UserCreateRequest.h"
#include "accelbyte/iam/models/UserCreateRequestV3.h"
#include "accelbyte/iam/models/UserCreate.h"
#include "accelbyte/iam/models/UserCreateV3.h"
#include "accelbyte/iam/models/UserDeletionStatus.h"
#include "accelbyte/iam/models/UserIdsRequest.h"
#include "accelbyte/iam/models/UserIdentityUpdateRequestV3.h"
#include "accelbyte/iam/models/UserInfo.h"
#include "accelbyte/iam/models/UserInfo.h"
#include "accelbyte/iam/models/UserInputValidationRequest.h"
#include "accelbyte/iam/models/UserInputValidation.h"
#include "accelbyte/iam/models/UserInvitationHistory.h"
#include "accelbyte/iam/models/UserInvitationV3.h"
#include "accelbyte/iam/models/UserLoginHistory.h"
#include "accelbyte/iam/models/UserMFAStatusV4.h"
#include "accelbyte/iam/models/UserMFATokenV4.h"
#include "accelbyte/iam/models/UserPasswordUpdateRequest.h"
#include "accelbyte/iam/models/UserPasswordUpdateV3Request.h"
#include "accelbyte/iam/models/UserPermissionsV3.h"
#include "accelbyte/iam/models/UserPlatformInfo.h"
#include "accelbyte/iam/models/UserPlatformInfos.h"
#include "accelbyte/iam/models/UserPlatformLinkHistories.h"
#include "accelbyte/iam/models/UserPlatformLinkHistory.h"
#include "accelbyte/iam/models/UserPlatformMetadata.h"
#include "accelbyte/iam/models/UserProfileUpdateAllowStatus.h"
#include "accelbyte/iam/models/UserInfoV4.h"
#include "accelbyte/iam/models/AdminUser.h"
#include "accelbyte/iam/models/AdminUserV3.h"
#include "accelbyte/iam/models/UserRolesV4.h"
#include "accelbyte/iam/models/UserUpdateRequest.h"
#include "accelbyte/iam/models/AdminUserUpdateRequestV3.h"
#include "accelbyte/iam/models/UserVerificationRequest.h"
#include "accelbyte/iam/models/UserVerificationRequestV3.h"
#include "accelbyte/iam/models/UserWithPlatformInfo.h"
#include "accelbyte/iam/models/UsersPlatformInfosRequestV3.h"
#include "accelbyte/iam/models/UsersPlatformInfos.h"
#include "accelbyte/iam/models/UsersUpdateRequestV3.h"
#include "accelbyte/iam/models/ValidUserIDV4.h"
#include "accelbyte/iam/models/ValidationDetail.h"
#include "accelbyte/iam/models/ValidationDetailPublic.h"
#include "accelbyte/iam/models/VerificationCode.h"
#include "accelbyte/iam/models/AdminVerifyRegistrationCode.h"
#include "accelbyte/iam/models/WebLink.h"
#include "accelbyte/iam/models/UserUnbanCreateRequestV3.h"
#include "accelbyte/iam/models/Revocations.h"
#include "accelbyte/iam/models/JWKKey.h"
#include "accelbyte/iam/models/JWKSet.h"
#include "accelbyte/iam/models/UserRevocationRecords.h"
#include "accelbyte/iam/models/CountryLocation.h"
#include "accelbyte/iam/models/Error.h"
#include "accelbyte/iam/models/LoginQueueTicket.h"
#include "accelbyte/iam/models/OneTimeLinkCode.h"
#include "accelbyte/iam/models/OneTimeLinkCodeValidation.h"
#include "accelbyte/iam/models/PlatformTokenRefreshV3.h"
#include "accelbyte/iam/models/TargetTokenCode.h"
#include "accelbyte/iam/models/TicketEndpointAction.h"
#include "accelbyte/iam/models/TokenIntrospect.h"
#include "accelbyte/iam/models/Token.h"
#include "accelbyte/iam/models/TokenV3.h"
#include "accelbyte/iam/models/TokenThirdParty.h"
#include "accelbyte/iam/models/TokenDeviceCookieV3.h"
#include "accelbyte/iam/models/UserBan.h"
#include "accelbyte/iam/models/Error.h"
#include "accelbyte/iam/models/6a19ab71422e393latformAccounts.h"
#include "accelbyte/iam/models/Permission.h"
#include "accelbyte/common/Error.h"
#include "accelbyte/tls/SecurityAuthorization.h"

#include <functional>
#include "accelbyte/memory/memory.h"

namespace accelbyte {
namespace iam {

class OAuth20Extension
{
public:	
    /**
    * @brief Authentication API
    * @details This endpoint is being used to authenticate a user account. 
It validates user&#39;s email / username and password.
Deactivated or login-banned users are unable to login.
Redirect URI and Client ID must be specified as a pair and only used to redirect to the specified redirect URI in case the requestId is no longer valid.

## Device Cookie Validation

Device Cookie is used to protect the user account from brute force login attack, [more detail from OWASP](https://owasp.org/www-community/Slow_Down_Online_Guessing_Attacks_with_Device_Cookies).
This endpoint will read device cookie from cookie **auth-trust-id**. If device cookie not found, it will generate a new one and set it into cookie when successfully authenticate.

Action code: 10801
    * @details /iam/v3/authenticate
    *
    */
    AB_iam_EXPORT static void user_authentication_v3(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const o_auth2_0_extension::UserAuthenticationV3& request, 
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Authentication with platform link
    * @details This endpoint is being used to authenticate a user account and perform platform link. 
It validates user&#39;s email / username and password. 
If user already enable 2FA, then invoke _/mfa/verify_ using **mfa_token** from this endpoint response.

## Device Cookie Validation

Device Cookie is used to protect the user account from brute force login attack, [more detail from OWASP](https://owasp.org/www-community/Slow_Down_Online_Guessing_Attacks_with_Device_Cookies).
This endpoint will read device cookie from cookie **auth-trust-id**. If device cookie not found, it will generate a new one and set it into cookie when successfully authenticate.
    * @details /iam/v3/authenticateWithLink
    *
    */
    AB_iam_EXPORT static void authentication_platform_link_v3(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const o_auth2_0_extension::AuthenticationPlatformLinkV3& request, 
        const std::function<void(const model::TokenV3&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Create headless account and response token
    * @details This endpoint is being used to create headless account after 3rd platform authenticated, and response token . 
The &#39;linkingToken&#39; in request body is received from &#34;/platforms/{platformId}/token&#34; 
when 3rd platform account is not linked to justice account yet.
    * @details /iam/v3/headless/token
    *
    */
    AB_iam_EXPORT static void generate_token_by_headless_account_v3(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const o_auth2_0_extension::GenerateTokenByHeadlessAccountV3& request, 
        const std::function<void(const model::TokenV3&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Generate one time linking code
    * @details This endpoint is being used to request the one time code [8 length] for headless account to link or upgrade to a full account.
Should specify the target platform id and current user should already linked to this platform.
Current user should be a headless account.
## Supported platforms:
- **steam**
- **steamopenid**
- **facebook**
- **google**
- **googleplaygames**
- **oculus**
- **twitch**
- **discord**
- **android**
- **ios**
- **apple**
- **device**
- **justice**
- **epicgames**
- **ps4**
- **ps5**
- **nintendo**
- **awscognito**
- **live**
- **xblweb**
- **netflix**
- **snapchat**
    * @details /iam/v3/link/code/request
    *
    */
    AB_iam_EXPORT static void one_time_link_code_v3_request(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const o_auth2_0_extension::OneTimeLinkCodeV3Request& request, 
        const std::function<void(const model::OneTimeLinkCode&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Validate one time linking code
    * @details This endpoint is being used to validate one time link code.
    * @details /iam/v3/link/code/validate
    *
    */
    AB_iam_EXPORT static void validate_one_time_link_code_v3(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const o_auth2_0_extension::ValidateOneTimeLinkCodeV3& request, 
        const std::function<void(const model::OneTimeLinkCodeValidation&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Generate publisher token by headless account's one time link code
    * @details This endpoint is being used to generate user&#39;s token by one time link code.
It require publisher ClientID
It required a code which can be generated from &lt;code&gt;/iam/v3/link/code/request&lt;/code&gt;.

This endpoint support creating transient token by utilizing **isTransient** param:
**isTransient=true** will generate a transient token with a short Time Expiration and without a refresh token
**isTransient=false** will consume the one-time code and generate the access token with a refresh token.
    * @details /iam/v3/link/token/exchange
    *
    */
    AB_iam_EXPORT static void request_token_by_one_time_link_code_v3(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const o_auth2_0_extension::RequestTokenByOneTimeLinkCodeV3& request, 
        const std::function<void(const model::TokenV3&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Get Country Location
    * @details This endpoint get country location based on the request.
    * @details /iam/v3/location/country
    *
    */
    AB_iam_EXPORT static void get_country_location_v3(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const o_auth2_0_extension::GetCountryLocationV3& request, 
        const std::function<void(const model::CountryLocation&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Logout
    * @details This endpoint is used to remove **access_token**, **refresh_token** from cookie.
    * @details /iam/v3/logout
    *
    */
    AB_iam_EXPORT static void logout(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const o_auth2_0_extension::Logout& request, 
        const std::function<void()>& on_204,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Request code to get a new token
    * @details This endpoint is being used to request the code to exchange a new token. 
The target new token&#39;s clientId should NOT be same with current using one.
Path namespace should be target namespace.
Client ID should match the target namespace.

The code in response can be consumed by &lt;code&gt;/iam/v3/token/exchange&lt;/code&gt;
    * @details /iam/v3/namespace/{namespace}/token/request
    *
    */
    AB_iam_EXPORT static void request_token_exchange_code_v3(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const o_auth2_0_extension::RequestTokenExchangeCodeV3& request, 
        const std::function<void(const model::TargetTokenCode&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Platform Authentication API
    * @details This endpoint authenticates user platform. It validates user to its
respective platforms. Deactivated or login-banned users are unable to login.
If already linked with justice account or match SSO condition, will redirect to client&#39;s redirect url with code. then invoke &#39;/iam/v3/oauth/token&#39; with grant_type=authorization_code	
If already not linked with justice account and not match SSO condition, will redirect to client&#39;s account linking page	
## Supported platforms:
- **steamopenid**Steam login page will redirects to this endpoint after login success
	as previously defined on openID request parameter &lt;code&gt;openid.return_to&lt;/code&gt; when request login to steam
	https://openid.net/specs/openid-authentication-2_0.html#anchor27
- **ps4web**PS4 login page will redirects to this endpoint after login success
	as previously defined on authorize request parameter &lt;code&gt;redirect_uri&lt;/code&gt; 
	https://ps4.siedev.net/resources/documents/WebAPI/1/Auth_WebAPI-Reference/0002.html#0GetAccessTokenUsingAuthorizationCode
- **xblweb**XBL login page will redirects to this endpoint after login success
	as previously defined on authorize request parameter &lt;code&gt;redirect_uri&lt;/code&gt; 
- **epicgames**Epicgames login page will redirects to this endpoint after login success
	or an error occurred. If error, it redirects to the login page.
- **twitch**Twitch login page will redirects to this endpoint after login success
	as previously defined on authorize request parameter &lt;code&gt;redirect_uri&lt;/code&gt;
- **facebook**Facebook login page will redirects to this endpoint after login success
	as previously defined on authorize request parameter &lt;code&gt;redirect_uri&lt;/code&gt;
- **google**Google login page will redirects to this endpoint after login success
	as previously defined on authorize request parameter &lt;code&gt;redirect_uri&lt;/code&gt;
- **snapchat**Snapchat login page will redirects to this endpoint after login success
	as previously defined on authorize request parameter &lt;code&gt;redirect_uri&lt;/code&gt;
- **discord**Discord login page will redirects to this endpoint after login success
	as previously defined on authorize request parameter &lt;code&gt;redirect_uri&lt;/code&gt;
action code : 10709
    * @details /iam/v3/platforms/{platformId}/authenticate
    *
    */
    AB_iam_EXPORT static void get_platform_authentication_v3(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const o_auth2_0_extension::GetPlatformAuthenticationV3& request, 
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Platform Token Validation
    * @details This endpoint will validate the third party platform token, for some platforms will also refresh the token stored in IAM, it will not generate any event or AB access/refresh token.
This endpoint can be used by game client to refresh third party token if game client got platform token not found error, for example got 404 
platform token not found from IAP/DLC.

## Platforms will refresh stored token:
- **twitch**: The platform_token’s value is the authorization code returned by Twitch OAuth.
- **epicgames**: The platform_token’s value is an access-token or authorization code obtained from Epicgames EOS Account Service.
- **ps4**: The platform_token’s value is the authorization code returned by Sony OAuth.
- **ps5**: The platform_token’s value is the authorization code returned by Sony OAuth.
- **amazon**: The platform_token’s value is authorization code.
- **awscognito**: The platform_token’s value is the aws cognito access token or id token (JWT).
- **live**: The platform_token’s value is xbox XSTS token
- **snapchat**: The platform_token’s value is the authorization code returned by Snapchat OAuth.
- **for specific generic oauth (OIDC)**: The platform_token’s value should be the same type as created OIDC auth type whether it is auth code, idToken or bearerToken.
    * @details /iam/v3/platforms/{platformId}/token/verify
    *
    */
    AB_iam_EXPORT static void verify_platform_token_refresh_v3(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const o_auth2_0_extension::VerifyPlatformTokenRefreshV3& request, 
        const std::function<void(const model::PlatformTokenRefreshV3&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Generate target token by code
    * @details This endpoint is being used to generate target token.
It requires basic header with ClientID and Secret, it should match the ClientID when call &lt;code&gt;/iam/v3/namespace/{namespace}/token/request&lt;/code&gt;
The code should be generated from &lt;code&gt;/iam/v3/namespace/{namespace}/token/request&lt;/code&gt;.
    * @details /iam/v3/token/exchange
    *
    */
    AB_iam_EXPORT static void generate_target_token_v3(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const o_auth2_0_extension::GenerateTargetTokenV3& request, 
        const std::function<void(const model::TokenV3&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

};

}
}