// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/http/ModelObject.h"
#include "accelbyte/common/Optional.h"
#include "accelbyte/common/String.h"
#include "accelbyte/common/Map.h"
#include "accelbyte/common/Vector.h"
#include "accelbyte/common/DateTime.h"
#include "accelbyte/memory/memory.h"
#include "accelbyte/utils/JsonObjectString.h"
#include "accelbyte/cloudsave/cloudsave_export.h"

#include "accelbyte/cloudsave/models/TTLConfig.h"

namespace accelbyte {
namespace cloudsave {
namespace model {

class AdminGameBinaryRecordCreate : public accelbyte::http::ModelObject
{
public:
    enum class SetBy : uint32_t {
        UNKNOWN,
        CLIENT,
        SERVER
    };
    /**
    * @brief default constructor.
    **/
	AB_cloudsave_EXPORT  AdminGameBinaryRecordCreate() = default;
	
    /**
    * @brief destructor.
    **/
    AB_cloudsave_EXPORT virtual ~AdminGameBinaryRecordCreate() = default;
	
	/**
    * @brief Return the object unique id (used for serialization)
    **/
    AB_cloudsave_EXPORT virtual const String& model_id() const override;
	
	/**
    * @brief Return the unique id that can be used to determine this class (used for serialization)
    **/
    AB_cloudsave_EXPORT static const String& model_object_id();
    
    // start of usefull parameters
	accelbyte::String file_type{};
	accelbyte::String key{};
	SetBy set_by{SetBy::CLIENT};
	accelbyte::Optional<TTLConfig> ttl_config{};
};

}
}
}