// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/http/SendableObject.h"
#include "accelbyte/common/DateTime.h"
#include "accelbyte/utils/JsonObjectString.h"
#include "accelbyte/common/Optional.h"
#include "accelbyte/iam/iam_export.h"

#include "accelbyte/common/String.h"
#include "accelbyte/common/Map.h"
#include "accelbyte/common/Vector.h"


namespace accelbyte {
namespace iam {
namespace users {

/**
* @brief Admin get the link status of the third party platform token with user id.

This endpoint is used for checking whether the third party user represented by third party token is 
linked with the corresponding user id.

## Supported platforms:
- **steam**: The platform_token’s value is the authentication code returned by Steam.
- **steamopenid**: Steam&#39;s user authentication method using OpenID 2.0. The platform_token&#39;s value is URL generated by Steam on web authentication
- **facebook**: The platform_token’s value is the authorization code returned by Facebook OAuth
- **google**: The platform_token’s value is the authorization code returned by Google OAuth
- **googleplaygames**: The platform_token’s value is the authorization code returned by Google play games OAuth
- **oculus**: The platform_token’s value is a string composed of Oculus&#39;s user ID and the nonce separated by a colon (:).
- **twitch**: The platform_token’s value is the authorization code returned by Twitch OAuth.
- **discord**: The platform_token’s value is the authorization code returned by Discord OAuth
- **android**: The device_id is the Android’s device ID
- **ios**: The device_id is the iOS’s device ID.
- **apple**: The platform_token’s value is the authorization code returned by Apple OAuth.(We will use this code to generate APP token)
- **device**: Every device that does’nt run Android and iOS is categorized as a device. The device_id is the device’s ID.
- **justice**: The platform_token’s value is the designated user’s access token.
- **epicgames**: The platform_token’s value is an access-token obtained from Epicgames EOS Account Service.
- **ps4**: The platform_token’s value is the authorization code returned by Sony OAuth.
- **ps5**: The platform_token’s value is the authorization code returned by Sony OAuth.
- **nintendo**: The platform_token’s value is the authorization code(id_token) returned by Nintendo OAuth.
- **awscognito**: The platform_token’s value is the aws cognito access token or id token (JWT).
- **live**: The platform_token’s value is xbox XSTS token
- **xblweb**: The platform_token’s value is code returned by xbox after login
- **netflix**: The platform_token’s value is GAT (Gamer Access Token) returned by Netflix backend
- **snapchat**: The platform_token’s value is the authorization code returned by Snapchat OAuth.

*/
class AdminGetThirdPartyPlatformTokenLinkStatusV3 : public accelbyte::http::SendableObject
{
public:
    
    
    /**
    * @brief default constructor.
    **/
	AB_iam_EXPORT AdminGetThirdPartyPlatformTokenLinkStatusV3() = default;
	
    /**
    * @brief destrutor.
    **/
    AB_iam_EXPORT virtual ~AdminGetThirdPartyPlatformTokenLinkStatusV3() = default;
	
	/**
    * @brief Return the object unique id (used for serialization)
    **/
    AB_iam_EXPORT const String& sendable_id() const override;
	
	/**
    * @brief Return the unique id that can be used to determine this class (used for serialization)
    **/
    AB_iam_EXPORT static const String& sendable_object_id();
	
    // usefull parameters    
     /**
     * @brief Platform Token
    **/
    accelbyte::String platform_token{};
     /**
     * @brief Namespace, only accept alphabet and numeric
if not set the user namespace will be used.
    **/
    accelbyte::Optional<accelbyte::String> ab_namespace{};
     /**
     * @brief Platform ID
    **/
    accelbyte::String platform_id{};
     /**
     * @brief UserId
    **/
    accelbyte::String user_id{};
};

}
}
}