// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/http/SendableObject.h"
#include "accelbyte/common/DateTime.h"
#include "accelbyte/utils/JsonObjectString.h"
#include "accelbyte/common/Optional.h"
#include "accelbyte/iam/iam_export.h"

#include "accelbyte/common/String.h"
#include "accelbyte/common/Map.h"
#include "accelbyte/common/Vector.h"

#include "accelbyte/iam/models/BanUpdateRequest.h"

namespace accelbyte {
namespace iam {
namespace users {

/**
* @brief Set ban status for a single user for a specific ban. Retrieve
user ban and choose the ban ID. Set the form parameter to true/false to enable
or disable the ban.
action code : 10142&#39;
*/
class AdminUpdateUserBanV3 : public accelbyte::http::SendableObject
{
public:
    
    
    /**
    * @brief default constructor.
    **/
	AB_iam_EXPORT AdminUpdateUserBanV3() = default;
	
    /**
    * @brief destrutor.
    **/
    AB_iam_EXPORT virtual ~AdminUpdateUserBanV3() = default;
	
	/**
    * @brief Return the object unique id (used for serialization)
    **/
    AB_iam_EXPORT const String& sendable_id() const override;
	
	/**
    * @brief Return the unique id that can be used to determine this class (used for serialization)
    **/
    AB_iam_EXPORT static const String& sendable_object_id();
	
    // usefull parameters    
     /**
     * @brief None
    **/
    model::BanUpdateRequest body{};
     /**
     * @brief Ban ID, should follow UUID version 4 without hyphen
    **/
    accelbyte::String ban_id{};
     /**
     * @brief Namespace, only accept alphabet and numeric
if not set the user namespace will be used.
    **/
    accelbyte::Optional<accelbyte::String> ab_namespace{};
     /**
     * @brief User ID, should follow UUID version 4 without hyphen
    **/
    accelbyte::String user_id{};
};

}
}
}