// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/http/SendableObject.h"
#include "accelbyte/common/DateTime.h"
#include "accelbyte/utils/JsonObjectString.h"
#include "accelbyte/common/Optional.h"
#include "accelbyte/iam/iam_export.h"

#include "accelbyte/common/String.h"
#include "accelbyte/common/Map.h"
#include "accelbyte/common/Vector.h"


namespace accelbyte {
namespace iam {
namespace users {

/**
* @brief This endpoint search all users on the specified namespace that match the query on these fields: display name, unique display name, username or by 3rd party display name.
The query length should between 3-20, otherwise will not query the database. 
The default limit value is 20.

## Searching by 3rd party platform

**Note: searching by 3rd party platform display name will use exact query, not fuzzy query.**

Step when searching by 3rd party platform display name:
  1. set __by__ to __thirdPartyPlatform__
  2. set __platformId__ to the _supported platform id_
  3. set __platformBy__ to __platformDisplayName__


**Supported Platforms:**
- Steam group (steamnetwork):
	- steam
	- steamopenid
- PSN group (psn):
	- ps4web
	- ps4
	- ps5
- XBOX group(xbox):
	- live
	- xblweb
- Oculus group (oculusgroup):
	- oculus
	- oculusweb
- Google group (google):
	- google
	- googleplaygames:
- epicgames
- facebook
- twitch
- discord
- android
- ios
- apple
- device
- nintendo
- awscognito
- amazon
- netflix
- snapchat
- _oidc platform id_

Note:
- You can use either platform id or platform group as **platformId** parameter.
- **Nintendo platform user id**: NSA ID need to be appended with Environment ID using colon as separator. e.g kmzwa8awaa:dd1


*/
class SearchUserV3 : public accelbyte::http::SendableObject
{
public:
    
    
    /**
    * @brief default constructor.
    **/
	AB_iam_EXPORT SearchUserV3() = default;
	
    /**
    * @brief destrutor.
    **/
    AB_iam_EXPORT virtual ~SearchUserV3() = default;
	
	/**
    * @brief Return the object unique id (used for serialization)
    **/
    AB_iam_EXPORT const String& sendable_id() const override;
	
	/**
    * @brief Return the unique id that can be used to determine this class (used for serialization)
    **/
    AB_iam_EXPORT static const String& sendable_object_id();
	
    // usefull parameters    
     /**
     * @brief Namespace, only accept alphabet and numeric
if not set the user namespace will be used.
    **/
    accelbyte::Optional<accelbyte::String> ab_namespace{};
     /**
     * @brief Search by given attribute, possible values are displayName, uniqueDisplayName, username, and thirdPartyPlatform
    **/
    accelbyte::Optional<accelbyte::String> by{};
     /**
     * @brief The number of data retrieved in a page, default 20
    **/
    accelbyte::Optional<long> limit{};
     /**
     * @brief The number of offset, default 0
    **/
    accelbyte::Optional<long> offset{};
     /**
     * @brief Search platformBy given attribute, possible value is platformDisplayName
    **/
    accelbyte::Optional<accelbyte::String> platform_by{};
     /**
     * @brief Platform Id that want to be searched.
    **/
    accelbyte::Optional<accelbyte::String> platform_id{};
     /**
     * @brief Query, can be either display name or username. Max character is 50
    **/
    accelbyte::Optional<accelbyte::String> query{};
};

}
}
}