// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/http/SendableObject.h"
#include "accelbyte/common/DateTime.h"
#include "accelbyte/utils/JsonObjectString.h"
#include "accelbyte/common/Optional.h"
#include "accelbyte/iam/iam_export.h"

#include "accelbyte/common/String.h"
#include "accelbyte/common/Map.h"
#include "accelbyte/common/Vector.h"

#include "accelbyte/iam/models/UserInputValidationRequest.h"

namespace accelbyte {
namespace iam {
namespace users {

/**
* @brief Validate user&#39;s input. 
--------
**note:** 
- this endpoint will check the input validation and profanity filter service(if this is enabled)
- the namespace should be publisher namespace

*/
class ValidateUserInput : public accelbyte::http::SendableObject
{
public:
    
    
    /**
    * @brief default constructor.
    **/
	AB_iam_EXPORT ValidateUserInput() = default;
	
    /**
    * @brief destrutor.
    **/
    AB_iam_EXPORT virtual ~ValidateUserInput() = default;
	
	/**
    * @brief Return the object unique id (used for serialization)
    **/
    AB_iam_EXPORT const String& sendable_id() const override;
	
	/**
    * @brief Return the unique id that can be used to determine this class (used for serialization)
    **/
    AB_iam_EXPORT static const String& sendable_object_id();
	
    // usefull parameters    
     /**
     * @brief None
    **/
    model::UserInputValidationRequest body{};
     /**
     * @brief Namespace, only accept alphabet and numeric
if not set the user namespace will be used.
    **/
    accelbyte::Optional<accelbyte::String> ab_namespace{};
};

}
}
}