// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/http/SendableObject.h"
#include "accelbyte/common/DateTime.h"
#include "accelbyte/utils/JsonObjectString.h"
#include "accelbyte/common/Optional.h"
#include "accelbyte/platform/platform_export.h"

#include "accelbyte/common/String.h"
#include "accelbyte/common/Map.h"
#include "accelbyte/common/Vector.h"


namespace accelbyte {
namespace platform {
namespace item {

/**
* @brief This API is used to get an item by sku in specific locale. If item not exist in specific region, default region item will return.&lt;p&gt;Other detail info: &lt;ul&gt;&lt;li&gt;&lt;i&gt;Returns&lt;/i&gt;: item data&lt;/li&gt;&lt;/ul&gt;
*/
class AdminGetLocaleItemBySku : public accelbyte::http::SendableObject
{
public:
    
    
    /**
    * @brief default constructor.
    **/
	AB_platform_EXPORT AdminGetLocaleItemBySku() = default;
	
    /**
    * @brief destrutor.
    **/
    AB_platform_EXPORT virtual ~AdminGetLocaleItemBySku() = default;
	
	/**
    * @brief Return the object unique id (used for serialization)
    **/
    AB_platform_EXPORT const String& sendable_id() const override;
	
	/**
    * @brief Return the unique id that can be used to determine this class (used for serialization)
    **/
    AB_platform_EXPORT static const String& sendable_object_id();
	
    // usefull parameters    
     /**
     * @brief Namespace
if not set the user namespace will be used.
    **/
    accelbyte::Optional<accelbyte::String> ab_namespace{};
     /**
     * @brief None
    **/
    accelbyte::String sku{};
     /**
     * @brief None
    **/
    accelbyte::Optional<bool> active_only{};
     /**
     * @brief None
    **/
    accelbyte::Optional<accelbyte::String> language{};
     /**
     * @brief whether populate bundled items if it's a bundle
    **/
    accelbyte::Optional<bool> populate_bundle{};
     /**
     * @brief None
    **/
    accelbyte::Optional<accelbyte::String> region{};
     /**
     * @brief default is published store id
    **/
    accelbyte::Optional<accelbyte::String> store_id{};
};

}
}
}