// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/http/SendableObject.h"
#include "accelbyte/common/DateTime.h"
#include "accelbyte/utils/JsonObjectString.h"
#include "accelbyte/common/Optional.h"
#include "accelbyte/reporting/reporting_export.h"

#include "accelbyte/common/String.h"
#include "accelbyte/common/Map.h"
#include "accelbyte/common/Vector.h"


namespace accelbyte {
namespace reporting {
namespace admin_extension_categories_and_auto_moderation_actions {

/**
* @brief Get a list of extension category data with the specified name
*/
class AdminFindExtensionCategories : public accelbyte::http::SendableObject
{
public:
    
    enum class Order : uint32_t {
        UNKNOWN,
        ASC,
        ASCENDING,
        DESC,
        DESCENDING
    };
    enum class SortBy : uint32_t {
        UNKNOWN,
        EXTENSION_CATEGORY,
        EXTENSION_CATEGORY_NAME
    };
    
    /**
    * @brief default constructor.
    **/
	AB_reporting_EXPORT AdminFindExtensionCategories() = default;
	
    /**
    * @brief destrutor.
    **/
    AB_reporting_EXPORT virtual ~AdminFindExtensionCategories() = default;
	
	/**
    * @brief Return the object unique id (used for serialization)
    **/
    AB_reporting_EXPORT const String& sendable_id() const override;
	
	/**
    * @brief Return the unique id that can be used to determine this class (used for serialization)
    **/
    AB_reporting_EXPORT static const String& sendable_object_id();
	
    // usefull parameters    
     /**
     * @brief data order, asc or desc (default: asc)
    **/
    accelbyte::Optional<Order> order{};
     /**
     * @brief data order key, valid key : 'extensionCategory', and 'extensionCategoryName'
    **/
    accelbyte::Optional<SortBy> sort_by{};
};

}
}
}