// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/http/SendableObject.h"
#include "accelbyte/common/DateTime.h"
#include "accelbyte/utils/JsonObjectString.h"
#include "accelbyte/common/Optional.h"
#include "accelbyte/legal/legal_export.h"

#include "accelbyte/common/String.h"
#include "accelbyte/common/Map.h"
#include "accelbyte/common/Vector.h"


namespace accelbyte {
namespace legal {
namespace localized_policy_versions {

/**
* @brief Update a localized version policy to be the default.
*/
class AdminSetDefaultLocalPolicy : public accelbyte::http::SendableObject
{
public:
    
    
    /**
    * @brief default constructor.
    **/
	AB_legal_EXPORT AdminSetDefaultLocalPolicy() = default;
	
    /**
    * @brief destrutor.
    **/
    AB_legal_EXPORT virtual ~AdminSetDefaultLocalPolicy() = default;
	
	/**
    * @brief Return the object unique id (used for serialization)
    **/
    AB_legal_EXPORT const String& sendable_id() const override;
	
	/**
    * @brief Return the unique id that can be used to determine this class (used for serialization)
    **/
    AB_legal_EXPORT static const String& sendable_object_id();
	
    // usefull parameters    
     /**
     * @brief Localized Policy Version Id
    **/
    accelbyte::String localized_policy_version_id{};
};

}
}
}