// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/http/SendableObject.h"
#include "accelbyte/common/DateTime.h"
#include "accelbyte/utils/JsonObjectString.h"
#include "accelbyte/common/Optional.h"
#include "accelbyte/gdpr/gdpr_export.h"

#include "accelbyte/common/String.h"
#include "accelbyte/common/Map.h"
#include "accelbyte/common/Vector.h"


namespace accelbyte {
namespace gdpr {
namespace data_retrieval {

/**
* @brief Get user&#39;s personal data requests
Scope: account
*/
class AdminGetUserPersonalData : public accelbyte::http::SendableObject
{
public:
    
    
    /**
    * @brief default constructor.
    **/
	AB_gdpr_EXPORT AdminGetUserPersonalData() = default;
	
    /**
    * @brief destrutor.
    **/
    AB_gdpr_EXPORT virtual ~AdminGetUserPersonalData() = default;
	
	/**
    * @brief Return the object unique id (used for serialization)
    **/
    AB_gdpr_EXPORT const String& sendable_id() const override;
	
	/**
    * @brief Return the unique id that can be used to determine this class (used for serialization)
    **/
    AB_gdpr_EXPORT static const String& sendable_object_id();
	
    // usefull parameters    
     /**
     * @brief namespace
if not set the user namespace will be used.
    **/
    accelbyte::Optional<accelbyte::String> ab_namespace{};
     /**
     * @brief IAM id of the user
    **/
    accelbyte::String user_id{};
     /**
     * @brief the maximum number of data that may be returned (1...100)
    **/
    accelbyte::Optional<long> limit{};
     /**
     * @brief The start position that points to query data
    **/
    accelbyte::Optional<long> offset{};
};

}
}
}