// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/http/SendableObject.h"
#include "accelbyte/common/DateTime.h"
#include "accelbyte/utils/JsonObjectString.h"
#include "accelbyte/common/Optional.h"
#include "accelbyte/legal/legal_export.h"

#include "accelbyte/common/String.h"
#include "accelbyte/common/Map.h"
#include "accelbyte/common/Vector.h"


namespace accelbyte {
namespace legal {
namespace admin_user_eligibilities {

/**
* @brief Retrieve the active policies and its conformance status by user.&lt;br&gt;This process only supports cross-namespace checking between game namespace and publisher namespace , that means if the active policy already accepted by the same user in publisher namespace, then it will also be considered as eligible in non-publisher namespace.
*/
class AdminListEligibilities : public accelbyte::http::SendableObject
{
public:
    
    
    /**
    * @brief default constructor.
    **/
	AB_legal_EXPORT AdminListEligibilities() = default;
	
    /**
    * @brief destrutor.
    **/
    AB_legal_EXPORT virtual ~AdminListEligibilities() = default;
	
	/**
    * @brief Return the object unique id (used for serialization)
    **/
    AB_legal_EXPORT const String& sendable_id() const override;
	
	/**
    * @brief Return the unique id that can be used to determine this class (used for serialization)
    **/
    AB_legal_EXPORT static const String& sendable_object_id();
	
    // usefull parameters    
     /**
     * @brief Namespace
if not set the user namespace will be used.
    **/
    accelbyte::Optional<accelbyte::String> ab_namespace{};
     /**
     * @brief User Id
    **/
    accelbyte::String user_id{};
     /**
     * @brief Client Id
    **/
    accelbyte::String client_id{};
     /**
     * @brief Country Code
    **/
    accelbyte::String country_code{};
     /**
     * @brief Publisher user Id
    **/
    accelbyte::Optional<accelbyte::String> publisher_user_id{};
};

}
}
}