// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/http/SendableObject.h"
#include "accelbyte/common/DateTime.h"
#include "accelbyte/utils/JsonObjectString.h"
#include "accelbyte/common/Optional.h"
#include "accelbyte/ugc/ugc_export.h"

#include "accelbyte/common/String.h"
#include "accelbyte/common/Map.h"
#include "accelbyte/common/Vector.h"


namespace accelbyte {
namespace ugc {
namespace public_channel {

/**
* @brief Get user channel paginated
*/
class GetChannels : public accelbyte::http::SendableObject
{
public:
    
    
    /**
    * @brief default constructor.
    **/
	AB_ugc_EXPORT GetChannels() = default;
	
    /**
    * @brief destrutor.
    **/
    AB_ugc_EXPORT virtual ~GetChannels() = default;
	
	/**
    * @brief Return the object unique id (used for serialization)
    **/
    AB_ugc_EXPORT const String& sendable_id() const override;
	
	/**
    * @brief Return the unique id that can be used to determine this class (used for serialization)
    **/
    AB_ugc_EXPORT static const String& sendable_object_id();
	
    // usefull parameters    
     /**
     * @brief namespace of the game
if not set the user namespace will be used.
    **/
    accelbyte::Optional<accelbyte::String> ab_namespace{};
     /**
     * @brief userID
    **/
    accelbyte::String user_id{};
     /**
     * @brief number of content per page
    **/
    accelbyte::Optional<long> limit{};
     /**
     * @brief likes filter by channel name
    **/
    accelbyte::Optional<accelbyte::String> name{};
     /**
     * @brief the offset number to retrieve
    **/
    accelbyte::Optional<long> offset{};
};

}
}
}