// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/http/SendableObject.h"
#include "accelbyte/common/DateTime.h"
#include "accelbyte/utils/JsonObjectString.h"
#include "accelbyte/common/Optional.h"
#include "accelbyte/iam/iam_export.h"

#include "accelbyte/common/String.h"
#include "accelbyte/common/Map.h"
#include "accelbyte/common/Vector.h"


namespace accelbyte {
namespace iam {
namespace o_auth {

/**
* @brief ## The endpoint is going to be deprecated
This endpoint requires all requests to have authorization header set with bearer token.

The endpoint revokes all access tokens and refresh tokens a user has prior the revocation time. It is a convenient feature for the developer (or admin) who wanted to revokes all user&#39;s access tokens and refresh tokens generated before some period of time.
### Endpoint migration guide
- **Substitute endpoint: _/iam/v3/oauth/admin/namespaces/{namespace}/users/{userId}/revoke [POST]_**
*/
class RevokeUser : public accelbyte::http::SendableObject
{
public:
    
    
    /**
    * @brief default constructor.
    **/
	AB_iam_EXPORT RevokeUser() = default;
	
    /**
    * @brief destrutor.
    **/
    AB_iam_EXPORT virtual ~RevokeUser() = default;
	
	/**
    * @brief Return the object unique id (used for serialization)
    **/
    AB_iam_EXPORT const String& sendable_id() const override;
	
	/**
    * @brief Return the unique id that can be used to determine this class (used for serialization)
    **/
    AB_iam_EXPORT static const String& sendable_object_id();
	
    // usefull parameters    
     /**
     * @brief namespace
if not set the user namespace will be used.
    **/
    accelbyte::Optional<accelbyte::String> ab_namespace{};
     /**
     * @brief User to be revoked
    **/
    accelbyte::String user_id{};
};

}
}
}