// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/http/ModelObject.h"
#include "accelbyte/common/Optional.h"
#include "accelbyte/common/String.h"
#include "accelbyte/common/Map.h"
#include "accelbyte/common/Vector.h"
#include "accelbyte/common/DateTime.h"
#include "accelbyte/memory/memory.h"
#include "accelbyte/utils/JsonObjectString.h"
#include "accelbyte/login_queue/login_queue_export.h"


namespace accelbyte {
namespace login_queue {
namespace model {

class TokenValidation : public accelbyte::http::ModelObject
{
public:
    /**
    * @brief default constructor.
    **/
	AB_login_queue_EXPORT  TokenValidation() = default;
	
    /**
    * @brief destructor.
    **/
    AB_login_queue_EXPORT virtual ~TokenValidation() = default;
	
	/**
    * @brief Return the object unique id (used for serialization)
    **/
    AB_login_queue_EXPORT virtual const String& model_id() const override;
	
	/**
    * @brief Return the unique id that can be used to determine this class (used for serialization)
    **/
    AB_login_queue_EXPORT static const String& model_object_id();
    
    // start of usefull parameters
	accelbyte::String user_id{};
};

}
}
}