// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/social/social_export.h"
#include "accelbyte/social/user_statistic/AdminGetStatItems.h"
#include "accelbyte/social/user_statistic/AdminUpdateUsersStatItemsValue.h"
#include "accelbyte/social/user_statistic/AdminUpdateUsersStatItem.h"
#include "accelbyte/social/user_statistic/AdminDefaultGetStatItems.h"
#include "accelbyte/social/user_statistic/AdminResetUsersStatItems.h"
#include "accelbyte/social/user_statistic/AdminGetStatItemsByStatCode.h"
#include "accelbyte/social/user_statistic/AdminGetUserStatItems.h"
#include "accelbyte/social/user_statistic/AdminCreateUserStatItems.h"
#include "accelbyte/social/user_statistic/AdminUpdateUserStatItemsValue.h"
#include "accelbyte/social/user_statistic/AdminUpdateUserStatItem.h"
#include "accelbyte/social/user_statistic/AdminResetUserStatItemsValue.h"
#include "accelbyte/social/user_statistic/AdminDeleteUserStatItems.h"
#include "accelbyte/social/user_statistic/AdminCreateUserStatItem.h"
#include "accelbyte/social/user_statistic/AdminIncUserStatItemValue.h"
#include "accelbyte/social/user_statistic/AdminResetUserStatItemValue.h"
#include "accelbyte/social/user_statistic/GetStatItems.h"
#include "accelbyte/social/user_statistic/UpdateUsersStatItemsValue.h"
#include "accelbyte/social/user_statistic/e9bbbfcb55d7e37sStatItemsValue.h"
#include "accelbyte/social/user_statistic/ResetUsersStatItems.h"
#include "accelbyte/social/user_statistic/GetMyStatItems.h"
#include "accelbyte/social/user_statistic/GetAllStatItems.h"
#include "accelbyte/social/user_statistic/GetUserStatItemValue.h"
#include "accelbyte/social/user_statistic/CreateUserStatItems.h"
#include "accelbyte/social/user_statistic/GetUserStatItemsValue.h"
#include "accelbyte/social/user_statistic/UpdateUserStatItemsValue.h"
#include "accelbyte/social/user_statistic/UpdateCreateUserStatItemsValue.h"
#include "accelbyte/social/user_statistic/ResetUserStatItemsValue.h"
#include "accelbyte/social/user_statistic/DeleteUserStatItems.h"
#include "accelbyte/social/user_statistic/CreateUserStatItem.h"
#include "accelbyte/social/user_statistic/UpdateUserStatItem.h"
#include "accelbyte/social/user_statistic/UpdateCreateUserStatItem.h"
#include "accelbyte/social/user_statistic/ResetUserStatItemValue.h"
#include "accelbyte/social/user_statistic/AdminUpdateUsersStatItemsV2.h"
#include "accelbyte/social/user_statistic/AdminDefaultGetStatItemsV2.h"
#include "accelbyte/social/user_statistic/AdminGetUsersStatItems.h"
#include "accelbyte/social/user_statistic/24a7d1f00afaddctatItemsValueV2.h"
#include "accelbyte/social/user_statistic/AdminGetStatItemsByUserIds.h"
#include "accelbyte/social/user_statistic/AdminResetUserStatItemsValueV2.h"
#include "accelbyte/social/user_statistic/AdminDeleteUserStatItemsV2.h"
#include "accelbyte/social/user_statistic/AdminUpdateUserStatItemValueV2.h"
#include "accelbyte/social/user_statistic/UpdateUsersStatItemsV2.h"
#include "accelbyte/social/user_statistic/GetUserStatItemsValueV2.h"
#include "accelbyte/social/user_statistic/UpdateUsersStatItemsValueV2.h"
#include "accelbyte/social/user_statistic/UpdateUserStatItemValueV2.h"
#include "accelbyte/social/models/UserStatItemsReset.h"
#include "accelbyte/social/models/UserStatItemValue.h"
#include "accelbyte/social/models/Attribute.h"
#include "accelbyte/social/models/CycleStatsAdds.h"
#include "accelbyte/social/models/StatCycleOperations.h"
#include "accelbyte/social/models/StatCyclesRequest.h"
#include "accelbyte/social/models/RequestedStatCycles.h"
#include "accelbyte/social/models/StatItemCreates.h"
#include "accelbyte/social/models/StatItemsInc.h"
#include "accelbyte/social/models/StatItemResets.h"
#include "accelbyte/social/models/StatItemUpdates.h"
#include "accelbyte/social/models/StatOperations.h"
#include "accelbyte/social/models/UserStatItemByStatCodes.h"
#include "accelbyte/social/models/UserStatItemIncs.h"
#include "accelbyte/social/models/UserStatItemResets.h"
#include "accelbyte/social/models/UserStatItemUpdates.h"
#include "accelbyte/social/models/CycleOverride.h"
#include "accelbyte/social/models/CycleOverrideRequest.h"
#include "accelbyte/social/models/Error.h"
#include "accelbyte/social/models/FieldValidationError.h"
#include "accelbyte/social/models/GameProfileHeader.h"
#include "accelbyte/social/models/GameProfile.h"
#include "accelbyte/social/models/GameProfilePublic.h"
#include "accelbyte/social/models/GameProfileRequest.h"
#include "accelbyte/social/models/GlobalStatItem.h"
#include "accelbyte/social/models/GlobalStatItems.h"
#include "accelbyte/social/models/NamespaceSlotConfig.h"
#include "accelbyte/social/models/Pagination.h"
#include "accelbyte/social/models/Permission.h"
#include "accelbyte/social/models/UpdateSlotConfig.h"
#include "accelbyte/social/models/Slot.h"
#include "accelbyte/social/models/UpdateSlotMetadata.h"
#include "accelbyte/social/models/CreateStat.h"
#include "accelbyte/social/models/CreateStatCycle.h"
#include "accelbyte/social/models/StatCycle.h"
#include "accelbyte/social/models/StatCycles.h"
#include "accelbyte/social/models/UpdateStatCycle.h"
#include "accelbyte/social/models/StatImport.h"
#include "accelbyte/social/models/Stat.h"
#include "accelbyte/social/models/StatItemIncRequest.h"
#include "accelbyte/social/models/StatItemInc.h"
#include "accelbyte/social/models/UpdateStatItem.h"
#include "accelbyte/social/models/StatItemValue.h"
#include "accelbyte/social/models/StatItemValues.h"
#include "accelbyte/social/models/Stats.h"
#include "accelbyte/social/models/StatReset.h"
#include "accelbyte/social/models/UpdateStat.h"
#include "accelbyte/social/models/UserGameProfiles.h"
#include "accelbyte/social/models/UserSlotConfig.h"
#include "accelbyte/social/models/UserStatCycleItem.h"
#include "accelbyte/social/models/UserStatCycleItems.h"
#include "accelbyte/social/models/UserStatItem.h"
#include "accelbyte/social/models/UserStatItems.h"
#include "accelbyte/social/models/ValidationError.h"
#include "accelbyte/common/Error.h"
#include "accelbyte/tls/SecurityAuthorization.h"

#include <functional>
#include "accelbyte/memory/memory.h"

namespace accelbyte {
namespace social {

class UserStatistic
{
public:	
    /**
    * @brief Bulk fetch statitems value
    * @details Bulk fetch multiple user&#39;s statitem value for a given namespace and statCode.  
Other detail info:
+ *Returns*: list of user&#39;s statItem
    * @details /social/v1/admin/namespaces/{namespace}/statitems/bulk
    *
    */
    AB_social_EXPORT static void admin_get_stat_items(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const user_statistic::AdminGetStatItems& request, 
        const std::function<void(const accelbyte::Vector<model::UserStatItem>&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Bulk update multiple user's statitems value
    * @details Bulk update multiple user&#39;s statitems value.&lt;br&gt;
    * @details /social/v1/admin/namespaces/{namespace}/statitems/value/bulk
    *
    */
    AB_social_EXPORT static void admin_update_users_stat_items_value(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const user_statistic::AdminUpdateUsersStatItemsValue& request, 
        const std::function<void(const accelbyte::Vector<model::StatOperations>&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Bulk update multiple user's statitems value
    * @details Bulk update multiple user&#39;s statitems value.&lt;br&gt;Other detail info:&lt;ul&gt;&lt;li&gt;&lt;i&gt;Returns&lt;/i&gt;: bulk updated result&lt;/li&gt;&lt;/ul&gt;
    * @details /social/v1/admin/namespaces/{namespace}/statitems/value/bulk
    *
    */
    AB_social_EXPORT static void admin_update_users_stat_item(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const user_statistic::AdminUpdateUsersStatItem& request, 
        const std::function<void(const accelbyte::Vector<model::StatOperations>&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Bulk fetch user stat item values
    * @details Bulk fetch multiple user&#39;s stat item values for a given namespace and statCode.
NOTE: If stat item does not exist, will return default value. Other detail info:
+ *Returns*: list of user&#39;s stat item values
    * @details /social/v1/admin/namespaces/{namespace}/statitems/value/bulk/getOrDefault
    *
    */
    AB_social_EXPORT static void admin_default_get_stat_items(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const user_statistic::AdminDefaultGetStatItems& request, 
        const std::function<void(const accelbyte::Vector<model::UserStatItemValue>&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Bulk reset multiple user's statitems value
    * @details Bulk reset multiple user&#39;s statitems value.
User&#39;s statitem value will be reset to the default value defined in the statistic configuration.

Other detail info:
+ *Returns*: bulk updated result
    * @details /social/v1/admin/namespaces/{namespace}/statitems/value/reset/bulk
    *
    */
    AB_social_EXPORT static void admin_reset_users_stat_items(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const user_statistic::AdminResetUsersStatItems& request, 
        const std::function<void(const accelbyte::Vector<model::StatOperations>&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Get users' stat item values by stat code
    * @details Get users&#39; stat item values for a given namespace and statCode.
Other info:
+ *Returns*: list of users&#39; stat item values
    * @details /social/v1/admin/namespaces/{namespace}/stats/{statCode}/statitems
    *
    */
    AB_social_EXPORT static void admin_get_stat_items_by_stat_code(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const user_statistic::AdminGetStatItemsByStatCode& request, 
        const std::function<void(const model::StatItemValues&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief List user's statItems
    * @details List user&#39;s statItems.&lt;br&gt;Other detail info:&lt;ul&gt;&lt;li&gt;&lt;i&gt;Returns&lt;/i&gt;: stat items&lt;/li&gt;&lt;/ul&gt;
    * @details /social/v1/admin/namespaces/{namespace}/users/{userId}/statitems
    *
    */
    AB_social_EXPORT static void admin_get_user_stat_items(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const user_statistic::AdminGetUserStatItems& request, 
        const std::function<void(const model::UserStatItems&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Bulk create user's statItems
    * @details Bulk create user&#39;s statItems.&lt;br&gt;Other detail info:&lt;ul&gt;&lt;li&gt;&lt;i&gt;Returns&lt;/i&gt;: bulk created result&lt;/li&gt;
    * @details /social/v1/admin/namespaces/{namespace}/users/{userId}/statitems/bulk
    *
    */
    AB_social_EXPORT static void admin_create_user_stat_items(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const user_statistic::AdminCreateUserStatItems& request, 
        const std::function<void(const accelbyte::Vector<model::StatOperations>&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Bulk update user's statitems value
    * @details Bulk update user&#39;s statitems value.&lt;br&gt;Other detail info:&lt;ul&gt;&lt;li&gt;&lt;i&gt;Returns&lt;/i&gt;: bulk updated result&lt;/li&gt;&lt;/ul&gt;
    * @details /social/v1/admin/namespaces/{namespace}/users/{userId}/statitems/value/bulk
    *
    */
    AB_social_EXPORT static void admin_update_user_stat_items_value(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const user_statistic::AdminUpdateUserStatItemsValue& request, 
        const std::function<void(const accelbyte::Vector<model::StatOperations>&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Bulk update user's statitems value
    * @details Bulk update user&#39;s statitems value.&lt;br&gt;Other detail info:&lt;ul&gt;&lt;li&gt;&lt;i&gt;Returns&lt;/i&gt;: bulk updated result&lt;/li&gt;&lt;/ul&gt;
    * @details /social/v1/admin/namespaces/{namespace}/users/{userId}/statitems/value/bulk
    *
    */
    AB_social_EXPORT static void admin_update_user_stat_item(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const user_statistic::AdminUpdateUserStatItem& request, 
        const std::function<void(const accelbyte::Vector<model::StatOperations>&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Bulk reset user's statitems value
    * @details Bulk reset user&#39;s statitems value for given namespace and user.  
Other detail info:
+ *Returns*: bulk updated result
    * @details /social/v1/admin/namespaces/{namespace}/users/{userId}/statitems/value/reset/bulk
    *
    */
    AB_social_EXPORT static void admin_reset_user_stat_items_value(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const user_statistic::AdminResetUserStatItemsValue& request, 
        const std::function<void(const accelbyte::Vector<model::StatOperations>&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Delete User's statItems
    * @details This endpoint is for testing purpose. Use this endpoint for cleaning up after testing.&lt;br&gt;Delete user&#39;s statItems given stat code.&lt;br&gt;Other detail info:&lt;ul&gt;&lt;li&gt;&lt;i&gt;Returns&lt;/i&gt;: no content&lt;/li&gt;&lt;/li&gt;
    * @details /social/v1/admin/namespaces/{namespace}/users/{userId}/stats/{statCode}/statitems
    *
    */
    AB_social_EXPORT static void admin_delete_user_stat_items(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const user_statistic::AdminDeleteUserStatItems& request, 
        const std::function<void()>& on_204,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Create user's statItem
    * @details Create statItem for a user.&lt;br&gt;Other detail info:&lt;ul&gt;&lt;li&gt;&lt;i&gt;Returns&lt;/i&gt;: created user&#39;s statItem&lt;/li&gt;&lt;/ul&gt;
    * @details /social/v1/admin/namespaces/{namespace}/users/{userId}/stats/{statCode}/statitems
    *
    */
    AB_social_EXPORT static void admin_create_user_stat_item(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const user_statistic::AdminCreateUserStatItem& request, 
        const std::function<void()>& on_201,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Update user's statitem value
    * @details Update user&#39;s statitem value.&lt;br&gt;Other detail info:&lt;ul&gt;&lt;li&gt;&lt;i&gt;Returns&lt;/i&gt;: updated user&#39;s statItem&lt;/li&gt;&lt;/ul&gt;
    * @details /social/v1/admin/namespaces/{namespace}/users/{userId}/stats/{statCode}/statitems/value
    *
    */
    AB_social_EXPORT static void admin_inc_user_stat_item_value(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const user_statistic::AdminIncUserStatItemValue& request, 
        const std::function<void(const model::StatItemInc&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Reset user's statitem value
    * @details Reset user&#39;s statitem value for a given namespace and user.
User&#39;s statitem value will be reset to the default value defined in the statistic configuration.

Other detail info:
+ *Returns*: updated user&#39;s statItem
    * @details /social/v1/admin/namespaces/{namespace}/users/{userId}/stats/{statCode}/statitems/value/reset
    *
    */
    AB_social_EXPORT static void admin_reset_user_stat_item_value(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const user_statistic::AdminResetUserStatItemValue& request, 
        const std::function<void(const model::StatItemInc&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Public bulk fetch statitems value
    * @details Public bulk fetch multiple user&#39;s statitem value for a given namespace and statCode.  
Other detail info:
+ *Returns*: list of user&#39;s statItem
    * @details /social/v1/public/namespaces/{namespace}/statitems/bulk
    *
    */
    AB_social_EXPORT static void get_stat_items(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const user_statistic::GetStatItems& request, 
        const std::function<void(const accelbyte::Vector<model::UserStatItem>&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Public bulk update multiple user's statitems value
    * @details Public bulk update multiple user&#39;s statitems value.&lt;br&gt;Other detail info:&lt;ul&gt;&lt;li&gt;&lt;i&gt;Returns&lt;/i&gt;: bulk updated result&lt;/li&gt;&lt;/ul&gt;
    * @details /social/v1/public/namespaces/{namespace}/statitems/value/bulk
    *
    */
    AB_social_EXPORT static void update_users_stat_items_value(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const user_statistic::UpdateUsersStatItemsValue& request, 
        const std::function<void(const accelbyte::Vector<model::StatOperations>&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Public bulk update multiple user's statitems value
    * @details Public bulk update multiple user&#39;s statitems value.&lt;br&gt;Other detail info:&lt;ul&gt;&lt;li&gt;&lt;i&gt;Returns&lt;/i&gt;: bulk updated result&lt;/li&gt;&lt;/ul&gt;
    * @details /social/v1/public/namespaces/{namespace}/statitems/value/bulk
    *
    */
    AB_social_EXPORT static void update_create_users_stat_items_value(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const user_statistic::UpdateCreateUsersStatItemsValue& request, 
        const std::function<void(const accelbyte::Vector<model::StatOperations>&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Public bulk reset multiple user's statitems value
    * @details Bulk reset multiple user&#39;s statitems value. 
User&#39;s statitem value will be reset to the default value defined in the statistic configuration.

Other detail info:
+ *Returns*: bulk updated result
    * @details /social/v1/public/namespaces/{namespace}/statitems/value/reset/bulk
    *
    */
    AB_social_EXPORT static void reset_users_stat_items(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const user_statistic::ResetUsersStatItems& request, 
        const std::function<void(const accelbyte::Vector<model::StatOperations>&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Public list user's statItems
    * @details Public list all statItems by pagination.&lt;br&gt;Other detail info:&lt;ul&gt;&lt;li&gt;&lt;i&gt;Returns&lt;/i&gt;: stat items&lt;/li&gt;&lt;/ul&gt;
    * @details /social/v1/public/namespaces/{namespace}/users/me/statitems
    *
    */
    AB_social_EXPORT static void get_my_stat_items(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const user_statistic::GetMyStatItems& request, 
        const std::function<void(const model::UserStatItems&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Public list user's statItems
    * @details Public list all statItems of user.&lt;br&gt;NOTE: &lt;li&gt;If stat code does not exist, will ignore this stat code.&lt;/li&gt;&lt;li&gt;If stat item does not exist, will return default value&lt;/li&gt;&lt;/ul&gt;Other detail info:&lt;ul&gt;&lt;li&gt;&lt;i&gt;Returns&lt;/i&gt;: stat items&lt;/li&gt;&lt;/ul&gt;
    * @details /social/v1/public/namespaces/{namespace}/users/me/statitems/value/bulk
    *
    */
    AB_social_EXPORT static void get_all_stat_items(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const user_statistic::GetAllStatItems& request, 
        const std::function<void(const accelbyte::Vector<model::UserStatItemValue>&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Public list user's statItems
    * @details Public list all statItems by pagination.&lt;br&gt;Other detail info:&lt;ul&gt;&lt;li&gt;&lt;i&gt;Returns&lt;/i&gt;: stat items&lt;/li&gt;&lt;/ul&gt;
    * @details /social/v1/public/namespaces/{namespace}/users/{userId}/statitems
    *
    */
    AB_social_EXPORT static void get_user_stat_item_value(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const user_statistic::GetUserStatItemValue& request, 
        const std::function<void(const model::UserStatItems&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Bulk create user's statItems
    * @details Bulk create statItems.&lt;br&gt;Other detail info:&lt;ul&gt;&lt;li&gt;&lt;i&gt;Returns&lt;/i&gt;: bulk created result&lt;/li&gt;&lt;/ul&gt;
    * @details /social/v1/public/namespaces/{namespace}/users/{userId}/statitems/bulk
    *
    */
    AB_social_EXPORT static void create_user_stat_items(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const user_statistic::CreateUserStatItems& request, 
        const std::function<void(const accelbyte::Vector<model::StatOperations>&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Public list user's statItems
    * @details Public list all statItems of user.&lt;br&gt;NOTE: &lt;li&gt;If stat code does not exist, will ignore this stat code.&lt;/li&gt;&lt;li&gt;If stat item does not exist, will return default value&lt;/li&gt;&lt;/ul&gt;Other detail info:&lt;ul&gt;&lt;li&gt;&lt;i&gt;Returns&lt;/i&gt;: stat items&lt;/li&gt;&lt;/ul&gt;
    * @details /social/v1/public/namespaces/{namespace}/users/{userId}/statitems/value/bulk
    *
    */
    AB_social_EXPORT static void get_user_stat_items_value(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const user_statistic::GetUserStatItemsValue& request, 
        const std::function<void(const accelbyte::Vector<model::UserStatItemValue>&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Public bulk update user's statitems value
    * @details Public bulk update user&#39;s statitems value.&lt;br&gt;Other detail info:&lt;ul&gt;&lt;li&gt;&lt;i&gt;Returns&lt;/i&gt;: bulk updated result&lt;/li&gt;
    * @details /social/v1/public/namespaces/{namespace}/users/{userId}/statitems/value/bulk
    *
    */
    AB_social_EXPORT static void update_user_stat_items_value(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const user_statistic::UpdateUserStatItemsValue& request, 
        const std::function<void(const accelbyte::Vector<model::StatOperations>&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Public bulk update user's statitems value
    * @details Public bulk update user&#39;s statitems value.&lt;br&gt;Other detail info:&lt;ul&gt;&lt;li&gt;&lt;i&gt;Returns&lt;/i&gt;: bulk updated result&lt;/li&gt;&lt;/ul&gt;
    * @details /social/v1/public/namespaces/{namespace}/users/{userId}/statitems/value/bulk
    *
    */
    AB_social_EXPORT static void update_create_user_stat_items_value(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const user_statistic::UpdateCreateUserStatItemsValue& request, 
        const std::function<void(const accelbyte::Vector<model::StatOperations>&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Public bulk reset user's statitems value
    * @details Public bulk reset user&#39;s statitems value for given namespace and user.  
Other detail info:
+ *Returns*: bulk updated result
    * @details /social/v1/public/namespaces/{namespace}/users/{userId}/statitems/value/reset/bulk
    *
    */
    AB_social_EXPORT static void reset_user_stat_items_value(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const user_statistic::ResetUserStatItemsValue& request, 
        const std::function<void(const accelbyte::Vector<model::StatOperations>&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Delete User's statItems
    * @details Delete user&#39;s statItems given stat code.&lt;br&gt;Other detail info:&lt;ul&gt;&lt;li&gt;&lt;i&gt;Returns&lt;/i&gt;: no content&lt;/li&gt;&lt;/li&gt;
    * @details /social/v1/public/namespaces/{namespace}/users/{userId}/stats/{statCode}/statitems
    *
    */
    AB_social_EXPORT static void delete_user_stat_items(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const user_statistic::DeleteUserStatItems& request, 
        const std::function<void()>& on_204,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Create user's statItem
    * @details Create user&#39;s statItem.&lt;br&gt;Other detail info:&lt;ul&gt;&lt;li&gt;&lt;i&gt;Returns&lt;/i&gt;: created user&#39;s statItem&lt;/li&gt;&lt;/ul&gt;
    * @details /social/v1/public/namespaces/{namespace}/users/{userId}/stats/{statCode}/statitems
    *
    */
    AB_social_EXPORT static void create_user_stat_item(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const user_statistic::CreateUserStatItem& request, 
        const std::function<void()>& on_201,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Public update user's statitem value
    * @details Public update user&#39;s statitem value.&lt;br&gt;Other detail info:&lt;ul&gt;&lt;li&gt;&lt;i&gt;Returns&lt;/i&gt;: updated user&#39;s statItem&lt;/li&gt;&lt;/ul&gt;
    * @details /social/v1/public/namespaces/{namespace}/users/{userId}/stats/{statCode}/statitems/value
    *
    */
    AB_social_EXPORT static void update_user_stat_item(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const user_statistic::UpdateUserStatItem& request, 
        const std::function<void(const model::StatItemInc&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Public update user's statitem value
    * @details Public update user&#39;s statitem value.&lt;br&gt;Other detail info:&lt;ul&gt;&lt;li&gt;&lt;i&gt;Returns&lt;/i&gt;: updated user&#39;s statItem&lt;/li&gt;&lt;/ul&gt;
    * @details /social/v1/public/namespaces/{namespace}/users/{userId}/stats/{statCode}/statitems/value
    *
    */
    AB_social_EXPORT static void update_create_user_stat_item(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const user_statistic::UpdateCreateUserStatItem& request, 
        const std::function<void(const model::StatItemInc&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Public reset user's statitem value
    * @details Reset user&#39;s statitem value for a given namespace and user.
User&#39;s statitem value will be reset to the default value defined in the statistic configuration.

Other detail info:
+ *Returns*: updated user&#39;s statItem
    * @details /social/v1/public/namespaces/{namespace}/users/{userId}/stats/{statCode}/statitems/value/reset
    *
    */
    AB_social_EXPORT static void reset_user_stat_item_value(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const user_statistic::ResetUserStatItemValue& request, 
        const std::function<void(const model::StatItemInc&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Bulk update multiple user's statitems value
    * @details Bulk update multiple user&#39;s statitems value with specific update strategy.  
There are four supported update strategies:
+ *OVERRIDE*: update user statitem with the new value
+ *INCREMENT*: increment user statitem with the specified value
+ *MAX*: update user statitem with the specified value if it&#39;s larger than the existing value
+ *MIN*: update user statitem with the specified value if it&#39;s lower than the existing value

Other detail info:
+ *Returns*: bulk updated result
    * @details /social/v2/admin/namespaces/{namespace}/statitems/value/bulk
    *
    */
    AB_social_EXPORT static void admin_update_users_stat_items_v2(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const user_statistic::AdminUpdateUsersStatItemsV2& request, 
        const std::function<void(const accelbyte::Vector<model::StatOperations>&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Bulk fetch user stat item values
    * @details Bulk fetch multiple user&#39;s stat item values for a given namespace and statCode.
NOTE: If stat item does not exist, will return default value. Other detail info:
+ *Returns*: list of user&#39;s stat item values
    * @details /social/v2/admin/namespaces/{namespace}/statitems/value/bulk/getOrDefault
    *
    */
    AB_social_EXPORT static void admin_default_get_stat_items_v2(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const user_statistic::AdminDefaultGetStatItemsV2& request, 
        const std::function<void(const accelbyte::Vector<model::UserStatItemValue>&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief (Legacy) Admin list user's statItems
    * @details Admin list all statItems of user&lt;br&gt;NOTE: &lt;b&gt;Legacy endpoint&lt;/b&gt;, please use POST /v2/admin/namespaces/{namespace}/users/{userId}/statitems/value/bulk/getOrDefault&lt;ul&gt;&lt;li&gt;If stat code does not exist, will ignore this stat code.&lt;/li&gt;&lt;li&gt;If stat item does not exist, will return default value&lt;/li&gt;&lt;/ul&gt;Other detail info:&lt;ul&gt;&lt;li&gt;&lt;i&gt;Returns&lt;/i&gt;: stat items&lt;/li&gt;&lt;/ul&gt;
    * @details /social/v2/admin/namespaces/{namespace}/users/{userId}/statitems/value/bulk
    *
    */
    AB_social_EXPORT static void admin_get_users_stat_items(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const user_statistic::AdminGetUsersStatItems& request, 
        const std::function<void(const accelbyte::Vector<model::UserStatItemValue>&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Bulk update user's statitems value
    * @details Bulk update user&#39;s statitems value for given namespace and user with specific update strategy.  
There are four supported update strategies:
+ *OVERRIDE*: update user statitem with the new value
+ *INCREMENT*: increment user statitem with the specified value
+ *MAX*: update user statitem with the specified value if it&#39;s larger than the existing value
+ *MIN*: update user statitem with the specified value if it&#39;s lower than the existing value

The *additionalKey* parameter will be suffixed to *userId* and is used to support multi level user&#39;s statitems, such as character&#39;s statitems. 
If provided, user&#39;s statitems will be saved with key: *userId_additionalKey* 

Other detail info:
+ *Returns*: bulk updated result
    * @details /social/v2/admin/namespaces/{namespace}/users/{userId}/statitems/value/bulk
    *
    */
    AB_social_EXPORT static void admin_update_users_stat_items_value_v2(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const user_statistic::AdminUpdateUsersStatItemsValueV2& request, 
        const std::function<void(const accelbyte::Vector<model::StatOperations>&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Bulk get user's statitems value by user id and multiple stat codes
    * @details Bulk get user&#39;s statitems value for given namespace and user by multiple stat codes.  
Will return default value if player doesn&#39;t have the stat. 
Other detail info:
+ *Required permission*: resource=&#34;ADMIN:NAMESPACE:{namespace}:USER:{userId}:STATITEM&#34;, action=2 (READ)
+ *Max stat codes*: 20
+ *Returns*: list of user&#39;s stat item values
    * @details /social/v2/admin/namespaces/{namespace}/users/{userId}/statitems/value/bulk/getOrDefault
    *
    */
    AB_social_EXPORT static void admin_get_stat_items_by_user_ids(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const user_statistic::AdminGetStatItemsByUserIds& request, 
        const std::function<void(const accelbyte::Vector<model::UserStatItemValue>&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Bulk reset user's statitem values
    * @details Bulk reset user&#39;s statitem values for given namespace and user.  
Other detail info:
+ *Returns*: bulk updated result
    * @details /social/v2/admin/namespaces/{namespace}/users/{userId}/statitems/value/reset/bulk
    *
    */
    AB_social_EXPORT static void admin_reset_user_stat_items_value_v2(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const user_statistic::AdminResetUserStatItemsValueV2& request, 
        const std::function<void(const accelbyte::Vector<model::StatOperations>&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Delete User's statItems
    * @details Delete user&#39;s stat items for given namespace, statCode, and user Id. 
If query param *additionalKey* is provided, it will delete user stat items of specific key (i.e. characterName). 
Otherwise, it will delete all stat items related to the user Id. 
&lt;br&gt;Delete user&#39;s statItems given stat code.&lt;br&gt;Other detail info:&lt;ul&gt;&lt;li&gt;&lt;i&gt;Returns&lt;/i&gt;: no content&lt;/li&gt;&lt;/li&gt;
    * @details /social/v2/admin/namespaces/{namespace}/users/{userId}/stats/{statCode}/statitems
    *
    */
    AB_social_EXPORT static void admin_delete_user_stat_items_v2(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const user_statistic::AdminDeleteUserStatItemsV2& request, 
        const std::function<void()>& on_204,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Update user's statitem value
    * @details Update user&#39;s statitem value for a given namespace and user with a certain update strategy.
There are four supported update strategies:
+ *OVERRIDE*: update user statitem with the new value
+ *INCREMENT*: increment user statitem with the specified value
+ *MAX*: update user statitem with the specified value if it&#39;s larger than the existing value
+ *MIN*: update user statitem with the specified value if it&#39;s lower than the existing value

The *additionalKey* parameter will be suffixed to *userId* and is used to support multi level user&#39;s statitems, such as character&#39;s statitems. 
If provided, user&#39;s statitems will be saved with key: *userId_additionalKey* 

Other detail info:
+ *Returns*: updated user&#39;s statItem
    * @details /social/v2/admin/namespaces/{namespace}/users/{userId}/stats/{statCode}/statitems/value
    *
    */
    AB_social_EXPORT static void admin_update_user_stat_item_value_v2(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const user_statistic::AdminUpdateUserStatItemValueV2& request, 
        const std::function<void(const model::StatItemInc&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Public bulk update multiple user's statitems value
    * @details Public bulk update multiple user&#39;s statitems value with specific update strategy.  
There are four supported update strategies:
+ *OVERRIDE*: update user statitem with the new value
+ *INCREMENT*: increment user statitem with the specified value
+ *MAX*: update user statitem with the specified value if it&#39;s larger than the existing value
+ *MIN*: update user statitem with the specified value if it&#39;s lower than the existing value

Other detail info:
+ *Returns*: bulk updated result
    * @details /social/v2/public/namespaces/{namespace}/statitems/value/bulk
    *
    */
    AB_social_EXPORT static void update_users_stat_items_v2(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const user_statistic::UpdateUsersStatItemsV2& request, 
        const std::function<void(const accelbyte::Vector<model::StatOperations>&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Public list user's statItems
    * @details Public list all statItems of user.&lt;br&gt;NOTE: &lt;li&gt;If stat code does not exist, will ignore this stat code.&lt;/li&gt;&lt;li&gt;If stat item does not exist, will return default value&lt;/li&gt;&lt;/ul&gt;Other detail info:&lt;ul&gt;&lt;li&gt;&lt;i&gt;Returns&lt;/i&gt;: stat items&lt;/li&gt;&lt;/ul&gt;
    * @details /social/v2/public/namespaces/{namespace}/users/{userId}/statitems/value/bulk
    *
    */
    AB_social_EXPORT static void get_user_stat_items_value_v2(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const user_statistic::GetUserStatItemsValueV2& request, 
        const std::function<void(const accelbyte::Vector<model::UserStatItemValue>&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Public bulk update user's statitems value
    * @details Public bulk update user&#39;s statitems value for given namespace and user with specific update strategy.  
There are four supported update strategies:
+ *OVERRIDE*: update user statitem with the new value
+ *INCREMENT*: increment user statitem with the specified value
+ *MAX*: update user statitem with the specified value if it&#39;s larger than the existing value
+ *MIN*: update user statitem with the specified value if it&#39;s lower than the existing value

The *additionalKey* parameter will be suffixed to *userId* and is used to support multi level user&#39;s statitems, such as character&#39;s statitems. 
If provided, user&#39;s statitems will be saved with key: *userId_additionalKey* 

Other detail info:
+ *Returns*: bulk updated result
    * @details /social/v2/public/namespaces/{namespace}/users/{userId}/statitems/value/bulk
    *
    */
    AB_social_EXPORT static void update_users_stat_items_value_v2(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const user_statistic::UpdateUsersStatItemsValueV2& request, 
        const std::function<void(const accelbyte::Vector<model::StatOperations>&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Public update user's statitem value
    * @details Public update user&#39;s statitem value for a given namespace and user with a certain update strategy. 
There are four supported update strategies:
+ *OVERRIDE*: update user statitem with the new value
+ *INCREMENT*: increment user statitem with the specified value
+ *MAX*: update user statitem with the specified value if it&#39;s larger than the existing value
+ *MIN*: update user statitem with the specified value if it&#39;s lower than the existing value

The *additionalKey* parameter will be suffixed to *userId* and is used to support multi level user&#39;s statitems, such as character&#39;s statitems. 
If provided, user&#39;s statitems will be saved with key: *userId_additionalKey* 

Other detail info:
+ *Returns*: updated user&#39;s statItem
    * @details /social/v2/public/namespaces/{namespace}/users/{userId}/stats/{statCode}/statitems/value
    *
    */
    AB_social_EXPORT static void update_user_stat_item_value_v2(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const user_statistic::UpdateUserStatItemValueV2& request, 
        const std::function<void(const model::StatItemInc&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

};

}
}