// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/http/SendableObject.h"
#include "accelbyte/common/DateTime.h"
#include "accelbyte/utils/JsonObjectString.h"
#include "accelbyte/common/Optional.h"
#include "accelbyte/social/social_export.h"

#include "accelbyte/common/String.h"
#include "accelbyte/common/Map.h"
#include "accelbyte/common/Vector.h"


namespace accelbyte {
namespace social {
namespace slot {

/**
* @brief &lt;h2&gt;The endpoint is going to be deprecated&lt;/h2&gt;&lt;br&gt;Updates a slot.&lt;br&gt;Other detail info:&lt;ul&gt;&lt;li&gt;&lt;i&gt;Returns&lt;/i&gt;: updated slot&lt;/li&gt;&lt;/ul&gt;
*/
class UpdateUserNamespaceSlot : public accelbyte::http::SendableObject
{
public:
    
    
    /**
    * @brief default constructor.
    **/
	AB_social_EXPORT UpdateUserNamespaceSlot() = default;
	
    /**
    * @brief destrutor.
    **/
    AB_social_EXPORT virtual ~UpdateUserNamespaceSlot() = default;
	
	/**
    * @brief Return the object unique id (used for serialization)
    **/
    AB_social_EXPORT const String& sendable_id() const override;
	
	/**
    * @brief Return the unique id that can be used to determine this class (used for serialization)
    **/
    AB_social_EXPORT static const String& sendable_object_id();
	
    // usefull parameters    
     /**
     * @brief Namespace ID
if not set the user namespace will be used.
    **/
    accelbyte::Optional<accelbyte::String> ab_namespace{};
     /**
     * @brief Slot ID
    **/
    accelbyte::String slot_id{};
     /**
     * @brief User ID
    **/
    accelbyte::String user_id{};
     /**
     * @brief File checksum
    **/
    accelbyte::Optional<accelbyte::String> checksum{};
     /**
     * @brief Custom attribute
    **/
    accelbyte::Optional<accelbyte::String> custom_attribute{};
     /**
     * @brief None
    **/
    accelbyte::Optional<accelbyte::String> file{};
     /**
     * @brief Label
    **/
    accelbyte::Optional<accelbyte::String> label{};
     /**
     * @brief Tags
    **/
    accelbyte::Optional<accelbyte::Vector<accelbyte::String>> tags{};
};

}
}
}