// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/http/SendableObject.h"
#include "accelbyte/common/DateTime.h"
#include "accelbyte/utils/JsonObjectString.h"
#include "accelbyte/common/Optional.h"
#include "accelbyte/reporting/reporting_export.h"

#include "accelbyte/common/String.h"
#include "accelbyte/common/Map.h"
#include "accelbyte/common/Vector.h"


namespace accelbyte {
namespace reporting {
namespace admin_moderation_rule {

/**
* @brief This endpoint delete moderation rule.
*/
class AdminDeleteModerationRule : public accelbyte::http::SendableObject
{
public:
    
    
    /**
    * @brief default constructor.
    **/
	AB_reporting_EXPORT AdminDeleteModerationRule() = default;
	
    /**
    * @brief destrutor.
    **/
    AB_reporting_EXPORT virtual ~AdminDeleteModerationRule() = default;
	
	/**
    * @brief Return the object unique id (used for serialization)
    **/
    AB_reporting_EXPORT const String& sendable_id() const override;
	
	/**
    * @brief Return the unique id that can be used to determine this class (used for serialization)
    **/
    AB_reporting_EXPORT static const String& sendable_object_id();
	
    // usefull parameters    
     /**
     * @brief None
if not set the user namespace will be used.
    **/
    accelbyte::Optional<accelbyte::String> ab_namespace{};
     /**
     * @brief None
    **/
    accelbyte::String rule_id{};
};

}
}
}