// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/http/SendableObject.h"
#include "accelbyte/common/DateTime.h"
#include "accelbyte/utils/JsonObjectString.h"
#include "accelbyte/common/Optional.h"
#include "accelbyte/ugc/ugc_export.h"

#include "accelbyte/common/String.h"
#include "accelbyte/common/Map.h"
#include "accelbyte/common/Vector.h"

#include "accelbyte/ugc/models/UpdateContentShareCodeRequest.h"

namespace accelbyte {
namespace ugc {
namespace public_content_v2 {

/**
* @brief This endpoint is used to modify the shareCode of a content. However, this operation is restricted by default and requires the above permission to be granted to the User role.&lt;br&gt;
								&lt;code&gt;shareCode&lt;/code&gt; format should follows:
								Max length: 7
								Available characters: abcdefhkpqrstuxyz
*/
class UpdateContentShareCodeV2 : public accelbyte::http::SendableObject
{
public:
    
    
    /**
    * @brief default constructor.
    **/
	AB_ugc_EXPORT UpdateContentShareCodeV2() = default;
	
    /**
    * @brief destrutor.
    **/
    AB_ugc_EXPORT virtual ~UpdateContentShareCodeV2() = default;
	
	/**
    * @brief Return the object unique id (used for serialization)
    **/
    AB_ugc_EXPORT const String& sendable_id() const override;
	
	/**
    * @brief Return the unique id that can be used to determine this class (used for serialization)
    **/
    AB_ugc_EXPORT static const String& sendable_object_id();
	
    // usefull parameters    
     /**
     * @brief None
    **/
    model::UpdateContentShareCodeRequest body{};
     /**
     * @brief channel ID
    **/
    accelbyte::String channel_id{};
     /**
     * @brief content ID
    **/
    accelbyte::String content_id{};
     /**
     * @brief namespace of the game
if not set the user namespace will be used.
    **/
    accelbyte::Optional<accelbyte::String> ab_namespace{};
     /**
     * @brief user ID
    **/
    accelbyte::String user_id{};
};

}
}
}