// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/http/ModelObject.h"
#include "accelbyte/common/Optional.h"
#include "accelbyte/common/String.h"
#include "accelbyte/common/Map.h"
#include "accelbyte/common/Vector.h"
#include "accelbyte/common/DateTime.h"
#include "accelbyte/memory/memory.h"
#include "accelbyte/utils/JsonObjectString.h"
#include "accelbyte/platform/platform_export.h"


namespace accelbyte {
namespace platform {
namespace model {

class PaymentData : public accelbyte::http::ModelObject
{
public:
    /**
    * @brief default constructor.
    **/
	AB_platform_EXPORT  PaymentData() = default;
	
    /**
    * @brief destructor.
    **/
    AB_platform_EXPORT virtual ~PaymentData() = default;
	
	/**
    * @brief Return the object unique id (used for serialization)
    **/
    AB_platform_EXPORT virtual const String& model_id() const override;
	
	/**
    * @brief Return the unique id that can be used to determine this class (used for serialization)
    **/
    AB_platform_EXPORT static const String& model_object_id();
    
    // start of usefull parameters
	accelbyte::Optional<int> discount_amount{};
	accelbyte::Optional<accelbyte::String> discount_code{};
	accelbyte::Optional<int> subtotal_price{};
	accelbyte::Optional<int> tax{};
	accelbyte::Optional<int> total_price{};
};

}
}
}