// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/http/ModelObject.h"
#include "accelbyte/common/Optional.h"
#include "accelbyte/common/String.h"
#include "accelbyte/common/Map.h"
#include "accelbyte/common/Vector.h"
#include "accelbyte/common/DateTime.h"
#include "accelbyte/memory/memory.h"
#include "accelbyte/utils/JsonObjectString.h"
#include "accelbyte/platform/platform_export.h"

#include "accelbyte/platform/models/ImportStoreError.h"

namespace accelbyte {
namespace platform {
namespace model {

class ImportStoreHistoryInfo : public accelbyte::http::ModelObject
{
public:
    enum class ImportFileFormat : uint32_t {
        UNKNOWN,
        CSV,
        JSON
    };
    /**
    * @brief default constructor.
    **/
	AB_platform_EXPORT  ImportStoreHistoryInfo() = default;
	
    /**
    * @brief destructor.
    **/
    AB_platform_EXPORT virtual ~ImportStoreHistoryInfo() = default;
	
	/**
    * @brief Return the object unique id (used for serialization)
    **/
    AB_platform_EXPORT virtual const String& model_id() const override;
	
	/**
    * @brief Return the unique id that can be used to determine this class (used for serialization)
    **/
    AB_platform_EXPORT static const String& model_object_id();
    
    // start of usefull parameters
	accelbyte::DateTime created_at{};
	accelbyte::Optional<accelbyte::Vector<ImportStoreError>> errors{};
	accelbyte::String id{};
	ImportFileFormat import_file_format{};
	accelbyte::String initiated_by{};
	accelbyte::String ab_namespace{};
	accelbyte::Optional<accelbyte::String> note{};
	accelbyte::String store_id{};
	bool success{false};
};

}
}
}