// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/http/SendableObject.h"
#include "accelbyte/common/DateTime.h"
#include "accelbyte/utils/JsonObjectString.h"
#include "accelbyte/common/Optional.h"
#include "accelbyte/platform/platform_export.h"

#include "accelbyte/common/String.h"
#include "accelbyte/common/Map.h"
#include "accelbyte/common/Vector.h"

#include "accelbyte/platform/models/UpdatePlatformDLCConfig.h"

namespace accelbyte {
namespace platform {
namespace dlc {

/**
* @brief Update Platform DLC config. Other detail info: &lt;ul&gt;&lt;li&gt;&lt;i&gt;Returns&lt;/i&gt;: updated Platform DLC config&lt;/li&gt;&lt;/ul&gt;&lt;h2&gt;Restrictions for platform dlc map&lt;/h2&gt;
1. Cannot use &lt;b&gt;&#34;.&#34;&lt;/b&gt; as the key name
-	&lt;pre&gt;{ &#34;data.2&#34;: &#34;value&#34; }&lt;/pre&gt;
2. Cannot use &lt;b&gt;&#34;$&#34;&lt;/b&gt; as the prefix in key names
-	&lt;pre&gt;{ &#34;$data&#34;: &#34;value&#34; }&lt;/pre&gt;
*/
class AdminUpdatePlatformDLCConfig : public accelbyte::http::SendableObject
{
public:
    
    
    /**
    * @brief default constructor.
    **/
	AB_platform_EXPORT AdminUpdatePlatformDLCConfig() = default;
	
    /**
    * @brief destrutor.
    **/
    AB_platform_EXPORT virtual ~AdminUpdatePlatformDLCConfig() = default;
	
	/**
    * @brief Return the object unique id (used for serialization)
    **/
    AB_platform_EXPORT const String& sendable_id() const override;
	
	/**
    * @brief Return the unique id that can be used to determine this class (used for serialization)
    **/
    AB_platform_EXPORT static const String& sendable_object_id();
	
    // usefull parameters    
     /**
     * @brief None
    **/
    model::UpdatePlatformDLCConfig body{};
     /**
     * @brief None
if not set the user namespace will be used.
    **/
    accelbyte::Optional<accelbyte::String> ab_namespace{};
};

}
}
}