// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/http/SendableObject.h"
#include "accelbyte/common/DateTime.h"
#include "accelbyte/utils/JsonObjectString.h"
#include "accelbyte/common/Optional.h"
#include "accelbyte/challenge/challenge_export.h"

#include "accelbyte/common/String.h"
#include "accelbyte/common/Map.h"
#include "accelbyte/common/Vector.h"

#include "accelbyte/challenge/models/PluginAssignmentRequest.h"

namespace accelbyte {
namespace challenge {
namespace plugins {

/**
* @brief &lt;ul&gt;&lt;li&gt;Required permission: ADMIN:NAMESPACE:{namespace}:CHALLENGE:PLUGIN [CREATE]&lt;/li&gt;&lt;/ul&gt;
*/
class AdminCreateAssignmentPlugin : public accelbyte::http::SendableObject
{
public:
    
    
    /**
    * @brief default constructor.
    **/
	AB_challenge_EXPORT AdminCreateAssignmentPlugin() = default;
	
    /**
    * @brief destrutor.
    **/
    AB_challenge_EXPORT virtual ~AdminCreateAssignmentPlugin() = default;
	
	/**
    * @brief Return the object unique id (used for serialization)
    **/
    AB_challenge_EXPORT const String& sendable_id() const override;
	
	/**
    * @brief Return the unique id that can be used to determine this class (used for serialization)
    **/
    AB_challenge_EXPORT static const String& sendable_object_id();
	
    // usefull parameters    
     /**
     * @brief None
    **/
    model::PluginAssignmentRequest body{};
     /**
     * @brief namespace of the game
if not set the user namespace will be used.
    **/
    accelbyte::Optional<accelbyte::String> ab_namespace{};
};

}
}
}