// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/http/SendableObject.h"
#include "accelbyte/common/DateTime.h"
#include "accelbyte/utils/JsonObjectString.h"
#include "accelbyte/common/Optional.h"
#include "accelbyte/login_queue/login_queue_export.h"

#include "accelbyte/common/String.h"
#include "accelbyte/common/Map.h"
#include "accelbyte/common/Vector.h"


namespace accelbyte {
namespace login_queue {
namespace admin_v1 {

/**
* @brief This API is used to get log queue configuration of a namespace.
Calling this endpoint with namespace which has not set up configuration will return a valid configuration with default value
*/
class AdminGetConfiguration : public accelbyte::http::SendableObject
{
public:
    
    
    /**
    * @brief default constructor.
    **/
	AB_login_queue_EXPORT AdminGetConfiguration() = default;
	
    /**
    * @brief destrutor.
    **/
    AB_login_queue_EXPORT virtual ~AdminGetConfiguration() = default;
	
	/**
    * @brief Return the object unique id (used for serialization)
    **/
    AB_login_queue_EXPORT const String& sendable_id() const override;
	
	/**
    * @brief Return the unique id that can be used to determine this class (used for serialization)
    **/
    AB_login_queue_EXPORT static const String& sendable_object_id();
	
    // usefull parameters    
     /**
     * @brief namespace of the game
if not set the user namespace will be used.
    **/
    accelbyte::Optional<accelbyte::String> ab_namespace{};
};

}
}
}