// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/http/SendableObject.h"
#include "accelbyte/common/DateTime.h"
#include "accelbyte/utils/JsonObjectString.h"
#include "accelbyte/common/Optional.h"
#include "accelbyte/group/group_export.h"

#include "accelbyte/common/String.h"
#include "accelbyte/common/Map.h"
#include "accelbyte/common/Vector.h"


namespace accelbyte {
namespace group {
namespace configuration {

/**
* @brief This endpoint is used to initiate configuration.  
This endpoint will automatically create default configuration and member roles with default permission  
Default Permission for admin role will cover these permission:  
- Permission to invite user to group
- Permission to accept or reject join request
- Permission to kick group member  

Default max member value will be 50 and global rules will be empty  
Action Code: 73104
*/
class AdminInitiateGroupConfigV1 : public accelbyte::http::SendableObject
{
public:
    
    
    /**
    * @brief default constructor.
    **/
	AB_group_EXPORT AdminInitiateGroupConfigV1() = default;
	
    /**
    * @brief destrutor.
    **/
    AB_group_EXPORT virtual ~AdminInitiateGroupConfigV1() = default;
	
	/**
    * @brief Return the object unique id (used for serialization)
    **/
    AB_group_EXPORT const String& sendable_id() const override;
	
	/**
    * @brief Return the unique id that can be used to determine this class (used for serialization)
    **/
    AB_group_EXPORT static const String& sendable_object_id();
	
    // usefull parameters    
     /**
     * @brief namespace
if not set the user namespace will be used.
    **/
    accelbyte::Optional<accelbyte::String> ab_namespace{};
};

}
}
}