// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/inventory/inventory_export.h"
#include "accelbyte/inventory/admin_integration_configurations/AdminGetIntegrationConfigs.h"
#include "accelbyte/inventory/admin_integration_configurations/AdminCreateIntegrationConfig.h"
#include "accelbyte/inventory/admin_integration_configurations/AdminUpdateIntegrationConfig.h"
#include "accelbyte/inventory/admin_integration_configurations/d6e9168dabeb1b0tegrationConfig.h"
#include "accelbyte/inventory/models/AdminUpdateItemRequest.h"
#include "accelbyte/inventory/models/SaveItemsError.h"
#include "accelbyte/inventory/models/SaveItems.h"
#include "accelbyte/inventory/models/ChainingOperationRequest.h"
#include "accelbyte/inventory/models/ChainingOperation.h"
#include "accelbyte/inventory/models/ConsumeItem.h"
#include "accelbyte/inventory/models/ConsumeItemRequest.h"
#include "accelbyte/inventory/models/CreateIntegrationConfigRequest.h"
#include "accelbyte/inventory/models/CreateInventoryConfigRequest.h"
#include "accelbyte/inventory/models/CreateInventoryRequest.h"
#include "accelbyte/inventory/models/CreateItem.h"
#include "accelbyte/inventory/models/CreateItemTypeRequest.h"
#include "accelbyte/inventory/models/Type.h"
#include "accelbyte/inventory/models/CreateTagRequest.h"
#include "accelbyte/inventory/models/Tag.h"
#include "accelbyte/inventory/models/DeleteInventoryRequest.h"
#include "accelbyte/inventory/models/Error.h"
#include "accelbyte/inventory/models/IntegrationConfig.h"
#include "accelbyte/inventory/models/InventoryConfig.h"
#include "accelbyte/inventory/models/InventoryConfigRequest.h"
#include "accelbyte/inventory/models/Configuration.h"
#include "accelbyte/inventory/models/Inventory.h"
#include "accelbyte/inventory/models/Item.h"
#include "accelbyte/inventory/models/ListConfigurations.h"
#include "accelbyte/inventory/models/ListInventories.h"
#include "accelbyte/inventory/models/GetInventoriesResponse.h"
#include "accelbyte/inventory/models/ListItems.h"
#include "accelbyte/inventory/models/ListTypes.h"
#include "accelbyte/inventory/models/ListTags.h"
#include "accelbyte/inventory/models/MoveItemsRequest.h"
#include "accelbyte/inventory/models/MovedItems.h"
#include "accelbyte/inventory/models/Operation.h"
#include "accelbyte/inventory/models/Pagination.h"
#include "accelbyte/inventory/models/PurchaseValidationItemRequest.h"
#include "accelbyte/inventory/models/PurchaseValidationRequest.h"
#include "accelbyte/inventory/models/RemoveInventoryItemRequest.h"
#include "accelbyte/inventory/models/RemovedItems.h"
#include "accelbyte/inventory/models/SaveItemRequest.h"
#include "accelbyte/inventory/models/SaveItemInventoryRequest.h"
#include "accelbyte/inventory/models/TradeItem.h"
#include "accelbyte/inventory/models/MovedItem.h"
#include "accelbyte/inventory/models/UpdateIntegrationConfigRequest.h"
#include "accelbyte/inventory/models/UpdateInventoryRequest.h"
#include "accelbyte/inventory/models/UpdateItem.h"
#include "accelbyte/inventory/models/UpdateItemRequest.h"
#include "accelbyte/inventory/models/UpdatedItem.h"
#include "accelbyte/inventory/models/f453a8b0e607a5conConfigRequest.h"
#include "accelbyte/common/Error.h"
#include "accelbyte/tls/SecurityAuthorization.h"

#include <functional>
#include "accelbyte/memory/memory.h"

namespace accelbyte {
namespace inventory {

class AdminIntegrationConfigurations
{
public:	
    /**
    * @brief To list integration configurations
    * @details 
			Listing all integration configurations in a namespace.
			The response body will be in the form of standard pagination.

			Permission: ADMIN:NAMESPACE:{namespace}:INVENTORY:INTEGRATIONCONFIGURATION [READ]
		
    * @details /inventory/v1/admin/namespaces/{namespace}/integrationConfigurations
    *
    */
    AB_inventory_EXPORT static void admin_get_integration_configs(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const admin_integration_configurations::AdminGetIntegrationConfigs& request, 
        const std::function<void(const model::ListConfigurations&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief To create integration configuration
    * @details 
			Creating integration configuration.
			There cannot be one duplicate serviceName per namespace.

			Permission: ADMIN:NAMESPACE:{namespace}:INVENTORY:INTEGRATIONCONFIGURATION [CREATE]
		
    * @details /inventory/v1/admin/namespaces/{namespace}/integrationConfigurations
    *
    */
    AB_inventory_EXPORT static void admin_create_integration_config(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const admin_integration_configurations::AdminCreateIntegrationConfig& request, 
        const std::function<void(const model::IntegrationConfig&)>& on_201,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief To update integration configuration
    * @details 
			to update integration configuration
			There cannot be duplicate serviceName per namespace.
			
			Permission: ADMIN:NAMESPACE:{namespace}:INVENTORY:INTEGRATIONCONFIGURATION [UPDATE]
		
    * @details /inventory/v1/admin/namespaces/{namespace}/integrationConfigurations/{integrationConfigurationId}
    *
    */
    AB_inventory_EXPORT static void admin_update_integration_config(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const admin_integration_configurations::AdminUpdateIntegrationConfig& request, 
        const std::function<void(const model::IntegrationConfig&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief To update status integration configuration to be active / not active 
    * @details 
			to update status  integration configuration to be Active / Not Active.
			There cannot be duplicate serviceName per namespace.
			
			Permission: ADMIN:NAMESPACE:{namespace}:INVENTORY:INTEGRATIONCONFIGURATION [UPDATE]
		
    * @details /inventory/v1/admin/namespaces/{namespace}/integrationConfigurations/{integrationConfigurationId}/status
    *
    */
    AB_inventory_EXPORT static void admin_update_status_integration_config(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const admin_integration_configurations::AdminUpdateStatusIntegrationConfig& request, 
        const std::function<void(const model::IntegrationConfig&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

};

}
}