// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/http/SendableObject.h"
#include "accelbyte/common/DateTime.h"
#include "accelbyte/utils/JsonObjectString.h"
#include "accelbyte/common/Optional.h"
#include "accelbyte/group/group_export.h"

#include "accelbyte/common/String.h"
#include "accelbyte/common/Map.h"
#include "accelbyte/common/Vector.h"


namespace accelbyte {
namespace group {
namespace group_member {

/**
* @brief Required valid user authentication

This endpoint is used to get user group information.

Get user group information. If user does not belong to any group, it will return warning to give information about it

Group Member Status:

*   JOIN : status of user requested to join group
*   INVITE: status of user invited to a group
*   JOINED: status of user already joined to a group

Action Code: 73405
		
*/
class GetGroupInfoV1 : public accelbyte::http::SendableObject
{
public:
    
    
    /**
    * @brief default constructor.
    **/
	AB_group_EXPORT GetGroupInfoV1() = default;
	
    /**
    * @brief destrutor.
    **/
    AB_group_EXPORT virtual ~GetGroupInfoV1() = default;
	
	/**
    * @brief Return the object unique id (used for serialization)
    **/
    AB_group_EXPORT const String& sendable_id() const override;
	
	/**
    * @brief Return the unique id that can be used to determine this class (used for serialization)
    **/
    AB_group_EXPORT static const String& sendable_object_id();
	
    // usefull parameters    
     /**
     * @brief namespace
if not set the user namespace will be used.
    **/
    accelbyte::Optional<accelbyte::String> ab_namespace{};
     /**
     * @brief User ID
    **/
    accelbyte::String user_id{};
};

}
}
}