// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/match2/match2_export.h"
#include "accelbyte/match2/rule_sets/GetRuleSets.h"
#include "accelbyte/match2/rule_sets/CreateRuleSet.h"
#include "accelbyte/match2/rule_sets/DeleteRuleSet.h"
#include "accelbyte/match2/rule_sets/GetRuleSetDetails.h"
#include "accelbyte/match2/rule_sets/UpdateRuleSet.h"
#include "accelbyte/match2/models/BackFillAcceptRequest.h"
#include "accelbyte/match2/models/BackFillCreateRequest.h"
#include "accelbyte/match2/models/BackfillCreateResponse.h"
#include "accelbyte/match2/models/Backfill.h"
#include "accelbyte/match2/models/BackfillProposal.h"
#include "accelbyte/match2/models/EnvironmentVariables.h"
#include "accelbyte/match2/models/MatchFunctions.h"
#include "accelbyte/match2/models/MatchPoolTickets.h"
#include "accelbyte/match2/models/MatchPools.h"
#include "accelbyte/match2/models/RuleSets.h"
#include "accelbyte/match2/models/Match.h"
#include "accelbyte/match2/models/MatchFunctionConfig.h"
#include "accelbyte/match2/models/MatchFunctionOverride.h"
#include "accelbyte/match2/models/MatchFunctionRequest.h"
#include "accelbyte/match2/models/MatchPool.h"
#include "accelbyte/match2/models/MatchPoolConfig.h"
#include "accelbyte/match2/models/MatchRuleSetNameData.h"
#include "accelbyte/match2/models/MatchTicketRequest.h"
#include "accelbyte/match2/models/MatchTicket.h"
#include "accelbyte/match2/models/MatchTicketStatus.h"
#include "accelbyte/match2/models/MatchTicketStatuses.h"
#include "accelbyte/match2/models/NamespaceConfigs.h"
#include "accelbyte/match2/models/Party.h"
#include "accelbyte/match2/models/PatchNamespaceConfigRequest.h"
#include "accelbyte/match2/models/PlayerData.h"
#include "accelbyte/match2/models/PlayerMetricRecord.h"
#include "accelbyte/match2/models/ProposedProposal.h"
#include "accelbyte/match2/models/RuleSetPayload.h"
#include "accelbyte/match2/models/Team.h"
#include "accelbyte/match2/models/Ticket.h"
#include "accelbyte/match2/models/TicketMetricResultRecord.h"
#include "accelbyte/match2/models/BackFillRejectRequest.h"
#include "accelbyte/match2/models/ConfigEnvironmentVariable.h"
#include "accelbyte/match2/models/ConfigmodelsNamespaceConfig.h"
#include "accelbyte/match2/models/LogconfigConfiguration.h"
#include "accelbyte/match2/models/MatchmakerMatchTicketRecord.h"
#include "accelbyte/match2/models/MatchmakerParty.h"
#include "accelbyte/match2/models/MatchmakerProposedProposal.h"
#include "accelbyte/match2/models/MatchmakerTeam.h"
#include "accelbyte/match2/models/MatchmakerTicket.h"
#include "accelbyte/match2/models/Configuration.h"
#include "accelbyte/match2/models/DSInfo.h"
#include "accelbyte/match2/models/GameSession.h"
#include "accelbyte/match2/models/Pagination.h"
#include "accelbyte/match2/models/Server.h"
#include "accelbyte/match2/models/User.h"
#include "accelbyte/match2/models/PlayerPlayerData.h"
#include "accelbyte/match2/models/Error.h"
#include "accelbyte/common/Error.h"
#include "accelbyte/tls/SecurityAuthorization.h"

#include <functional>
#include "accelbyte/memory/memory.h"

namespace accelbyte {
namespace match2 {

class RuleSets
{
public:	
    /**
    * @brief List existing rule sets
    * @details List rule sets.

    * @details /match2/v1/namespaces/{namespace}/rulesets
    *
    */
    AB_match2_EXPORT static void get_rule_sets(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const rule_sets::GetRuleSets& request, 
        const std::function<void(const model::RuleSets&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Create a match rule set
    * @details Creates a new rules set.

A rule set has a name and contains arbitrary data which is meaningful to some particular match function(s)
The name is used for a match pool to select the ruleset data that should be sent to the match function when matchmaking in that pool.

To use custom rules set please set enable_custom_match_function=true. Default (false).

When custom enable_custom_match_function=true, the ruleset will only validate if the rule is valid json.

    * @details /match2/v1/namespaces/{namespace}/rulesets
    *
    */
    AB_match2_EXPORT static void create_rule_set(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const rule_sets::CreateRuleSet& request, 
        const std::function<void()>& on_201,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Delete a rule set
    * @details Deletes an existing rule set.

    * @details /match2/v1/namespaces/{namespace}/rulesets/{ruleset}
    *
    */
    AB_match2_EXPORT static void delete_rule_set(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const rule_sets::DeleteRuleSet& request, 
        const std::function<void()>& on_204,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Get details for a specific rule set
    * @details Get details for a specific rule set

    * @details /match2/v1/namespaces/{namespace}/rulesets/{ruleset}
    *
    */
    AB_match2_EXPORT static void get_rule_set_details(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const rule_sets::GetRuleSetDetails& request, 
        const std::function<void(const model::RuleSetPayload&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Update a match rule set
    * @details Updates an existing matchmaking rule set.
	
To use custom rules set please set enable_custom_match_function=true. Default (false).

When custom enable_custom_match_function=true, the ruleset will only validate if the rule is valid json.

    * @details /match2/v1/namespaces/{namespace}/rulesets/{ruleset}
    *
    */
    AB_match2_EXPORT static void update_rule_set(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const rule_sets::UpdateRuleSet& request, 
        const std::function<void(const model::RuleSetPayload&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

};

}
}