// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/http/SendableObject.h"
#include "accelbyte/common/DateTime.h"
#include "accelbyte/utils/JsonObjectString.h"
#include "accelbyte/common/Optional.h"
#include "accelbyte/social/social_export.h"

#include "accelbyte/common/String.h"
#include "accelbyte/common/Map.h"
#include "accelbyte/common/Vector.h"


namespace accelbyte {
namespace social {
namespace user_statistic {

/**
* @brief Bulk fetch multiple user&#39;s stat item values for a given namespace and statCode.
NOTE: If stat item does not exist, will return default value. Other detail info:
+ *Returns*: list of user&#39;s stat item values
*/
class AdminDefaultGetStatItems : public accelbyte::http::SendableObject
{
public:
    
    
    /**
    * @brief default constructor.
    **/
	AB_social_EXPORT AdminDefaultGetStatItems() = default;
	
    /**
    * @brief destrutor.
    **/
    AB_social_EXPORT virtual ~AdminDefaultGetStatItems() = default;
	
	/**
    * @brief Return the object unique id (used for serialization)
    **/
    AB_social_EXPORT const String& sendable_id() const override;
	
	/**
    * @brief Return the unique id that can be used to determine this class (used for serialization)
    **/
    AB_social_EXPORT static const String& sendable_object_id();
	
    // usefull parameters    
     /**
     * @brief namespace
if not set the user namespace will be used.
    **/
    accelbyte::Optional<accelbyte::String> ab_namespace{};
     /**
     * @brief stat code
    **/
    accelbyte::String stat_code{};
     /**
     * @brief user ids
    **/
    accelbyte::Vector<accelbyte::String> user_ids{};
};

}
}
}