// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/http/SendableObject.h"
#include "accelbyte/common/DateTime.h"
#include "accelbyte/utils/JsonObjectString.h"
#include "accelbyte/common/Optional.h"
#include "accelbyte/group/group_export.h"

#include "accelbyte/common/String.h"
#include "accelbyte/common/Map.h"
#include "accelbyte/common/Vector.h"


namespace accelbyte {
namespace group {
namespace group {

/**
* @brief Required valid user authentication

Get list of groups. This endpoint will only show OPEN and PUBLIC group type. This endpoint can search based on the group name by filling the &#34;groupName&#34; query parameter

Action Code: 73303
		
*/
class GetGroupsV1 : public accelbyte::http::SendableObject
{
public:
    
    
    /**
    * @brief default constructor.
    **/
	AB_group_EXPORT GetGroupsV1() = default;
	
    /**
    * @brief destrutor.
    **/
    AB_group_EXPORT virtual ~GetGroupsV1() = default;
	
	/**
    * @brief Return the object unique id (used for serialization)
    **/
    AB_group_EXPORT const String& sendable_id() const override;
	
	/**
    * @brief Return the unique id that can be used to determine this class (used for serialization)
    **/
    AB_group_EXPORT static const String& sendable_object_id();
	
    // usefull parameters    
     /**
     * @brief namespace
if not set the user namespace will be used.
    **/
    accelbyte::Optional<accelbyte::String> ab_namespace{};
     /**
     * @brief Query Group Name
    **/
    accelbyte::Optional<accelbyte::String> group_name{};
     /**
     * @brief Query Group Region
    **/
    accelbyte::Optional<accelbyte::String> group_region{};
     /**
     * @brief size of displayed data
    **/
    accelbyte::Optional<long> limit{};
     /**
     * @brief The start position that points to query data
    **/
    accelbyte::Optional<long> offset{};
};

}
}
}