// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/ugc/ugc_export.h"
#include "accelbyte/ugc/admin_group/AdminGetOfficialGroups.h"
#include "accelbyte/ugc/admin_group/AdminCreateGroup.h"
#include "accelbyte/ugc/admin_group/AdminDeleteOfficialGroup.h"
#include "accelbyte/ugc/admin_group/AdminGetOfficialGroup.h"
#include "accelbyte/ugc/admin_group/AdminUpdateOfficialGroup.h"
#include "accelbyte/ugc/admin_group/AdminGetGroupOfficialContents.h"
#include "accelbyte/ugc/admin_group/AdminGetGroups.h"
#include "accelbyte/ugc/admin_group/AdminDeleteGroup.h"
#include "accelbyte/ugc/admin_group/AdminGetGroup.h"
#include "accelbyte/ugc/admin_group/AdminUpdateGroup.h"
#include "accelbyte/ugc/admin_group/AdminGetGroupContents.h"
#include "accelbyte/ugc/admin_group/0887e428b474b3aGroupContentsV2.h"
#include "accelbyte/ugc/admin_group/AdminGetUserGroupContentsV2.h"
#include "accelbyte/ugc/models/DownloadCount.h"
#include "accelbyte/ugc/models/AdminContentRequestV2.h"
#include "accelbyte/ugc/models/AdminGetContentsRequest.h"
#include "accelbyte/ugc/models/AdminUpdateContentRequest.h"
#include "accelbyte/ugc/models/AdminUpdateContentRequestV2.h"
#include "accelbyte/ugc/models/ApproveStagingContentRequest.h"
#include "accelbyte/ugc/models/AdminChannelRequest.h"
#include "accelbyte/ugc/models/Channel.h"
#include "accelbyte/ugc/models/AdminConfigResponse.h"
#include "accelbyte/ugc/models/ContentDownload.h"
#include "accelbyte/ugc/models/ContentDownloadV2.h"
#include "accelbyte/ugc/models/ContentDownloader.h"
#include "accelbyte/ugc/models/ContentLikeRequest.h"
#include "accelbyte/ugc/models/Like.h"
#include "accelbyte/ugc/models/Likers.h"
#include "accelbyte/ugc/models/ContentRequestV2.h"
#include "accelbyte/ugc/models/ContentSnapshot.h"
#include "accelbyte/ugc/models/ContentVersion.h"
#include "accelbyte/ugc/models/CopyContentRequest.h"
#include "accelbyte/ugc/models/CreateContentRequest.h"
#include "accelbyte/ugc/models/AdminCreateContentRequestS3.h"
#include "accelbyte/ugc/models/CreateContent.h"
#include "accelbyte/ugc/models/CreateContentV2.h"
#include "accelbyte/ugc/models/CreateGroupRequest.h"
#include "accelbyte/ugc/models/Group.h"
#include "accelbyte/ugc/models/CreateScreenshotRequest.h"
#include "accelbyte/ugc/models/Screenshots.h"
#include "accelbyte/ugc/models/CreateTagRequest.h"
#include "accelbyte/ugc/models/Tag.h"
#include "accelbyte/ugc/models/CreateTypeRequest.h"
#include "accelbyte/ugc/models/Type.h"
#include "accelbyte/ugc/models/CreatorFollowState.h"
#include "accelbyte/ugc/models/CreatorOverview.h"
#include "accelbyte/ugc/models/Creator.h"
#include "accelbyte/ugc/models/1297a459abe6758ploadURLRequest.h"
#include "accelbyte/ugc/models/ContentUpload.h"
#include "accelbyte/ugc/models/GetContentByShareCodesRequest.h"
#include "accelbyte/ugc/models/GetContentPreviewResponse.h"
#include "accelbyte/ugc/models/HideContentRequest.h"
#include "accelbyte/ugc/models/LikeState.h"
#include "accelbyte/ugc/models/GetContentVersionsResponse.h"
#include "accelbyte/ugc/models/ContentDownloadPagination.h"
#include "accelbyte/ugc/models/ContentDownloadV2Pagination.h"
#include "accelbyte/ugc/models/ContentDownloaderPagination.h"
#include "accelbyte/ugc/models/ContentLikersPagination.h"
#include "accelbyte/ugc/models/CreatorOverviewPagination.h"
#include "accelbyte/ugc/models/GetChannelPagination.h"
#include "accelbyte/ugc/models/GetConfigsPagination.h"
#include "accelbyte/ugc/models/GetTagPagination.h"
#include "accelbyte/ugc/models/GetTypePagination.h"
#include "accelbyte/ugc/models/GroupPagination.h"
#include "accelbyte/ugc/models/StagingContentsPagination.h"
#include "accelbyte/ugc/models/CursorPagination.h"
#include "accelbyte/ugc/models/PayloadURL.h"
#include "accelbyte/ugc/models/PreviewURL.h"
#include "accelbyte/ugc/models/ChannelRequest.h"
#include "accelbyte/ugc/models/CreateContentS3Request.h"
#include "accelbyte/ugc/models/GetContentsRequest.h"
#include "accelbyte/ugc/models/Screenshot.h"
#include "accelbyte/ugc/models/StagingContent.h"
#include "accelbyte/ugc/models/UpdateChannelRequest.h"
#include "accelbyte/ugc/models/UpdateConfigRequest.h"
#include "accelbyte/ugc/models/UpdateContentRequest.h"
#include "accelbyte/ugc/models/UpdateContentRequestV2.h"
#include "accelbyte/ugc/models/UpdateContentV2.h"
#include "accelbyte/ugc/models/UpdateContentShareCodeRequest.h"
#include "accelbyte/ugc/models/UpdateFileLocationRequest.h"
#include "accelbyte/ugc/models/UpdateScreenshotRequest.h"
#include "accelbyte/ugc/models/ScreenshotUpdate.h"
#include "accelbyte/ugc/models/UpdateStagingContentRequest.h"
#include "accelbyte/ugc/models/UserFollowRequest.h"
#include "accelbyte/ugc/models/Follow.h"
#include "accelbyte/ugc/models/CreateScreenshotRequestItem.h"
#include "accelbyte/ugc/models/PreviewMetadata.h"
#include "accelbyte/ugc/models/UpdateScreenshot.h"
#include "accelbyte/ugc/models/Error.h"
#include "accelbyte/common/Error.h"
#include "accelbyte/tls/SecurityAuthorization.h"

#include <functional>
#include "accelbyte/memory/memory.h"

namespace accelbyte {
namespace ugc {

class AdminGroup
{
public:	
    /**
    * @brief Get all user groups
    * @details Get user group paginated
    * @details /ugc/v1/admin/namespaces/{namespace}/groups
    *
    */
    AB_ugc_EXPORT static void admin_get_official_groups(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const admin_group::AdminGetOfficialGroups& request, 
        const std::function<void(const model::GroupPagination&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Create groups
    * @details Create group
    * @details /ugc/v1/admin/namespaces/{namespace}/groups
    *
    */
    AB_ugc_EXPORT static void admin_create_group(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const admin_group::AdminCreateGroup& request, 
        const std::function<void(const model::Group&)>& on_201,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Delete group
    * @details Delete group by group ID
    * @details /ugc/v1/admin/namespaces/{namespace}/groups/{groupId}
    *
    */
    AB_ugc_EXPORT static void admin_delete_official_group(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const admin_group::AdminDeleteOfficialGroup& request, 
        const std::function<void()>& on_204,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Get specific user group
    * @details Get user group by group ID
    * @details /ugc/v1/admin/namespaces/{namespace}/groups/{groupId}
    *
    */
    AB_ugc_EXPORT static void admin_get_official_group(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const admin_group::AdminGetOfficialGroup& request, 
        const std::function<void(const model::Group&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Update group
    * @details Replace group name and contents with new ones.
    * @details /ugc/v1/admin/namespaces/{namespace}/groups/{groupId}
    *
    */
    AB_ugc_EXPORT static void admin_update_official_group(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const admin_group::AdminUpdateOfficialGroup& request, 
        const std::function<void(const model::Group&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief (Legacy) Get contents belong to a group
    * @details Get content belong to a group
    * @details /ugc/v1/admin/namespaces/{namespace}/groups/{groupId}/contents
    *
    */
    AB_ugc_EXPORT static void admin_get_group_official_contents(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const admin_group::AdminGetGroupOfficialContents& request, 
        const std::function<void(const model::ContentDownloadPagination&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Get all user groups
    * @details Get user group paginated
    * @details /ugc/v1/admin/namespaces/{namespace}/users/{userId}/groups
    *
    */
    AB_ugc_EXPORT static void admin_get_groups(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const admin_group::AdminGetGroups& request, 
        const std::function<void(const model::GroupPagination&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Delete group
    * @details Delete group
    * @details /ugc/v1/admin/namespaces/{namespace}/users/{userId}/groups/{groupId}
    *
    */
    AB_ugc_EXPORT static void admin_delete_group(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const admin_group::AdminDeleteGroup& request, 
        const std::function<void()>& on_204,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Get specific user group
    * @details Get user group by group ID
    * @details /ugc/v1/admin/namespaces/{namespace}/users/{userId}/groups/{groupId}
    *
    */
    AB_ugc_EXPORT static void admin_get_group(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const admin_group::AdminGetGroup& request, 
        const std::function<void(const model::Group&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Update group
    * @details Replace group name and contents with new ones.
    * @details /ugc/v1/admin/namespaces/{namespace}/users/{userId}/groups/{groupId}
    *
    */
    AB_ugc_EXPORT static void admin_update_group(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const admin_group::AdminUpdateGroup& request, 
        const std::function<void(const model::Group&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief (Legacy) Get contents belong to a group
    * @details Get content belong to a group
    * @details /ugc/v1/admin/namespaces/{namespace}/users/{userId}/groups/{groupId}/contents
    *
    */
    AB_ugc_EXPORT static void admin_get_group_contents(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const admin_group::AdminGetGroupContents& request, 
        const std::function<void(const model::ContentDownloadPagination&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Get contents belong to a group
    * @details Get contents belong to a group
    * @details /ugc/v2/admin/namespaces/{namespace}/groups/{groupId}/contents
    *
    */
    AB_ugc_EXPORT static void admin_get_official_group_contents_v2(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const admin_group::AdminGetOfficialGroupContentsV2& request, 
        const std::function<void(const model::ContentDownloadV2Pagination&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Get contents belong to a group
    * @details Get contents belong to a group
    * @details /ugc/v2/admin/namespaces/{namespace}/users/{userId}/groups/{groupId}/contents
    *
    */
    AB_ugc_EXPORT static void admin_get_user_group_contents_v2(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const admin_group::AdminGetUserGroupContentsV2& request, 
        const std::function<void(const model::ContentDownloadV2Pagination&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

};

}
}