// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/ugc/ugc_export.h"
#include "accelbyte/ugc/public_content_v2/GetContentByChannelIDV2.h"
#include "accelbyte/ugc/public_content_v2/GetContentsV2.h"
#include "accelbyte/ugc/public_content_v2/GetContentByIdsV2.h"
#include "accelbyte/ugc/public_content_v2/GetContentByShareCodesV2.h"
#include "accelbyte/ugc/public_content_v2/GetContentByShareCodeV2.h"
#include "accelbyte/ugc/public_content_v2/GetContentByIDV2.h"
#include "accelbyte/ugc/public_content_v2/CreateContentV2.h"
#include "accelbyte/ugc/public_content_v2/UpdateContentByShareCodeV2.h"
#include "accelbyte/ugc/public_content_v2/DeleteContentByShareCodeV2.h"
#include "accelbyte/ugc/public_content_v2/DeleteContentV2.h"
#include "accelbyte/ugc/public_content_v2/UpdateContentV2.h"
#include "accelbyte/ugc/public_content_v2/UpdateContentFileLocation.h"
#include "accelbyte/ugc/public_content_v2/UpdateContentShareCodeV2.h"
#include "accelbyte/ugc/public_content_v2/GenerateContentUploadURLV2.h"
#include "accelbyte/ugc/public_content_v2/GetContentByUserIDV2.h"
#include "accelbyte/ugc/public_content_v2/UploadContentScreenshotV2.h"
#include "accelbyte/ugc/public_content_v2/UpdateScreenshotsV2.h"
#include "accelbyte/ugc/public_content_v2/DeleteContentScreenshotV2.h"
#include "accelbyte/ugc/models/DownloadCount.h"
#include "accelbyte/ugc/models/AdminContentRequestV2.h"
#include "accelbyte/ugc/models/AdminGetContentsRequest.h"
#include "accelbyte/ugc/models/AdminUpdateContentRequest.h"
#include "accelbyte/ugc/models/AdminUpdateContentRequestV2.h"
#include "accelbyte/ugc/models/ApproveStagingContentRequest.h"
#include "accelbyte/ugc/models/AdminChannelRequest.h"
#include "accelbyte/ugc/models/Channel.h"
#include "accelbyte/ugc/models/AdminConfigResponse.h"
#include "accelbyte/ugc/models/ContentDownload.h"
#include "accelbyte/ugc/models/ContentDownloadV2.h"
#include "accelbyte/ugc/models/ContentDownloader.h"
#include "accelbyte/ugc/models/ContentLikeRequest.h"
#include "accelbyte/ugc/models/Like.h"
#include "accelbyte/ugc/models/Likers.h"
#include "accelbyte/ugc/models/ContentRequestV2.h"
#include "accelbyte/ugc/models/ContentSnapshot.h"
#include "accelbyte/ugc/models/ContentVersion.h"
#include "accelbyte/ugc/models/CopyContentRequest.h"
#include "accelbyte/ugc/models/CreateContentRequest.h"
#include "accelbyte/ugc/models/AdminCreateContentRequestS3.h"
#include "accelbyte/ugc/models/CreateContent.h"
#include "accelbyte/ugc/models/CreateContentV2.h"
#include "accelbyte/ugc/models/CreateGroupRequest.h"
#include "accelbyte/ugc/models/Group.h"
#include "accelbyte/ugc/models/CreateScreenshotRequest.h"
#include "accelbyte/ugc/models/Screenshots.h"
#include "accelbyte/ugc/models/CreateTagRequest.h"
#include "accelbyte/ugc/models/Tag.h"
#include "accelbyte/ugc/models/CreateTypeRequest.h"
#include "accelbyte/ugc/models/Type.h"
#include "accelbyte/ugc/models/CreatorFollowState.h"
#include "accelbyte/ugc/models/CreatorOverview.h"
#include "accelbyte/ugc/models/Creator.h"
#include "accelbyte/ugc/models/1297a459abe6758ploadURLRequest.h"
#include "accelbyte/ugc/models/ContentUpload.h"
#include "accelbyte/ugc/models/GetContentByShareCodesRequest.h"
#include "accelbyte/ugc/models/GetContentPreviewResponse.h"
#include "accelbyte/ugc/models/HideContentRequest.h"
#include "accelbyte/ugc/models/LikeState.h"
#include "accelbyte/ugc/models/GetContentVersionsResponse.h"
#include "accelbyte/ugc/models/ContentDownloadPagination.h"
#include "accelbyte/ugc/models/ContentDownloadV2Pagination.h"
#include "accelbyte/ugc/models/ContentDownloaderPagination.h"
#include "accelbyte/ugc/models/ContentLikersPagination.h"
#include "accelbyte/ugc/models/CreatorOverviewPagination.h"
#include "accelbyte/ugc/models/GetChannelPagination.h"
#include "accelbyte/ugc/models/GetConfigsPagination.h"
#include "accelbyte/ugc/models/GetTagPagination.h"
#include "accelbyte/ugc/models/GetTypePagination.h"
#include "accelbyte/ugc/models/GroupPagination.h"
#include "accelbyte/ugc/models/StagingContentsPagination.h"
#include "accelbyte/ugc/models/CursorPagination.h"
#include "accelbyte/ugc/models/PayloadURL.h"
#include "accelbyte/ugc/models/PreviewURL.h"
#include "accelbyte/ugc/models/ChannelRequest.h"
#include "accelbyte/ugc/models/CreateContentS3Request.h"
#include "accelbyte/ugc/models/GetContentsRequest.h"
#include "accelbyte/ugc/models/Screenshot.h"
#include "accelbyte/ugc/models/StagingContent.h"
#include "accelbyte/ugc/models/UpdateChannelRequest.h"
#include "accelbyte/ugc/models/UpdateConfigRequest.h"
#include "accelbyte/ugc/models/UpdateContentRequest.h"
#include "accelbyte/ugc/models/UpdateContentRequestV2.h"
#include "accelbyte/ugc/models/UpdateContentV2.h"
#include "accelbyte/ugc/models/UpdateContentShareCodeRequest.h"
#include "accelbyte/ugc/models/UpdateFileLocationRequest.h"
#include "accelbyte/ugc/models/UpdateScreenshotRequest.h"
#include "accelbyte/ugc/models/ScreenshotUpdate.h"
#include "accelbyte/ugc/models/UpdateStagingContentRequest.h"
#include "accelbyte/ugc/models/UserFollowRequest.h"
#include "accelbyte/ugc/models/Follow.h"
#include "accelbyte/ugc/models/CreateScreenshotRequestItem.h"
#include "accelbyte/ugc/models/PreviewMetadata.h"
#include "accelbyte/ugc/models/UpdateScreenshot.h"
#include "accelbyte/ugc/models/Error.h"
#include "accelbyte/common/Error.h"
#include "accelbyte/tls/SecurityAuthorization.h"

#include <functional>
#include "accelbyte/memory/memory.h"

namespace accelbyte {
namespace ugc {

class PublicContentV2
{
public:	
    /**
    * @brief List contents specific to a channel
    * @details Public user can access without token or if token specified, requires valid user token
    * @details /ugc/v2/public/namespaces/{namespace}/channels/{channelId}/contents
    *
    */
    AB_ugc_EXPORT static void get_content_by_channel_idv2(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const public_content_v2::GetContentByChannelIDV2& request, 
        const std::function<void(const model::ContentDownloadV2Pagination&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief List contents
    * @details For advance tag filtering supports &amp; as AND operator and | as OR operator and parentheses ( ) for priority. e.g:  


*tags=red*
*tags=red&amp;animal*
*tags=red|animal*
*tags=red&amp;animal|wild*
*tags=red&amp;(animal|wild)*

The precedence of logical operator is AND &gt; OR, so if no parentheses, AND logical operator will be executed first.  

Allowed character for operand: alphanumeric, underscore _ and dash -  

Allowed character for operator: &amp; | ( )


**Please note that value of tags query param should be URL encoded**
    * @details /ugc/v2/public/namespaces/{namespace}/contents
    *
    */
    AB_ugc_EXPORT static void get_contents_v2(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const public_content_v2::GetContentsV2& request, 
        const std::function<void(const model::ContentDownloadV2Pagination&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Get contents by content Ids 
    * @details Maximum requested Ids: 100.
			Public user can access without token or if token specified, requires valid user token
    * @details /ugc/v2/public/namespaces/{namespace}/contents/bulk
    *
    */
    AB_ugc_EXPORT static void get_content_by_ids_v2(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const public_content_v2::GetContentByIdsV2& request, 
        const std::function<void(const accelbyte::Vector<model::ContentDownloadV2>&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Bulk get content by content sharecodes
    * @details Require valid user token.
							Maximum sharecodes per request 100
    * @details /ugc/v2/public/namespaces/{namespace}/contents/sharecodes/bulk
    *
    */
    AB_ugc_EXPORT static void get_content_by_share_codes_v2(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const public_content_v2::GetContentByShareCodesV2& request, 
        const std::function<void(const accelbyte::Vector<model::ContentDownloadV2>&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Get content by sharecode
    * @details Public user can access without token or if token specified, requires valid user token
    * @details /ugc/v2/public/namespaces/{namespace}/contents/sharecodes/{shareCode}
    *
    */
    AB_ugc_EXPORT static void get_content_by_share_code_v2(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const public_content_v2::GetContentByShareCodeV2& request, 
        const std::function<void(const model::ContentDownloadV2&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Get content by content ID
    * @details Public user can access without token or if token specified, requires valid user token
    * @details /ugc/v2/public/namespaces/{namespace}/contents/{contentId}
    *
    */
    AB_ugc_EXPORT static void get_content_by_idv2(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const public_content_v2::GetContentByIDV2& request, 
        const std::function<void(const model::ContentDownloadV2&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Create a content
    * @details Create a new content
    * @details /ugc/v2/public/namespaces/{namespace}/users/{userId}/channels/{channelId}/contents
    *
    */
    AB_ugc_EXPORT static void create_content_v2(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const public_content_v2::CreateContentV2& request, 
        const std::function<void(const model::CreateContentV2&)>& on_201,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Update content to S3 bucket by share code
    * @details Update content by share code
    * @details /ugc/v2/public/namespaces/{namespace}/users/{userId}/channels/{channelId}/contents/s3/sharecodes/{shareCode}
    *
    */
    AB_ugc_EXPORT static void update_content_by_share_code_v2(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const public_content_v2::UpdateContentByShareCodeV2& request, 
        const std::function<void(const model::CreateContentV2&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Delete content by share code
    * @details Delete existing content by share code
    * @details /ugc/v2/public/namespaces/{namespace}/users/{userId}/channels/{channelId}/contents/sharecodes/{shareCode}
    *
    */
    AB_ugc_EXPORT static void delete_content_by_share_code_v2(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const public_content_v2::DeleteContentByShareCodeV2& request, 
        const std::function<void()>& on_204,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Delete content
    * @details Delete existing content
    * @details /ugc/v2/public/namespaces/{namespace}/users/{userId}/channels/{channelId}/contents/{contentId}
    *
    */
    AB_ugc_EXPORT static void delete_content_v2(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const public_content_v2::DeleteContentV2& request, 
        const std::function<void()>& on_204,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Update content
    * @details Update existing content
    * @details /ugc/v2/public/namespaces/{namespace}/users/{userId}/channels/{channelId}/contents/{contentId}
    *
    */
    AB_ugc_EXPORT static void update_content_v2(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const public_content_v2::UpdateContentV2& request, 
        const std::function<void(const model::UpdateContentV2&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Update content file location
    * @details This endpoint should be used after calling generate upload url endpoint to commit the changes
    * @details /ugc/v2/public/namespaces/{namespace}/users/{userId}/channels/{channelId}/contents/{contentId}/fileLocation
    *
    */
    AB_ugc_EXPORT static void update_content_file_location(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const public_content_v2::UpdateContentFileLocation& request, 
        const std::function<void(const model::UpdateContentV2&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Update content share code
    * @details This endpoint is used to modify the shareCode of a content. However, this operation is restricted by default and requires the above permission to be granted to the User role.&lt;br&gt;
								&lt;code&gt;shareCode&lt;/code&gt; format should follows:
								Max length: 7
								Available characters: abcdefhkpqrstuxyz
    * @details /ugc/v2/public/namespaces/{namespace}/users/{userId}/channels/{channelId}/contents/{contentId}/sharecode
    *
    */
    AB_ugc_EXPORT static void update_content_share_code_v2(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const public_content_v2::UpdateContentShareCodeV2& request, 
        const std::function<void(const model::CreateContentV2&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Generate content upload URL
    * @details Generate content upload URL
    * @details /ugc/v2/public/namespaces/{namespace}/users/{userId}/channels/{channelId}/contents/{contentId}/uploadUrl
    *
    */
    AB_ugc_EXPORT static void generate_content_upload_urlv2(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const public_content_v2::GenerateContentUploadURLV2& request, 
        const std::function<void(const model::ContentUpload&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Get content by user ID
    * @details Public user can access without token or if token specified, required permission &lt;b&gt;NAMESPACE:{namespace}:USER:{userId}:CONTENT [READ]&lt;/b&gt;.
    * @details /ugc/v2/public/namespaces/{namespace}/users/{userId}/contents
    *
    */
    AB_ugc_EXPORT static void get_content_by_user_idv2(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const public_content_v2::GetContentByUserIDV2& request, 
        const std::function<void(const model::ContentDownloadV2Pagination&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Upload screenshots for content
    * @details This endpoint used to request upload URL from content&#39;s screenshot.  
If *contentType* is not specified, it will use *fileExtension* value.
Supported file extensions: pjp, jpg, jpeg, jfif, bmp, png.
Maximum description length: 1024
    * @details /ugc/v2/public/namespaces/{namespace}/users/{userId}/contents/{contentId}/screenshots
    *
    */
    AB_ugc_EXPORT static void upload_content_screenshot_v2(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const public_content_v2::UploadContentScreenshotV2& request, 
        const std::function<void(const model::Screenshots&)>& on_201,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Update screenshot of content
    * @details Maximum description length: 1024
    * @details /ugc/v2/public/namespaces/{namespace}/users/{userId}/contents/{contentId}/screenshots
    *
    */
    AB_ugc_EXPORT static void update_screenshots_v2(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const public_content_v2::UpdateScreenshotsV2& request, 
        const std::function<void(const model::ScreenshotUpdate&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Delete screenshots content
    * @details Delete screenshot from a content
    * @details /ugc/v2/public/namespaces/{namespace}/users/{userId}/contents/{contentId}/screenshots/{screenshotId}
    *
    */
    AB_ugc_EXPORT static void delete_content_screenshot_v2(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const public_content_v2::DeleteContentScreenshotV2& request, 
        const std::function<void()>& on_204,
        const std::function<void (const accelbyte::Error&)>& on_error);   

};

}
}