// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/http/ModelObject.h"
#include "accelbyte/common/Optional.h"
#include "accelbyte/common/String.h"
#include "accelbyte/common/Map.h"
#include "accelbyte/common/Vector.h"
#include "accelbyte/common/DateTime.h"
#include "accelbyte/memory/memory.h"
#include "accelbyte/utils/JsonObjectString.h"
#include "accelbyte/gdpr/gdpr_export.h"


namespace accelbyte {
namespace gdpr {
namespace model {

class FinishedRequest : public accelbyte::http::ModelObject
{
public:
    enum class Status : uint32_t {
        UNKNOWN,
        COMPLETED_FAILED
    };
    /**
    * @brief default constructor.
    **/
	AB_gdpr_EXPORT  FinishedRequest() = default;
	
    /**
    * @brief destructor.
    **/
    AB_gdpr_EXPORT virtual ~FinishedRequest() = default;
	
	/**
    * @brief Return the object unique id (used for serialization)
    **/
    AB_gdpr_EXPORT virtual const String& model_id() const override;
	
	/**
    * @brief Return the unique id that can be used to determine this class (used for serialization)
    **/
    AB_gdpr_EXPORT static const String& model_object_id();
    
    // start of usefull parameters
	accelbyte::Optional<accelbyte::DateTime> data_expiration_date{};
	accelbyte::Optional<accelbyte::String> failed_message{};
	accelbyte::DateTime finished_date{};
	accelbyte::DateTime request_date{};
	Status status{};
	accelbyte::String user_id{};
};

}
}
}