// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/http/ModelObject.h"
#include "accelbyte/common/Optional.h"
#include "accelbyte/common/String.h"
#include "accelbyte/common/Map.h"
#include "accelbyte/common/Vector.h"
#include "accelbyte/common/DateTime.h"
#include "accelbyte/memory/memory.h"
#include "accelbyte/utils/JsonObjectString.h"
#include "accelbyte/iam/iam_export.h"


namespace accelbyte {
namespace iam {
namespace model {

class AdminUserUpdateRequestV3 : public accelbyte::http::ModelObject
{
public:
    /**
    * @brief default constructor.
    **/
	AB_iam_EXPORT  AdminUserUpdateRequestV3() = default;
	
    /**
    * @brief destructor.
    **/
    AB_iam_EXPORT virtual ~AdminUserUpdateRequestV3() = default;
	
	/**
    * @brief Return the object unique id (used for serialization)
    **/
    AB_iam_EXPORT virtual const String& model_id() const override;
	
	/**
    * @brief Return the unique id that can be used to determine this class (used for serialization)
    **/
    AB_iam_EXPORT static const String& model_object_id();
    
    // start of usefull parameters
	accelbyte::Optional<accelbyte::String> avatar_url{};
	accelbyte::Optional<accelbyte::String> country{};
	accelbyte::Optional<accelbyte::String> date_of_birth{};
	accelbyte::Optional<accelbyte::String> display_name{};
	accelbyte::Optional<accelbyte::String> language_tag{};
	accelbyte::Optional<bool> skip_login_queue{};
	accelbyte::Optional<accelbyte::String> unique_display_name{};
	accelbyte::Optional<accelbyte::String> user_name{};
};

}
}
}