// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/http/SendableObject.h"
#include "accelbyte/common/DateTime.h"
#include "accelbyte/utils/JsonObjectString.h"
#include "accelbyte/common/Optional.h"
#include "accelbyte/turn_manager/turn_manager_export.h"

#include "accelbyte/common/String.h"
#include "accelbyte/common/Map.h"
#include "accelbyte/common/Vector.h"


namespace accelbyte {
namespace turn_manager {
namespace admin {

/**
* @brief ```
This endpoint get turn auto scale config by region.
```
*/
class AdminGetAutoscaleConfig : public accelbyte::http::SendableObject
{
public:
    
    
    /**
    * @brief default constructor.
    **/
	AB_turn_manager_EXPORT AdminGetAutoscaleConfig() = default;
	
    /**
    * @brief destrutor.
    **/
    AB_turn_manager_EXPORT virtual ~AdminGetAutoscaleConfig() = default;
	
	/**
    * @brief Return the object unique id (used for serialization)
    **/
    AB_turn_manager_EXPORT const String& sendable_id() const override;
	
	/**
    * @brief Return the unique id that can be used to determine this class (used for serialization)
    **/
    AB_turn_manager_EXPORT static const String& sendable_object_id();
	
    // usefull parameters    
     /**
     * @brief region
    **/
    accelbyte::String region{};
};

}
}
}