// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/http/SendableObject.h"
#include "accelbyte/common/DateTime.h"
#include "accelbyte/utils/JsonObjectString.h"
#include "accelbyte/common/Optional.h"
#include "accelbyte/cloudsave/cloudsave_export.h"

#include "accelbyte/common/String.h"
#include "accelbyte/common/Map.h"
#include "accelbyte/common/Vector.h"

#include "accelbyte/cloudsave/models/UploadBinaryRecordRequest.h"

namespace accelbyte {
namespace cloudsave {
namespace public_game_binary_record {

/**
* @brief Request presigned URL to upload the binary record to s3.

Other detail info:

Supported file types: jpeg, jpg, png, bmp, gif, mp3, webp, and bin.

*/
class CreateGameBinaryPresignedURLV1 : public accelbyte::http::SendableObject
{
public:
    
    
    /**
    * @brief default constructor.
    **/
	AB_cloudsave_EXPORT CreateGameBinaryPresignedURLV1() = default;
	
    /**
    * @brief destrutor.
    **/
    AB_cloudsave_EXPORT virtual ~CreateGameBinaryPresignedURLV1() = default;
	
	/**
    * @brief Return the object unique id (used for serialization)
    **/
    AB_cloudsave_EXPORT const String& sendable_id() const override;
	
	/**
    * @brief Return the unique id that can be used to determine this class (used for serialization)
    **/
    AB_cloudsave_EXPORT static const String& sendable_object_id();
	
    // usefull parameters    
     /**
     * @brief None
    **/
    model::UploadBinaryRecordRequest body{};
     /**
     * @brief key of record
    **/
    accelbyte::String key{};
     /**
     * @brief namespace of the game, only accept alphabet and numeric
if not set the user namespace will be used.
    **/
    accelbyte::Optional<accelbyte::String> ab_namespace{};
};

}
}
}