// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/session/session_export.h"
#include "accelbyte/session/configuration_template/AdminDeleteConfigAlertV1.h"
#include "accelbyte/session/configuration_template/AdminGetConfigAlertV1.h"
#include "accelbyte/session/configuration_template/AdminCreateConfigAlertV1.h"
#include "accelbyte/session/configuration_template/AdminUpdateConfigAlertV1.h"
#include "accelbyte/session/configuration_template/AdminCreateConfigTemplateV1.h"
#include "accelbyte/session/configuration_template/AdminGetAllConfigTemplatesV1.h"
#include "accelbyte/session/configuration_template/AdminDeleteConfigTemplateV1.h"
#include "accelbyte/session/configuration_template/AdminGetConfigTemplateV1.h"
#include "accelbyte/session/configuration_template/AdminUpdateConfigTemplateV1.h"
#include "accelbyte/session/configuration_template/AdminGetDSMCConfig.h"
#include "accelbyte/session/configuration_template/AdminSyncDSMCConfig.h"
#include "accelbyte/session/models/AppendMemberGameSessionRequest.h"
#include "accelbyte/session/models/CreateConfigAlertRequest.h"
#include "accelbyte/session/models/ConfigAlert.h"
#include "accelbyte/session/models/ConfigTemplate.h"
#include "accelbyte/session/models/ConfigTemplates.h"
#include "accelbyte/session/models/CreateConfigTemplateRequest.h"
#include "accelbyte/session/models/CreateGameSessionRequest.h"
#include "accelbyte/session/models/CreatePartyRequest.h"
#include "accelbyte/session/models/DSInfo.h"
#include "accelbyte/session/models/DeleteGameSessionsRequest.h"
#include "accelbyte/session/models/DeleteGameSessions.h"
#include "accelbyte/session/models/DeletePartySessions.h"
#include "accelbyte/session/models/DeletePartySessionsResponse.h"
#include "accelbyte/session/models/EnvVariables.h"
#include "accelbyte/session/models/EnvVariable.h"
#include "accelbyte/session/models/GameSessions.h"
#include "accelbyte/session/models/GameSession.h"
#include "accelbyte/session/models/GlobalConfig.h"
#include "accelbyte/session/models/JoinByCodeRequest.h"
#include "accelbyte/session/models/PartyKick.h"
#include "accelbyte/session/models/SessionPagination.h"
#include "accelbyte/session/models/PSNAppServerCredentialRecord.h"
#include "accelbyte/session/models/Pagination.h"
#include "accelbyte/session/models/Parties.h"
#include "accelbyte/session/models/PartySession.h"
#include "accelbyte/session/models/PlayerAttributesRequestBody.h"
#include "accelbyte/session/models/PlayerAttributes.h"
#include "accelbyte/session/models/PlayerPlatform.h"
#include "accelbyte/session/models/PlayersCurrentPlatformRequest.h"
#include "accelbyte/session/models/PlayersCurrentPlatform.h"
#include "accelbyte/session/models/PromoteLeaderRequest.h"
#include "accelbyte/session/models/ConfigInfo.h"
#include "accelbyte/session/models/UpdateGlobalConfigRequest.h"
#include "accelbyte/session/models/65f791541e2ae44dentialsRequest.h"
#include "accelbyte/session/models/MemberRequest.h"
#include "accelbyte/session/models/DeleteGameSession.h"
#include "accelbyte/session/models/DeletedPartySessions.h"
#include "accelbyte/session/models/ServerSecret.h"
#include "accelbyte/session/models/SessionInviteRequest.h"
#include "accelbyte/session/models/SessionInvite.h"
#include "accelbyte/session/models/SessionStorageRequest.h"
#include "accelbyte/session/models/SetDSReadyRequest.h"
#include "accelbyte/session/models/UpdateConfigTemplateRequest.h"
#include "accelbyte/session/models/94f65b9df7cb67cBackfillRequest.h"
#include "accelbyte/session/models/UpdateGameSessionMemberStatus.h"
#include "accelbyte/session/models/UpdateGameSessionRequest.h"
#include "accelbyte/session/models/UpdatePartyRequest.h"
#include "accelbyte/session/models/User.h"
#include "accelbyte/session/models/XblCertificate.h"
#include "accelbyte/session/models/LogConfig.h"
#include "accelbyte/session/models/Session.h"
#include "accelbyte/session/models/SessionMember.h"
#include "accelbyte/session/models/DSMConfigRecord.h"
#include "accelbyte/session/models/DefaultDSMCConfig.h"
#include "accelbyte/session/models/ExtendConfig.h"
#include "accelbyte/session/models/GameServer.h"
#include "accelbyte/session/models/MemberActiveSession.h"
#include "accelbyte/session/models/SessionSetting.h"
#include "accelbyte/session/models/PSNAppServerCredentials.h"
#include "accelbyte/session/models/PartyMembers.h"
#include "accelbyte/session/models/PlatformCredentials.h"
#include "accelbyte/session/models/PortConfigAMS.h"
#include "accelbyte/session/models/RecentPlayerQuery.h"
#include "accelbyte/session/models/c1e21684fe5f509eSessionRequest.h"
#include "accelbyte/session/models/Team.h"
#include "accelbyte/session/models/UserInfo.h"
#include "accelbyte/session/models/UserPlatform.h"
#include "accelbyte/session/models/XBLCertificateCredential.h"
#include "accelbyte/session/models/Error.h"
#include "accelbyte/common/Error.h"
#include "accelbyte/tls/SecurityAuthorization.h"

#include <functional>
#include "accelbyte/memory/memory.h"

namespace accelbyte {
namespace session {

class ConfigurationTemplate
{
public:	
    /**
    * @brief Delete configuration alert.
    * @details Delete configuration alert.
    * @details /session/v1/admin/namespaces/{namespace}/alerts-configuration
    *
    */
    AB_session_EXPORT static void admin_delete_config_alert_v1(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const configuration_template::AdminDeleteConfigAlertV1& request, 
        const std::function<void()>& on_204,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Get configuration alert.
    * @details Get a configuration alert.
    * @details /session/v1/admin/namespaces/{namespace}/alerts-configuration
    *
    */
    AB_session_EXPORT static void admin_get_config_alert_v1(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const configuration_template::AdminGetConfigAlertV1& request, 
        const std::function<void(const model::ConfigAlert&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Create configuration alert.
    * @details Create configuration alert
configuration alert mandatory :
- namespace
- durationDays must be greater than 0

    * @details /session/v1/admin/namespaces/{namespace}/alerts-configuration
    *
    */
    AB_session_EXPORT static void admin_create_config_alert_v1(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const configuration_template::AdminCreateConfigAlertV1& request, 
        const std::function<void(const model::ConfigAlert&)>& on_201,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Update configuration alert.
    * @details Update configuration alert
configuration alert mandatory :
- namespace
- durationDays must be greater than 0

    * @details /session/v1/admin/namespaces/{namespace}/alerts-configuration
    *
    */
    AB_session_EXPORT static void admin_update_config_alert_v1(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const configuration_template::AdminUpdateConfigAlertV1& request, 
        const std::function<void(const model::ConfigAlert&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Create configuration template.
    * @details Create template configuration to be applied across party and session.
Session configuration mandatory :
- name
- joinability. supported values:
	- OPEN: user can join or rejoin the session without an invite
	- CLOSED: once a CLOSED session is created or a session joinability is updated to CLOSED, any change to session members is not allowed and remaining invites will all be canceled.
	- INVITE_ONLY: to join the session, user whether needs to be invited, or have the code (for join by code). when a user is KICKED/LEFT/REJECTED from this session, they will need to be re-invited to join.
	- FRIENDS_OF_MEMBERS: only if a user is friend with at least one of the session members, they can join via code.
	- FRIENDS_OF_LEADER: only if a user is friend with the session leader, they can join via code.
	- FRIENDS_OF_FRIENDS: only friends of the leader OR friends of friends of the leader can join via code.
- autoJoin: when enabled, players will automatically join the initial game session creation. Game session will not send any invite and players dont need to act upon it. default: false (disabled)
- Type (example value : P2P, DS, NONE) if type empty, type will be assign to NONE
- MinPlayers (must greater or equal 0)
- MaxPlayers (must greater than 0)
- InviteTimeout (must greater or equal 0) if InviteTimeout equal 0 will be use default DefaultTimeoutSecond (60s)
- InactiveTimeout (must greater or equal 0) if InactiveTimeout equal 0 will be use default DefaultTimeoutSecond (60s)
- Persistent will only applies to session with type DS (example value true or false, default: false)
	- If Persistent True the session always active even DS removing or terminate and Session will be request DS again until DS Ready or Busy.
	- To Stop Session Not request again to DS or want Delete Session can Delete Session using endpoint DELETE /session/v1/public/namespaces/{namespace}/gamesessions/{sessionId}
	- If Persistent False the session will be inactive if all member left and DS terminate or removing
- nativeSessionSetting:
	- XboxSessionTemplateName: the XBox session template name that correspondent to the AB session template, and is needed to define XBox session&#39;s joinRestriction and maxMembersCount when doing the session sync.
	- XboxServiceConfigID: the XBox service configuration ID.
	- PSNServiceLabel: the PSN service label.
	- SessionTitle: the session title. In PSN, this will be used to define name of the session thats displayed on PlayStation system UI.
	- ShouldSync: to define whether the service needs to do session sync with native platform(s). Default: false (disabled).
	- PSNSupportedPlatforms: the PSN supported platforms. In PSN, if ShouldSync true and PSNSupportedPlatforms is empty, then PS5 will be set as default value.
- PSNBaseUrl this is for base URL PSN if not set will be default value https://s2s.sp-int.playstation.net. In a single namespace only 1 PSN Env that can be used. Multiple session template should refers to the same PSN Env as we have in IAM Service.
	- https://s2s.sp-int.playstation.net (DEV, need IP Whitelist)
	- https://s2s.prod-qa.playstation.net (QA Environment/PSN Certification)
	- https://s2s.np.playstation.net (Production)
	- localizedSessionName : for localized name and default language
		example payload :
		&#34;localizedSessionName&#34;:{
			&#34;defaultLanguage&#34; : &#34;en-US&#34;
			&#34;localizedText&#34; :{
				&#34;en-US&#34; : &#34;title&#34;
			}
		}
	- if the game client wants to enable push context to PSN, game client will need to store PSN_PUSH_CONTEXT_ID on the player attributes, otherwise Session service will try to populate from the session attributes or auto generate with random UUID if empty.
- TieTeamsSessionLifetime (optional, default: false): If it is set to true, the lifetime of any partyId session inside teams attribute will be tied to the game session. Only applies when the teams partyId is game session.
- DisableCodeGeneration (optional, default: false): If it is set to true, code will not be generated for party session automatically. 
- DSManualSetReady (optional, default: false): The DS need to call specific end point to flag the DS for game session is ready to accept client connection. 
- EnableSecret (optional, default: false): if configuration template is created with TypeDS and EnableSecret is True, A secret will be created
- LeaderElectionGracePeriod this is on second (optional, default:0) this is only use for party session, if value &gt; 0 if leader disconnect will be wait until value reach and leader will be change after reach
- ManualRejoin (optional, default: false): indicates if game client will handle manual rejoin upon websocket reconnection when enabled.
- DisableResendInvite (optional, default: false): by default, the service will be sending invites until the user reacts to it. enabling this flag will prohibit the service to send reminder invites&#39;.
- appName (optional, default: empty string). Extend application name that uploaded to AccelByte extends deployment. The application is for custom/external DS management.
- customURLGRPC (optional: default: empty string). Url for grpc server that server custom/external DS management. This value will be ignore when appName is filled. Value formatted as host:port. Example: yourdomain.com:9989 
- grpcSessionConfig (optional, default: empty object). Setting for grpc session extends. Session service will calls the grpc when any activity for the game sessions.
	- appName (required when customURL is empty) The extends app name that created and uploaded to AccelByte extends deployment.
	- customURL (required when appName is empty) The url for grpc server. Format is host:port. Example: mycustomdomain.com:9889. This will be ignore when appName is filled.
	- functionFlag (optional, default: -1) Flag to enable which function to calls when any event on the game sessions. The value is bitwise integer.
		- 0x1 is for created event. Event is sync, anything return from create event will be overide the final game session.
		- 0x2 is for updated event. Event is async. Called when any update on the game session.
		- 0x4 is for deleted event. Event is async. Callen when game session got deleted.
		Example: 
			- value 3: enable for created and updated
			- value 7: enable for created, updated, and deleted, etc

    * @details /session/v1/admin/namespaces/{namespace}/configuration
    *
    */
    AB_session_EXPORT static void admin_create_config_template_v1(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const configuration_template::AdminCreateConfigTemplateV1& request, 
        const std::function<void(const model::ConfigTemplate&)>& on_201,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Get configuration templates.
    * @details Get all template configurations in specified namespace.
    * @details /session/v1/admin/namespaces/{namespace}/configurations
    *
    */
    AB_session_EXPORT static void admin_get_all_config_templates_v1(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const configuration_template::AdminGetAllConfigTemplatesV1& request, 
        const std::function<void(const model::ConfigTemplates&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Delete configuration template.
    * @details Delete a template configuration.
    * @details /session/v1/admin/namespaces/{namespace}/configurations/{name}
    *
    */
    AB_session_EXPORT static void admin_delete_config_template_v1(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const configuration_template::AdminDeleteConfigTemplateV1& request, 
        const std::function<void()>& on_204,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Get configuration template.
    * @details Get a template configuration.
    * @details /session/v1/admin/namespaces/{namespace}/configurations/{name}
    *
    */
    AB_session_EXPORT static void admin_get_config_template_v1(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const configuration_template::AdminGetConfigTemplateV1& request, 
        const std::function<void(const model::ConfigTemplate&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Update configuration template.
    * @details Modify template configuration
Session configuration mandatory :
- name
- joinability. supported values:
	- OPEN: user can join or rejoin the session without an invite
	- CLOSED: once a CLOSED session is created or a session joinability is updated to CLOSED, any change to session members is not allowed and remaining invites will all be canceled.
	- INVITE_ONLY: to join the session, user whether needs to be invited, or have the code (for join by code). when a user is KICKED/LEFT/REJECTED from this session, they will need to be re-invited to join.
	- FRIENDS_OF_MEMBERS: only if a user is friend with at least one of the session members, they can join via code.
	- FRIENDS_OF_LEADER: only if a user is friend with the session leader, they can join via code.
	- FRIENDS_OF_FRIENDS: only friends of the leader OR friends of friends of the leader can join via code.
- autoJoin: when enabled, players will automatically join the initial game session creation. Game session will not send any invite and players dont need to act upon it. default: false (disabled)
- Type (example value : P2P, DS, NONE) if type empty, type will be assign to NONE
- MinPlayers (must greater or equal 0)
- MaxPlayers (must greater than 0)
- InviteTimeout (must greater or equal 0) if InviteTimeout equal 0 will be use default DefaultTimeoutSecond (60s)
- InactiveTimeout (must greater or equal 0) if InactiveTimeout equal 0 will be use default DefaultTimeoutSecond (60s)
- Persistent Flag only can use with type DS (example value true or false)
- If Persistent True the session always active even DS removing or terminate and Session will be request DS again until DS Ready or Busy.
- To Stop Session Not request again to DS or want Delete Session can Delete Session using endpoint DELETE /session/v1/public/namespaces/{namespace}/gamesessions/{sessionId}
- If Persistent False the session will be inactive if all member left and DS terminate or removing
- nativeSessionSetting:
	- XboxSessionTemplateName: the XBox session template name that correspondent to the AB session template, and is needed to define XBox session&#39;s joinRestriction and maxMembersCount when doing the session sync.
	- XboxServiceConfigID: the XBox service configuration ID.
	- PSNServiceLabel: the PSN service label.
	- SessionTitle: the session title. In PSN, this will be used to define name of the session thats displayed on PlayStation system UI.
	- ShouldSync: to define whether the service needs to do session sync with native platform(s). Default: false (disabled).
	- PSNSupportedPlatforms: the PSN supported platforms. In PSN, if ShouldSync true and PSNSupportedPlatforms is empty, then PS5 will be set as default value.
- PSNBaseUrl this is for base URL PSN if not set will be default value https://s2s.sp-int.playstation.net. In a single namespace only 1 PSN Env that can be used. Multiple session template should refers to the same PSN Env as we have in IAM Service.
	- https://s2s.sp-int.playstation.net (DEV, need IP Whitelist)
	- https://s2s.prod-qa.playstation.net (QA Environment/PSN Certification)
	- https://s2s.np.playstation.net (Production)
	- localizedSessionName : for localized name and default language
		example payload :
		&#34;localizedSessionName&#34;:{
			&#34;defaultLanguage&#34; : &#34;en-US&#34;
			&#34;localizedText&#34; :{
				&#34;en-US&#34; : &#34;title&#34;
			}
		}
	- if the game client wants to enable push context to PSN, game client will need to store PSN_PUSH_CONTEXT_ID on the player attributes, otherwise Session service will try to populate from the session attributes or auto generate with random UUID if empty.
- TieTeamsSessionLifetime: If it is set to true, the lifetime of any partyId session inside teams attribute will be tied to the game session. Only applies when the teams partyId is game session.
- DisableCodeGeneration (optional, default: false): If it is set to true, code will not be generated for party session automatically. 
- DSManualSetReady (optional, default: false): The DS need to call specific end point to flag the DS for game session is ready to accept client connection. 
- EnableSecret (optional, default: false): if configuration template is created with TypeDS and EnableSecret is True, A secret will be created.
- ManualRejoin (optional, default: false): indicates if game client will handle manual rejoin upon websocket reconnection when enabled.
         - DisableResendInvite (optional, default: false): by default, the service will be sending invites until the user reacts to it. enabling this flag will prohibit the service to send reminder invites&#39;.
- appName (optional, default: empty string). Extend application name that uploaded to AccelByte extends deployment. The application is for custom/external DS management.
- customURLGRPC (optional: default: empty string). Url for grpc server that server custom/external DS management. This value will be ignore when appName is filled. Value formatted as host:port. Example: yourdomain.com:9989
- grpcSessionConfig (optional, default: empty object). Setting for grpc session extends. Session service will calls the grpc when any activity for the game sessions.
	- appName (required when customURL is empty) The extends app name that created and uploaded to AccelByte extends deployment.
	- customURL (required when appName is empty) The url for grpc server. Format is host:port. Example: mycustomdomain.com:9889. This will be ignore when appName is filled.
	- functionFlag (optional, default: -1) Flag to enable which function to calls when any event on the game sessions. The value is bitwise integer.
		- 0x1 is for created event. Event is sync, anything return from create event will be overide the final game session.
		- 0x2 is for updated event. Event is async. Called when any update on the game session.
		- 0x4 is for deleted event. Event is async. Callen when game session got deleted.
		Example: 
			- value 3: enable for created and updated
			- value 7: enable for created, updated, and deleted, etc

    * @details /session/v1/admin/namespaces/{namespace}/configurations/{name}
    *
    */
    AB_session_EXPORT static void admin_update_config_template_v1(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const configuration_template::AdminUpdateConfigTemplateV1& request, 
        const std::function<void(const model::ConfigTemplate&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Get dsmc configuration .
    * @details Get a dsmc configuration.
    * @details /session/v1/admin/namespaces/{namespace}/dsconfigs
    *
    */
    AB_session_EXPORT static void admin_get_dsmc_config(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const configuration_template::AdminGetDSMCConfig& request, 
        const std::function<void(const model::DSMConfigRecord&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief sync dsmc configuration.
    * @details sync dsmc configuration.
    * @details /session/v1/admin/namespaces/{namespace}/dsconfigs/sync
    *
    */
    AB_session_EXPORT static void admin_sync_dsmc_config(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const configuration_template::AdminSyncDSMCConfig& request, 
        const std::function<void(const model::DSMConfigRecord&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

};

}
}