// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/http/ModelObject.h"
#include "accelbyte/common/Optional.h"
#include "accelbyte/common/String.h"
#include "accelbyte/common/Map.h"
#include "accelbyte/common/Vector.h"
#include "accelbyte/common/DateTime.h"
#include "accelbyte/memory/memory.h"
#include "accelbyte/utils/JsonObjectString.h"
#include "accelbyte/legal/legal_export.h"


namespace accelbyte {
namespace legal {
namespace model {

class FieldError : public accelbyte::http::ModelObject
{
public:
    /**
    * @brief default constructor.
    **/
	AB_legal_EXPORT  FieldError() = default;
	
    /**
    * @brief destructor.
    **/
    AB_legal_EXPORT virtual ~FieldError() = default;
	
	/**
    * @brief Return the object unique id (used for serialization)
    **/
    AB_legal_EXPORT virtual const String& model_id() const override;
	
	/**
    * @brief Return the unique id that can be used to determine this class (used for serialization)
    **/
    AB_legal_EXPORT static const String& model_object_id();
    
    // start of usefull parameters
	accelbyte::Optional<accelbyte::String> error_code{};
	accelbyte::Optional<accelbyte::String> error_field{};
	accelbyte::Optional<accelbyte::String> error_message{};
	accelbyte::Optional<accelbyte::String> error_value{};
	accelbyte::Optional<accelbyte::Map<accelbyte::String,accelbyte::String>> message_variables{};
};

}
}
}