// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/http/ModelObject.h"
#include "accelbyte/common/Optional.h"
#include "accelbyte/common/String.h"
#include "accelbyte/common/Map.h"
#include "accelbyte/common/Vector.h"
#include "accelbyte/common/DateTime.h"
#include "accelbyte/memory/memory.h"
#include "accelbyte/utils/JsonObjectString.h"
#include "accelbyte/session/session_export.h"

#include "accelbyte/session/models/DSInfo.h"
#include "accelbyte/session/models/ConfigInfo.h"
#include "accelbyte/session/models/User.h"
#include "accelbyte/session/models/Team.h"

namespace accelbyte {
namespace session {
namespace model {

class GameSession : public accelbyte::http::ModelObject
{
public:
    /**
    * @brief default constructor.
    **/
	AB_session_EXPORT  GameSession() = default;
	
    /**
    * @brief destructor.
    **/
    AB_session_EXPORT virtual ~GameSession() = default;
	
	/**
    * @brief Return the object unique id (used for serialization)
    **/
    AB_session_EXPORT virtual const String& model_id() const override;
	
	/**
    * @brief Return the unique id that can be used to determine this class (used for serialization)
    **/
    AB_session_EXPORT static const String& model_object_id();
    
    // start of usefull parameters
	DSInfo ds_information{};
	accelbyte::Optional<accelbyte::utils::JsonObjectString> attributes{};
	accelbyte::String backfill_ticket_id{};
	accelbyte::Optional<accelbyte::String> code{};
	ConfigInfo configuration{};
	accelbyte::String created_at{};
	accelbyte::String created_by{};
	accelbyte::Optional<accelbyte::String> expired_at{};
	accelbyte::String id{};
	bool is_active{false};
	bool is_full{false};
	accelbyte::String leader_id{};
	accelbyte::String match_pool{};
	accelbyte::Vector<User> members{};
	accelbyte::String ab_namespace{};
	accelbyte::Optional<accelbyte::utils::JsonObjectString> storage{};
	accelbyte::Optional<accelbyte::Vector<Team>> teams{};
	accelbyte::Optional<accelbyte::Vector<accelbyte::String>> ticket_ids{};
	accelbyte::String updated_at{};
	int version{0};
};

}
}
}