// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/http/SendableObject.h"
#include "accelbyte/common/DateTime.h"
#include "accelbyte/utils/JsonObjectString.h"
#include "accelbyte/common/Optional.h"
#include "accelbyte/iam/iam_export.h"

#include "accelbyte/common/String.h"
#include "accelbyte/common/Map.h"
#include "accelbyte/common/Vector.h"

#include "accelbyte/iam/models/RoleOverrideUpdateRequest.h"

namespace accelbyte {
namespace iam {
namespace override_role_config_v3 {

/**
* @brief This API is for updating role override config.
Note:
This API has upsert behavior, if there is no config yet, it will create a new one first.

*/
class AdminUpdateRoleOverrideConfigV3 : public accelbyte::http::SendableObject
{
public:
    
    enum class Identity : uint32_t {
        UNKNOWN,
        GAME_ADMIN,
        USER,
        VIEW_ONLY
    };
    
    /**
    * @brief default constructor.
    **/
	AB_iam_EXPORT AdminUpdateRoleOverrideConfigV3() = default;
	
    /**
    * @brief destrutor.
    **/
    AB_iam_EXPORT virtual ~AdminUpdateRoleOverrideConfigV3() = default;
	
	/**
    * @brief Return the object unique id (used for serialization)
    **/
    AB_iam_EXPORT const String& sendable_id() const override;
	
	/**
    * @brief Return the unique id that can be used to determine this class (used for serialization)
    **/
    AB_iam_EXPORT static const String& sendable_object_id();
	
    // usefull parameters    
     /**
     * @brief None
    **/
    model::RoleOverrideUpdateRequest body{};
     /**
     * @brief Namespace, only accept alphabet and numeric
if not set the user namespace will be used.
    **/
    accelbyte::Optional<accelbyte::String> ab_namespace{};
     /**
     * @brief Role identity
    **/
    Identity identity{Identity::USER};
};

}
}
}