// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/turn_manager/turn_manager_export.h"
#include "accelbyte/turn_manager/turn_server/GetServers.h"
#include "accelbyte/turn_manager/turn_server/GenerateUsernamePassword.h"
#include "accelbyte/turn_manager/models/AutoScaleConfig.h"
#include "accelbyte/turn_manager/models/AutoScaleConfigs.h"
#include "accelbyte/turn_manager/models/AutoScaleConfigUpdateRequest.h"
#include "accelbyte/turn_manager/models/CreateClusterRequest.h"
#include "accelbyte/turn_manager/models/CurrentTime.h"
#include "accelbyte/turn_manager/models/HeartbeatRequest.h"
#include "accelbyte/turn_manager/models/Servers.h"
#include "accelbyte/turn_manager/models/MemUsage.h"
#include "accelbyte/turn_manager/models/NetUsage.h"
#include "accelbyte/turn_manager/models/P2PConnectedRequest.h"
#include "accelbyte/turn_manager/models/P2PDisconnectedRequest.h"
#include "accelbyte/turn_manager/models/P2PTestItem.h"
#include "accelbyte/turn_manager/models/P2PTest.h"
#include "accelbyte/turn_manager/models/SecretRequest.h"
#include "accelbyte/turn_manager/models/Secret.h"
#include "accelbyte/turn_manager/models/Server.h"
#include "accelbyte/turn_manager/models/SetAliasRequest.h"
#include "accelbyte/turn_manager/models/Error.h"
#include "accelbyte/common/Error.h"
#include "accelbyte/tls/SecurityAuthorization.h"

#include <functional>
#include "accelbyte/memory/memory.h"

namespace accelbyte {
namespace turn_manager {

class TurnServer
{
public:	
    /**
    * @brief Get list of TURN services
    * @details ```
This endpoint lists all TURN server available in all regions.

This endpoint is intended to be called by game client to find out all available TURN server.
After getting a list of TURN server on each region, game client is expected to ping each one with UDP
connection as described below:

1. Make UDP connection to each TURN IP:Port
2. Send string &#34;PING&#34; after connection established
3. Wait for string &#34;PONG&#34; response
4. Note the request-response latency for each TURN in each region

The game then can use ping latency information to either:
1. Inform the player on these latencies and let player choose preferred region
2. Send the latency list to Matchmaking Service so that player can be matched with other players
in nearby regions
```
    * @details /turnmanager/turn
    *
    */
    AB_turn_manager_EXPORT static void get_servers(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const turn_server::GetServers& request, 
        const std::function<void(const model::Servers&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Get generated username password
    * @details ```
This endpoint get generated username and password to authenticate with turn service.
```
    * @details /turnmanager/turn/secret/{region}/{ip}/{port}
    *
    */
    AB_turn_manager_EXPORT static void generate_username_password(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const turn_server::GenerateUsernamePassword& request, 
        const std::function<void(const model::Secret&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

};

}
}