// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/http/SendableObject.h"
#include "accelbyte/common/DateTime.h"
#include "accelbyte/utils/JsonObjectString.h"
#include "accelbyte/common/Optional.h"
#include "accelbyte/login_queue/login_queue_export.h"

#include "accelbyte/common/String.h"
#include "accelbyte/common/Map.h"
#include "accelbyte/common/Vector.h"


namespace accelbyte {
namespace login_queue {
namespace ticket_v1 {

/**
* @brief Refresh ticket. This endpoint requires ticket to be placed in the authorization header with this format: &#34;Bearer ticketID&#34;. When the ticketID is empty or not found the response status will be 401
*/
class RefreshTicket : public accelbyte::http::SendableObject
{
public:
    
    
    /**
    * @brief default constructor.
    **/
	AB_login_queue_EXPORT RefreshTicket() = default;
	
    /**
    * @brief destrutor.
    **/
    AB_login_queue_EXPORT virtual ~RefreshTicket() = default;
	
	/**
    * @brief Return the object unique id (used for serialization)
    **/
    AB_login_queue_EXPORT const String& sendable_id() const override;
	
	/**
    * @brief Return the unique id that can be used to determine this class (used for serialization)
    **/
    AB_login_queue_EXPORT static const String& sendable_object_id();
	
    // usefull parameters    
     /**
     * @brief namespace of the game
if not set the user namespace will be used.
    **/
    accelbyte::Optional<accelbyte::String> ab_namespace{};
};

}
}
}