// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/http/SendableObject.h"
#include "accelbyte/common/DateTime.h"
#include "accelbyte/utils/JsonObjectString.h"
#include "accelbyte/common/Optional.h"
#include "accelbyte/iam/iam_export.h"

#include "accelbyte/common/String.h"
#include "accelbyte/common/Map.h"
#include "accelbyte/common/Vector.h"


namespace accelbyte {
namespace iam {
namespace sso_saml_2_0 {

/**
* @brief This endpoint authenticates user platform for SAML protocol. It validates user to its
respective platforms. Deactivated or login-banned users are unable to login.
## Supported platforms:
- **azure**
	Microsoft login page will redirects to this endpoint after login success
as previously defined on authentication request SAML
*/
class AuthenticatePlatformSAMLV3 : public accelbyte::http::SendableObject
{
public:
    
    
    /**
    * @brief default constructor.
    **/
	AB_iam_EXPORT AuthenticatePlatformSAMLV3() = default;
	
    /**
    * @brief destrutor.
    **/
    AB_iam_EXPORT virtual ~AuthenticatePlatformSAMLV3() = default;
	
	/**
    * @brief Return the object unique id (used for serialization)
    **/
    AB_iam_EXPORT const String& sendable_id() const override;
	
	/**
    * @brief Return the unique id that can be used to determine this class (used for serialization)
    **/
    AB_iam_EXPORT static const String& sendable_object_id();
	
    // usefull parameters    
     /**
     * @brief Platform ID
    **/
    accelbyte::String platform_id{};
     /**
     * @brief State that contains request ID retrieved from authorize endpoint ([GET] iam/v3/oauth/authorize)
    **/
    accelbyte::String state{};
     /**
     * @brief The authorization code from 3rd party OAuth server
    **/
    accelbyte::Optional<accelbyte::String> code{};
     /**
     * @brief The error message from Identity Provider (IdP)
    **/
    accelbyte::Optional<accelbyte::String> error{};
};

}
}
}