// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/http/SendableObject.h"
#include "accelbyte/common/DateTime.h"
#include "accelbyte/utils/JsonObjectString.h"
#include "accelbyte/common/Optional.h"
#include "accelbyte/iam/iam_export.h"

#include "accelbyte/common/String.h"
#include "accelbyte/common/Map.h"
#include "accelbyte/common/Vector.h"


namespace accelbyte {
namespace iam {
namespace o_auth2_0 {

/**
* @brief Initializes OAuth2.0 authorization code flow
The endpoint stores authorization request and redirects to login page with the authorization request id.
The user can then do the authentication on the login page. 
The user will be redirected back to the requesting client with authorization code if successfully authenticated. 

Only authorization code flow supported by this endpoint, implicit flow is not supported.
- **Authorize success**: 
	redirects to login page with the following information: ?request_id={authorization_request_id}
- **Authorize failure**: 
	redirects to the given redirect uri with the following information:
	?error={error_code}&amp;error_description={error description}				

For Public Client case, it&#39;s mandatory to fill **code_challenge** to avoid authorization code interception attack.
Please refer to the RFC for more information about Proof Key for Code Exchange(PKCE): https://datatracker.ietf.org/doc/html/rfc7636 

Following are the error code based on the specification:
- invalid_request: The request is missing a required parameter, 
	includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.
- server_error: 
	The authorization server encountered an unexpected condition that prevented it from fulfilling the request.
- unauthorized_client: The client is not authorized to request a token using this method.
- access_denied: The resource owner or authorization server denied the request.
- invalid_scope: The requested scope is invalid, unknown, or malformed.
- unsupported_response_type: The authorization server does not support obtaining a token using this method.
- temporarily_unavailable: The authorization server is currently unable to handle the request 
	due to a temporary overloading or maintenance of the server.
Please refer to the RFC for more information about authorization code flow: https://tools.ietf.org/html/rfc6749#section-4.1
action code: 10701
*/
class AuthorizeV3 : public accelbyte::http::SendableObject
{
public:
    
    enum class ResponseType : uint32_t {
        UNKNOWN,
        CODE
    };
    enum class CodeChallengeMethod : uint32_t {
        UNKNOWN,
        S256,
        PLAIN
    };
    
    /**
    * @brief default constructor.
    **/
	AB_iam_EXPORT AuthorizeV3() = default;
	
    /**
    * @brief destrutor.
    **/
    AB_iam_EXPORT virtual ~AuthorizeV3() = default;
	
	/**
    * @brief Return the object unique id (used for serialization)
    **/
    AB_iam_EXPORT const String& sendable_id() const override;
	
	/**
    * @brief Return the unique id that can be used to determine this class (used for serialization)
    **/
    AB_iam_EXPORT static const String& sendable_object_id();
	
    // usefull parameters    
     /**
     * @brief Registered client ID
    **/
    accelbyte::String client_id{};
     /**
     * @brief Supported response type : 'code'
    **/
    ResponseType response_type{ResponseType::CODE};
     /**
     * @brief Value generated by transforming code verifier using code challenge method. Mandatory for public client.
    **/
    accelbyte::Optional<accelbyte::String> code_challenge{};
     /**
     * @brief Method that is used to transform code verifier to code challenge
    **/
    accelbyte::Optional<CodeChallengeMethod> code_challenge_method{};
     /**
     * @brief If create new headless account when login by new third platform user
    **/
    accelbyte::Optional<bool> create_headless{};
     /**
     * @brief One time link code for headless account to link. Can get from [/iam/v3/link/code/request]
    **/
    accelbyte::Optional<accelbyte::String> one_time_link_code{};
     /**
     * @brief Redirect URI registered for requesting client. Required if client registered with multiple redirect URI. Registered redirect uri will be assigned if left empty.
    **/
    accelbyte::Optional<accelbyte::String> redirect_uri{};
     /**
     * @brief Defines the requested access request scope. Can be multiple values delimited by whitespace.
    **/
    accelbyte::Optional<accelbyte::String> scope{};
     /**
     * @brief Random value for preventing cross-site request forgery used by client.
    **/
    accelbyte::Optional<accelbyte::String> state{};
     /**
     * @brief Custom query to tell authorization web which page to present to user
    **/
    accelbyte::Optional<accelbyte::String> target_auth_page{};
     /**
     * @brief Use Redirect URI as the Login URL after resetting password when got locked
    **/
    accelbyte::Optional<bool> use_redirect_uri_as_login_url_when_locked{};
};

}
}
}