// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/http/SendableObject.h"
#include "accelbyte/common/DateTime.h"
#include "accelbyte/utils/JsonObjectString.h"
#include "accelbyte/common/Optional.h"
#include "accelbyte/achievement/achievement_export.h"

#include "accelbyte/common/String.h"
#include "accelbyte/common/Map.h"
#include "accelbyte/common/Vector.h"


namespace accelbyte {
namespace achievement {
namespace user_achievements {

/**
* @brief &lt;p&gt;Required permission 
			&lt;code&gt;ADMIN:NAMESPACE:{namespace}:USER:{userId}:ACHIEVEMENT [READ]&lt;/code&gt; and scope &lt;code&gt;social&lt;/code&gt;&lt;/p&gt;
			&lt;p&gt;Note:&lt;/p&gt;
			&lt;p&gt; User Achievement status value mean: &lt;code&gt;status = 1 (in progress)&lt;/code&gt; and &lt;code&gt;status = 2 (unlocked)&lt;/code&gt;&lt;/p&gt;
			&lt;p&gt; &lt;code&gt;achievedAt&lt;/code&gt; value will return default value: &lt;code&gt;0001-01-01T00:00:00Z&lt;/code&gt; for user achievement that locked or in progress&lt;/p&gt;
*/
class AdminGetUserAchievements : public accelbyte::http::SendableObject
{
public:
    
    
    /**
    * @brief default constructor.
    **/
	AB_achievement_EXPORT AdminGetUserAchievements() = default;
	
    /**
    * @brief destrutor.
    **/
    AB_achievement_EXPORT virtual ~AdminGetUserAchievements() = default;
	
	/**
    * @brief Return the object unique id (used for serialization)
    **/
    AB_achievement_EXPORT const String& sendable_id() const override;
	
	/**
    * @brief Return the unique id that can be used to determine this class (used for serialization)
    **/
    AB_achievement_EXPORT static const String& sendable_object_id();
	
    // usefull parameters    
     /**
     * @brief namespace of the game
if not set the user namespace will be used.
    **/
    accelbyte::Optional<accelbyte::String> ab_namespace{};
     /**
     * @brief user id
    **/
    accelbyte::String user_id{};
     /**
     * @brief the maximum number of data that may be returned (1...100)
    **/
    accelbyte::Optional<long> limit{};
     /**
     * @brief offset
    **/
    accelbyte::Optional<long> offset{};
     /**
     * @brief prefer to query achieved
    **/
    accelbyte::Optional<bool> prefer_unlocked{};
     /**
     * @brief sort by, allow values: [achievedAt, achievedAt:asc, achievedAt:desc, createdAt, createdAt:asc, createdAt:desc]
    **/
    accelbyte::Optional<accelbyte::String> sort_by{};
     /**
     * @brief tags
    **/
    accelbyte::Optional<accelbyte::Vector<accelbyte::String>> tags{};
};

}
}
}