// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/http/SendableObject.h"
#include "accelbyte/common/DateTime.h"
#include "accelbyte/utils/JsonObjectString.h"
#include "accelbyte/common/Optional.h"
#include "accelbyte/lobby/lobby_export.h"

#include "accelbyte/common/String.h"
#include "accelbyte/common/Map.h"
#include "accelbyte/common/Vector.h"

#include "accelbyte/lobby/models/UpdateTemplateRequest.h"

namespace accelbyte {
namespace lobby {
namespace notification {

/**
* @brief Update template localization&lt;br/&gt;
			Action Code: 50208
*/
class AdminUpdateTemplateLocalizationV1 : public accelbyte::http::SendableObject
{
public:
    
    
    /**
    * @brief default constructor.
    **/
	AB_lobby_EXPORT AdminUpdateTemplateLocalizationV1() = default;
	
    /**
    * @brief destrutor.
    **/
    AB_lobby_EXPORT virtual ~AdminUpdateTemplateLocalizationV1() = default;
	
	/**
    * @brief Return the object unique id (used for serialization)
    **/
    AB_lobby_EXPORT const String& sendable_id() const override;
	
	/**
    * @brief Return the unique id that can be used to determine this class (used for serialization)
    **/
    AB_lobby_EXPORT static const String& sendable_object_id();
	
    // usefull parameters    
     /**
     * @brief None
    **/
    model::UpdateTemplateRequest body{};
     /**
     * @brief namespace
if not set the user namespace will be used.
    **/
    accelbyte::Optional<accelbyte::String> ab_namespace{};
     /**
     * @brief template language, follows IETF BCP 47 standard
    **/
    accelbyte::String template_language{};
     /**
     * @brief Template Identifier, only alphabet characters and hyphens are permitted
    **/
    accelbyte::String template_slug{};
};

}
}
}