// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/lobby/lobby_export.h"
#include "accelbyte/lobby/blocks/SyncNativeBlockedUser.h"
#include "accelbyte/lobby/models/GetUsersPresenceResponse.h"
#include "accelbyte/lobby/models/UserPresence.h"
#include "accelbyte/lobby/models/LogAppMessageDeclaration.h"
#include "accelbyte/lobby/models/LogconfigConfiguration.h"
#include "accelbyte/lobby/models/FriendsRequest.h"
#include "accelbyte/lobby/models/FriendsResponse.h"
#include "accelbyte/lobby/models/c2b70d9d85f49a4ationRequestsV1.h"
#include "accelbyte/lobby/models/CreateTemplateRequest.h"
#include "accelbyte/lobby/models/CreateTopicRequest.h"
#include "accelbyte/lobby/models/CreateTopicRequestV1.h"
#include "accelbyte/lobby/models/FreeFormNotificationRequest.h"
#include "accelbyte/lobby/models/FreeFormNotificationRequestV1.h"
#include "accelbyte/lobby/models/FriendPlatform.h"
#include "accelbyte/lobby/models/FriendshipConnection.h"
#include "accelbyte/lobby/models/FriendshipConnectionResponse.h"
#include "accelbyte/lobby/models/3b193f05f7474b9ateSlugResponse.h"
#include "accelbyte/lobby/models/ef336add07ca463nTopicsResponse.h"
#include "accelbyte/lobby/models/GetFriendsResponse.h"
#include "accelbyte/lobby/models/GetUserFriendsResponse.h"
#include "accelbyte/lobby/models/GetUserIncomingFriendsResponse.h"
#include "accelbyte/lobby/models/GetUserOutgoingFriendsResponse.h"
#include "accelbyte/lobby/models/GlobalConfiguration.h"
#include "accelbyte/lobby/models/IncomingFriendsTimeData.h"
#include "accelbyte/lobby/models/GetUserPlatformsResponse.h"
#include "accelbyte/lobby/models/GetIncomingFriendsTimeResponse.h"
#include "accelbyte/lobby/models/GetOutgoingFriendsTimeResponse.h"
#include "accelbyte/lobby/models/Localization.h"
#include "accelbyte/lobby/models/NativeFriendRequest.h"
#include "accelbyte/lobby/models/NativeFriendSyncResponse.h"
#include "accelbyte/lobby/models/NativeUserBlockRequest.h"
#include "accelbyte/lobby/models/NativeUserBlockResponse.h"
#include "accelbyte/lobby/models/NotificationResponse.h"
#include "accelbyte/lobby/models/NotificationTemplateResponse.h"
#include "accelbyte/lobby/models/NotificationTopicResponse.h"
#include "accelbyte/lobby/models/NotificationTopicResponseV1.h"
#include "accelbyte/lobby/models/NotificationTemplateRequest.h"
#include "accelbyte/lobby/models/NotificationTemplateRequestV1.h"
#include "accelbyte/lobby/models/OutgoingFriendsTimeData.h"
#include "accelbyte/lobby/models/Pagination.h"
#include "accelbyte/lobby/models/0bb3f99dc8aa973gurationRequest.h"
#include "accelbyte/lobby/models/UserPresenceRequest.h"
#include "accelbyte/lobby/models/TemplateContent.h"
#include "accelbyte/lobby/models/TemplateLocalization.h"
#include "accelbyte/lobby/models/TemplateLocalizationResponse.h"
#include "accelbyte/lobby/models/TemplateResponse.h"
#include "accelbyte/lobby/models/TopicByNamespacesResponse.h"
#include "accelbyte/lobby/models/UpdateTemplateRequest.h"
#include "accelbyte/lobby/models/UpdateTopicRequest.h"
#include "accelbyte/lobby/models/UserAcceptFriendRequest.h"
#include "accelbyte/lobby/models/UserCancelFriendRequest.h"
#include "accelbyte/lobby/models/b23fd17b4038e3epStatusResponse.h"
#include "accelbyte/lobby/models/UserPlatformInfo.h"
#include "accelbyte/lobby/models/UserRejectFriendRequest.h"
#include "accelbyte/lobby/models/UserRequestFriendRequest.h"
#include "accelbyte/lobby/models/UserUnfriendRequest.h"
#include "accelbyte/lobby/models/UserWithPlatformInfo.h"
#include "accelbyte/lobby/models/f4fc3752ba7333clterIntoRequest.h"
#include "accelbyte/lobby/models/7002fa4fda2965drsFilterRequest.h"
#include "accelbyte/lobby/models/a9abc88a727e26byFiltersRequest.h"
#include "accelbyte/lobby/models/AdminCreateProfanitiesRequest.h"
#include "accelbyte/lobby/models/4a611538252f0d9tyFilterRequest.h"
#include "accelbyte/lobby/models/51bbeb84f58c376tersV1sResponse.h"
#include "accelbyte/lobby/models/AdminGetProfanityListsResponse.h"
#include "accelbyte/lobby/models/e18d53ba59ded9camespaceRequest.h"
#include "accelbyte/lobby/models/AdminUpdateProfanitiesRequest.h"
#include "accelbyte/lobby/models/12635663bc31134rofanityRequest.h"
#include "accelbyte/lobby/models/d0b9993386a9f0cofanityResponse.h"
#include "accelbyte/lobby/models/BlockPlayerRequest.h"
#include "accelbyte/lobby/models/BlockedByPlayerData.h"
#include "accelbyte/lobby/models/BlockedPlayerData.h"
#include "accelbyte/lobby/models/Config.h"
#include "accelbyte/lobby/models/Configs.h"
#include "accelbyte/lobby/models/ConfigRequest.h"
#include "accelbyte/lobby/models/CreateConfigRequest.h"
#include "accelbyte/lobby/models/CreateConfigResponse.h"
#include "accelbyte/lobby/models/DebugProfanityFilterRequest.h"
#include "accelbyte/lobby/models/ea2eda43d746c0fByUsersResponse.h"
#include "accelbyte/lobby/models/dae57f32ea35d6dedUsersResponse.h"
#include "accelbyte/lobby/models/548277b7295028btributeResponse.h"
#include "accelbyte/lobby/models/366fa7774590e18kedUsersRequest.h"
#include "accelbyte/lobby/models/ad42624d4d7c4fbedUsersResponse.h"
#include "accelbyte/lobby/models/GetConfigResponse.h"
#include "accelbyte/lobby/models/GetLobbyCcuResponse.h"
#include "accelbyte/lobby/models/a9963b269f8497etributeResponse.h"
#include "accelbyte/lobby/models/ImportConfigResponse.h"
#include "accelbyte/lobby/models/GetBlockedPlayersRequest.h"
#include "accelbyte/lobby/models/GetUnblockPlayersRequest.h"
#include "accelbyte/lobby/models/PartyData.h"
#include "accelbyte/lobby/models/4e0f5545a0476d6tributesRequest.h"
#include "accelbyte/lobby/models/PartyUpdateLimitSizeRequest.h"
#include "accelbyte/lobby/models/ProfanityFilter.h"
#include "accelbyte/lobby/models/ProfanityRule.h"
#include "accelbyte/lobby/models/beb37e36d881954ttributeRequest.h"
#include "accelbyte/lobby/models/UnblockPlayerRequest.h"
#include "accelbyte/lobby/models/UpdateConfigRequest.h"
#include "accelbyte/lobby/models/UpdateConfigResponse.h"
#include "accelbyte/lobby/models/ErrorResponse.h"
#include "accelbyte/lobby/models/ErrorResponseBody.h"
#include "accelbyte/lobby/models/ErrorResponseV1.h"
#include "accelbyte/common/Error.h"
#include "accelbyte/tls/SecurityAuthorization.h"

#include <functional>
#include "accelbyte/memory/memory.h"

namespace accelbyte {
namespace lobby {

class Blocks
{
public:	
    /**
    * @brief sync blocked user using server to server call to native first party server.
    * @details Sync blocked user using server to server call to native first party server.
				Supported platforms:
				ps5, ps4 and pspc : the default environment would be sp-int, can be override using psnEnv. 
				psnEnv consist of sp-int (default), prod-qa, np
				
    * @details /lobby/sync/namespaces/{namespace}/me/block
    *
    */
    AB_lobby_EXPORT static void sync_native_blocked_user(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const blocks::SyncNativeBlockedUser& request, 
        const std::function<void(const accelbyte::Vector<model::NativeUserBlockResponse>&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

};

}
}