// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/lobby/lobby_export.h"
#include "accelbyte/common/String.h"
#include "accelbyte/common/Map.h"
#include "accelbyte/memory/memory.h"

namespace accelbyte {
namespace lobby {

class LobbyRequestFactory;

class LobbyService
{
public:	
    AB_lobby_EXPORT static void initialize(const String& base_url, const String& version = "0.0.0", bool warning_as_error = false, bool log_usage = false);
    AB_lobby_EXPORT static bool initialized();
    AB_lobby_EXPORT static const Map<String,String>& used_endpoints();
    AB_lobby_EXPORT static const Map<String,String>& unused_endpoints();
    
private:
    static bool initialized_;
    static accelbyte::memory::SharedPtr<LobbyRequestFactory> request_factory_;
};

}
}