// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/http/SendableObject.h"
#include "accelbyte/common/DateTime.h"
#include "accelbyte/utils/JsonObjectString.h"
#include "accelbyte/common/Optional.h"
#include "accelbyte/iam/iam_export.h"

#include "accelbyte/common/String.h"
#include "accelbyte/common/Map.h"
#include "accelbyte/common/Vector.h"


namespace accelbyte {
namespace iam {
namespace roles {

/**
* @brief Admin roles has its members listed in the role.
action code: 10416
*/
class AdminGetRoleMembersV3 : public accelbyte::http::SendableObject
{
public:
    
    
    /**
    * @brief default constructor.
    **/
	AB_iam_EXPORT AdminGetRoleMembersV3() = default;
	
    /**
    * @brief destrutor.
    **/
    AB_iam_EXPORT virtual ~AdminGetRoleMembersV3() = default;
	
	/**
    * @brief Return the object unique id (used for serialization)
    **/
    AB_iam_EXPORT const String& sendable_id() const override;
	
	/**
    * @brief Return the unique id that can be used to determine this class (used for serialization)
    **/
    AB_iam_EXPORT static const String& sendable_object_id();
	
    // usefull parameters    
     /**
     * @brief Role ID, should follow UUID version 4 without hyphen
    **/
    accelbyte::String role_id{};
     /**
     * @brief The cursor that points to query data for the next page
    **/
    accelbyte::Optional<accelbyte::String> after{};
     /**
     * @brief The cursor that points to query data for the previous page
    **/
    accelbyte::Optional<accelbyte::String> before{};
     /**
     * @brief the maximum number of data that may be returned (1...100)
    **/
    accelbyte::Optional<long> limit{};
};

}
}
}