// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/match2/match2_export.h"
#include "accelbyte/match2/match_pools/GetMatchPools.h"
#include "accelbyte/match2/match_pools/CreateMatchPool.h"
#include "accelbyte/match2/match_pools/DeleteMatchPool.h"
#include "accelbyte/match2/match_pools/GetMatchPoolDetails.h"
#include "accelbyte/match2/match_pools/UpdateMatchPool.h"
#include "accelbyte/match2/match_pools/GetMatchPoolMetric.h"
#include "accelbyte/match2/match_pools/GetPlayerMetric.h"
#include "accelbyte/match2/match_pools/AdminGetMatchPoolTickets.h"
#include "accelbyte/match2/match_pools/GetUserPlayerMetric.h"
#include "accelbyte/match2/models/BackFillAcceptRequest.h"
#include "accelbyte/match2/models/BackFillCreateRequest.h"
#include "accelbyte/match2/models/BackfillCreateResponse.h"
#include "accelbyte/match2/models/Backfill.h"
#include "accelbyte/match2/models/BackfillProposal.h"
#include "accelbyte/match2/models/EnvironmentVariables.h"
#include "accelbyte/match2/models/MatchFunctions.h"
#include "accelbyte/match2/models/MatchPoolTickets.h"
#include "accelbyte/match2/models/MatchPools.h"
#include "accelbyte/match2/models/RuleSets.h"
#include "accelbyte/match2/models/Match.h"
#include "accelbyte/match2/models/MatchFunctionConfig.h"
#include "accelbyte/match2/models/MatchFunctionOverride.h"
#include "accelbyte/match2/models/MatchFunctionRequest.h"
#include "accelbyte/match2/models/MatchPool.h"
#include "accelbyte/match2/models/MatchPoolConfig.h"
#include "accelbyte/match2/models/MatchRuleSetNameData.h"
#include "accelbyte/match2/models/MatchTicketRequest.h"
#include "accelbyte/match2/models/MatchTicket.h"
#include "accelbyte/match2/models/MatchTicketStatus.h"
#include "accelbyte/match2/models/MatchTicketStatuses.h"
#include "accelbyte/match2/models/NamespaceConfigs.h"
#include "accelbyte/match2/models/Party.h"
#include "accelbyte/match2/models/PatchNamespaceConfigRequest.h"
#include "accelbyte/match2/models/PlayerData.h"
#include "accelbyte/match2/models/PlayerMetricRecord.h"
#include "accelbyte/match2/models/ProposedProposal.h"
#include "accelbyte/match2/models/RuleSetPayload.h"
#include "accelbyte/match2/models/Team.h"
#include "accelbyte/match2/models/Ticket.h"
#include "accelbyte/match2/models/TicketMetricResultRecord.h"
#include "accelbyte/match2/models/BackFillRejectRequest.h"
#include "accelbyte/match2/models/ConfigEnvironmentVariable.h"
#include "accelbyte/match2/models/ConfigmodelsNamespaceConfig.h"
#include "accelbyte/match2/models/LogconfigConfiguration.h"
#include "accelbyte/match2/models/MatchmakerMatchTicketRecord.h"
#include "accelbyte/match2/models/MatchmakerParty.h"
#include "accelbyte/match2/models/MatchmakerProposedProposal.h"
#include "accelbyte/match2/models/MatchmakerTeam.h"
#include "accelbyte/match2/models/MatchmakerTicket.h"
#include "accelbyte/match2/models/Configuration.h"
#include "accelbyte/match2/models/DSInfo.h"
#include "accelbyte/match2/models/GameSession.h"
#include "accelbyte/match2/models/Pagination.h"
#include "accelbyte/match2/models/Server.h"
#include "accelbyte/match2/models/User.h"
#include "accelbyte/match2/models/PlayerPlayerData.h"
#include "accelbyte/match2/models/Error.h"
#include "accelbyte/common/Error.h"
#include "accelbyte/tls/SecurityAuthorization.h"

#include <functional>
#include "accelbyte/memory/memory.h"

namespace accelbyte {
namespace match2 {

class MatchPools
{
public:	
    /**
    * @brief List match pools
    * @details List matchmaking pools.

    * @details /match2/v1/namespaces/{namespace}/match-pools
    *
    */
    AB_match2_EXPORT static void get_match_pools(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const match_pools::GetMatchPools& request, 
        const std::function<void(const model::MatchPools&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Create a match pool
    * @details Creates a new matchmaking pool.

A pool is isolated from other pools (i.e. tickets may be matched with other tickets in the same pool, but not with tickets in other pools).
Each pool has its own matchmaking rules and/or logic.

ticket_expiration_seconds and backfill_ticket_expiration_seconds will be set to 300 seconds (5 minutes) by default if not filled.

Match Function holds information about the name of the match logic server that matchmaking can refers to. By default we provide (&#34;default&#34; and &#34;basic&#34;). 
Match Function will be used as reference value for Match Function Overrides if not set.
In case Customer would like to use matchmaking service default match logic, then specify it in &#34;match_function_overrides&#34;.				
This sample configuration will let matchmaking service will use &#34;default&#34; match logic for make matches, while validation will hit both &#34;default&#34; and &#34;custom&#34; match logics.
e.g.
{ 
              &#34;match_function&#34;: &#34;custom&#34;,
  &#34;match_function_overrides&#34;: {
    &#34;validation&#34;: []{&#34;default&#34;,&#34;custom&#34;},
                &#34;make_matches&#34;: &#34;default&#34;,
              }
}

    * @details /match2/v1/namespaces/{namespace}/match-pools
    *
    */
    AB_match2_EXPORT static void create_match_pool(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const match_pools::CreateMatchPool& request, 
        const std::function<void()>& on_201,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Delete a match pool
    * @details Deletes an existing matchmaking pool.

    * @details /match2/v1/namespaces/{namespace}/match-pools/{pool}
    *
    */
    AB_match2_EXPORT static void delete_match_pool(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const match_pools::DeleteMatchPool& request, 
        const std::function<void()>& on_204,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Get details for a specific match pool
    * @details Get details for a specific match pool

    * @details /match2/v1/namespaces/{namespace}/match-pools/{pool}
    *
    */
    AB_match2_EXPORT static void get_match_pool_details(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const match_pools::GetMatchPoolDetails& request, 
        const std::function<void(const model::MatchPool&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Update a match pool
    * @details Updates an existing matchmaking pool.

ticket_expiration_seconds and backfill_ticket_expiration_seconds will be set to 300 seconds (5 minutes) by default if not filled.

Match Function holds information about the name of the match logic server that matchmaking can refers to. By default we provide (&#34;default&#34; and &#34;basic&#34;). 
Match Function will be used as reference value for Match Function Overrides if not set.
In case Customer would like to use matchmaking service default match logic, then specify it in &#34;match_function_overrides&#34;.				
This sample configuration will let matchmaking service will use &#34;default&#34; match logic for make matches, while validation will hit both &#34;default&#34; and &#34;custom&#34; match logics.
e.g.
{
	&#34;match_function&#34;: &#34;custom&#34;,
	&#34;match_function_overrides&#34;: {
		&#34;validation&#34;: []{&#34;default&#34;,&#34;custom&#34;},
		&#34;make_matches&#34;: &#34;default&#34;,
	}
}

    * @details /match2/v1/namespaces/{namespace}/match-pools/{pool}
    *
    */
    AB_match2_EXPORT static void update_match_pool(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const match_pools::UpdateMatchPool& request, 
        const std::function<void(const model::MatchPool&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Get metrics for a specific match pool
    * @details Get metric for a specific match pool

Result: queueTime in seconds

    * @details /match2/v1/namespaces/{namespace}/match-pools/{pool}/metrics
    *
    */
    AB_match2_EXPORT static void get_match_pool_metric(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const match_pools::GetMatchPoolMetric& request, 
        const std::function<void(const model::TicketMetricResultRecord&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Get metrics player for a specific match pool
    * @details Get player metric for a specific match pool

    * @details /match2/v1/namespaces/{namespace}/match-pools/{pool}/metrics/player
    *
    */
    AB_match2_EXPORT static void get_player_metric(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const match_pools::GetPlayerMetric& request, 
        const std::function<void(const model::PlayerMetricRecord&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Get tickets in queue for a specific match pool
    * @details Get tickets in queue for a specific match pool

Result: number of tickets and list of ticket detail in a match pool.

    * @details /match2/v1/namespaces/{namespace}/match-pools/{pool}/tickets
    *
    */
    AB_match2_EXPORT static void admin_get_match_pool_tickets(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const match_pools::AdminGetMatchPoolTickets& request, 
        const std::function<void(const model::MatchPoolTickets&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Get metrics player for a specific match pool
    * @details Public get player metric for a specific match pool

    * @details /match2/v1/public/namespaces/{namespace}/match-pools/{pool}/metrics/player
    *
    */
    AB_match2_EXPORT static void get_user_player_metric(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const match_pools::GetUserPlayerMetric& request, 
        const std::function<void(const model::PlayerMetricRecord&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

};

}
}