// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/http/SendableObject.h"
#include "accelbyte/common/DateTime.h"
#include "accelbyte/utils/JsonObjectString.h"
#include "accelbyte/common/Optional.h"
#include "accelbyte/leaderboard/leaderboard_export.h"

#include "accelbyte/common/String.h"
#include "accelbyte/common/Map.h"
#include "accelbyte/common/Vector.h"

#include "accelbyte/leaderboard/models/65e7c78c62e7ad7ConfigRequestV3.h"

namespace accelbyte {
namespace leaderboard {
namespace leaderboard_configuration_v3 {

/**
* @brief &lt;p&gt;&lt;b&gt;Fields :&lt;/b&gt;&lt;/p&gt;
	&lt;ul&gt;&lt;li&gt;leaderboardCode: unique leaderboard config code must be lowercase and maximum length is 48 characters. &lt;b&gt;(required)&lt;/b&gt;.&lt;/li&gt;
		&lt;li&gt;name: leaderboard name, maximum length for leaderboard name is 128 characters. &lt;b&gt;(required)&lt;/b&gt;.&lt;/li&gt;
		&lt;li&gt;description: leaderboard description, maximum length for leaderboard description is 2048 characters. &lt;b&gt;(optional)&lt;/b&gt;.&lt;/li&gt;
		&lt;li&gt;iconURL: leaderboard icon image url. &lt;b&gt;(optional)&lt;/b&gt;.&lt;/li&gt;
		&lt;li&gt;allTime: if true, all time leaderboard will be created. &lt;b&gt;(required)&lt;/b&gt;.&lt;/li&gt;
		&lt;li&gt;descending: leaderboard order. If true, the points will be sorted in descending order. &lt;b&gt;(required)&lt;/b&gt;.&lt;/li&gt;
		&lt;li&gt;statCode: Stat Code is related with statistic code in statistic service. &lt;b&gt;(required)&lt;/b&gt;.&lt;/li&gt;
		&lt;li&gt;cycleIds: Statistic cycle ids that will be tracked in the leaderboard. &lt;b&gt;(required)&lt;/b&gt;.&lt;/li&gt;
	&lt;/ul&gt;
*/
class AdminUpdateLeaderboardConfigV3 : public accelbyte::http::SendableObject
{
public:
    
    
    /**
    * @brief default constructor.
    **/
	AB_leaderboard_EXPORT AdminUpdateLeaderboardConfigV3() = default;
	
    /**
    * @brief destrutor.
    **/
    AB_leaderboard_EXPORT virtual ~AdminUpdateLeaderboardConfigV3() = default;
	
	/**
    * @brief Return the object unique id (used for serialization)
    **/
    AB_leaderboard_EXPORT const String& sendable_id() const override;
	
	/**
    * @brief Return the unique id that can be used to determine this class (used for serialization)
    **/
    AB_leaderboard_EXPORT static const String& sendable_object_id();
	
    // usefull parameters    
     /**
     * @brief None
    **/
    model::UpdateLeaderboardConfigRequestV3 body{};
     /**
     * @brief  human readable unique code to indentify leaderboard. Must be lowercase and maximum length is 48
    **/
    accelbyte::String leaderboard_code{};
     /**
     * @brief namespace of the game
if not set the user namespace will be used.
    **/
    accelbyte::Optional<accelbyte::String> ab_namespace{};
};

}
}
}