// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/basic/basic_export.h"
#include "accelbyte/basic/misc/AdminGetCountries.h"
#include "accelbyte/basic/misc/AdminGetCountryGroups.h"
#include "accelbyte/basic/misc/AdminAddCountryGroup.h"
#include "accelbyte/basic/misc/AdminDeleteCountryGroup.h"
#include "accelbyte/basic/misc/AdminUpdateCountryGroup.h"
#include "accelbyte/basic/misc/AdminGetLanguages.h"
#include "accelbyte/basic/misc/AdminGetTimeZones.h"
#include "accelbyte/basic/misc/GetTime.h"
#include "accelbyte/basic/misc/GetCountries.h"
#include "accelbyte/basic/misc/GetLanguages.h"
#include "accelbyte/basic/misc/GetTimeZones.h"
#include "accelbyte/basic/models/AddCountryGroupRequest.h"
#include "accelbyte/basic/models/CountryGroup.h"
#include "accelbyte/basic/models/CreateConfig.h"
#include "accelbyte/basic/models/ConfigInfo.h"
#include "accelbyte/basic/models/UpdateConfig.h"
#include "accelbyte/basic/models/CountryGroupObject.h"
#include "accelbyte/basic/models/CountryObject.h"
#include "accelbyte/basic/models/ErrorEntity.h"
#include "accelbyte/basic/models/FieldValidationError.h"
#include "accelbyte/basic/models/FileUploadUrlInfo.h"
#include "accelbyte/basic/models/NamespaceContext.h"
#include "accelbyte/basic/models/CreateNamespace.h"
#include "accelbyte/basic/models/NamespaceInfo.h"
#include "accelbyte/basic/models/NamespacePublisherInfo.h"
#include "accelbyte/basic/models/NamespaceSimpleInfo.h"
#include "accelbyte/basic/models/UpdateNamespaceStatus.h"
#include "accelbyte/basic/models/UpdateNamespace.h"
#include "accelbyte/basic/models/Permission.h"
#include "accelbyte/basic/models/CountryGroup.h"
#include "accelbyte/basic/models/Time.h"
#include "accelbyte/basic/models/UpdateCountryGroupRequest.h"
#include "accelbyte/basic/models/AdminUserProfile.h"
#include "accelbyte/basic/models/UserProfilesRequest.h"
#include "accelbyte/basic/models/CreateUserProfile.h"
#include "accelbyte/basic/models/UserProfileInfo.h"
#include "accelbyte/basic/models/CreatePrivateUserProfile.h"
#include "accelbyte/basic/models/UserProfilePrivateInfo.h"
#include "accelbyte/basic/models/UserProfilePublicInfo.h"
#include "accelbyte/basic/models/UpdateUserProfileStatus.h"
#include "accelbyte/basic/models/UpdateUserProfile.h"
#include "accelbyte/basic/models/UserZipCode.h"
#include "accelbyte/basic/models/UpdateUserZipCode.h"
#include "accelbyte/basic/models/ValidationError.h"
#include "accelbyte/common/Error.h"
#include "accelbyte/tls/SecurityAuthorization.h"

#include <functional>
#include "accelbyte/memory/memory.h"

namespace accelbyte {
namespace basic {

class Misc
{
public:	
    /**
    * @brief List countries
    * @details List countries.&lt;br&gt;Other detail info: &lt;ul&gt;&lt;li&gt;&lt;i&gt;Action code&lt;/i&gt;: 11204&lt;/li&gt;&lt;li&gt;&lt;i&gt;Returns&lt;/i&gt;: country code list&lt;/li&gt;&lt;/ul&gt;
    * @details /basic/v1/admin/namespaces/{namespace}/misc/countries
    * @deprecated True
    *
    */
    AB_basic_EXPORT static void admin_get_countries(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const misc::AdminGetCountries& request, 
        const std::function<void(const accelbyte::Vector<model::CountryObject>&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief List country groups
    * @details List country groups. Will return all available country groups if the query param is not specified&lt;br&gt;Other detail info: &lt;ul&gt;&lt;li&gt;&lt;i&gt;Action code&lt;/i&gt;: 11203&lt;/li&gt;&lt;li&gt;&lt;i&gt;Returns&lt;/i&gt;: list of country groups&lt;/li&gt;&lt;/ul&gt;
    * @details /basic/v1/admin/namespaces/{namespace}/misc/countrygroups
    *
    */
    AB_basic_EXPORT static void admin_get_country_groups(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const misc::AdminGetCountryGroups& request, 
        const std::function<void(const accelbyte::Vector<model::CountryGroup>&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Add a country group
    * @details Add a country groups&lt;br&gt;Country code must follow ISO3166-1 alpha-2.&lt;br/&gt;Other detail info: &lt;ul&gt;&lt;li&gt;&lt;i&gt;Action code&lt;/i&gt;: 11201&lt;/li&gt;&lt;li&gt;&lt;i&gt;Returns&lt;/i&gt;: newly created country group&lt;/li&gt;&lt;/ul&gt;
    * @details /basic/v1/admin/namespaces/{namespace}/misc/countrygroups
    *
    */
    AB_basic_EXPORT static void admin_add_country_group(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const misc::AdminAddCountryGroup& request, 
        const std::function<void(const model::CountryGroup&)>& on_201,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Delete a country group
    * @details Delete a country groups by its country group code. This endpoint usually used for testing purpose to cleanup test data.&lt;br&gt;
    * @details /basic/v1/admin/namespaces/{namespace}/misc/countrygroups/{countryGroupCode}
    *
    */
    AB_basic_EXPORT static void admin_delete_country_group(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const misc::AdminDeleteCountryGroup& request, 
        const std::function<void()>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Update a country group
    * @details Update a country groups. The countryGroupCode must be exist beforehand.&lt;br&gt;Valid update behaviour :&lt;br/&gt;- To update &lt;i&gt;countryGroupName&lt;/i&gt; only, do not include &lt;i&gt;countries&lt;/i&gt; key or just specify it with empty array.&lt;br/&gt;- To update &lt;i&gt;countries&lt;/i&gt; only, do not include &lt;i&gt;countryGroupName&lt;/i&gt; key or just specify it with blank value.&lt;br/&gt;Other detail info: &lt;ul&gt;&lt;li&gt;&lt;i&gt;Action code&lt;/i&gt;: 11202&lt;/li&gt;&lt;li&gt;&lt;i&gt;Returns&lt;/i&gt;: updated country group&lt;/li&gt;&lt;/ul&gt;
    * @details /basic/v1/admin/namespaces/{namespace}/misc/countrygroups/{countryGroupCode}
    *
    */
    AB_basic_EXPORT static void admin_update_country_group(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const misc::AdminUpdateCountryGroup& request, 
        const std::function<void(const model::CountryGroupObject&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief List languages.
    * @details List languages.&lt;br&gt;Other detail info: &lt;ul&gt;&lt;li&gt;&lt;i&gt;Action code&lt;/i&gt;: 11206&lt;/li&gt;&lt;li&gt;&lt;i&gt;Returns&lt;/i&gt;: language list&lt;/li&gt;&lt;/ul&gt;
    * @details /basic/v1/admin/namespaces/{namespace}/misc/languages
    *
    */
    AB_basic_EXPORT static void admin_get_languages(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const misc::AdminGetLanguages& request, 
        const std::function<void(const accelbyte::Map<accelbyte::String,accelbyte::String>&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief List time zones
    * @details List time zones.&lt;br&gt;Other detail info: &lt;ul&gt;&lt;li&gt;&lt;i&gt;Action code&lt;/i&gt;: 11205&lt;/li&gt;&lt;li&gt;&lt;i&gt;Returns&lt;/i&gt;: time zones&lt;/li&gt;&lt;/ul&gt;
    * @details /basic/v1/admin/namespaces/{namespace}/misc/timezones
    *
    */
    AB_basic_EXPORT static void admin_get_time_zones(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const misc::AdminGetTimeZones& request, 
        const std::function<void(const accelbyte::Vector<accelbyte::String>&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Get server time
    * @details Get server time
    * @details /basic/v1/public/misc/time
    *
    */
    AB_basic_EXPORT static void get_time(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const misc::GetTime& request, 
        const std::function<void(const model::Time&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief List countries
    * @details List countries.&lt;br&gt;Other detail info: &lt;ul&gt;&lt;li&gt;&lt;i&gt;Returns&lt;/i&gt;: country code list&lt;/li&gt;&lt;/ul&gt;
    * @details /basic/v1/public/namespaces/{namespace}/misc/countries
    * @deprecated True
    *
    */
    AB_basic_EXPORT static void get_countries(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const misc::GetCountries& request, 
        const std::function<void(const accelbyte::Vector<model::CountryObject>&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief List languages.
    * @details List languages.&lt;br&gt;Other detail info: &lt;ul&gt;&lt;li&gt;&lt;i&gt;Returns&lt;/i&gt;: language list&lt;/li&gt;&lt;/ul&gt;
    * @details /basic/v1/public/namespaces/{namespace}/misc/languages
    *
    */
    AB_basic_EXPORT static void get_languages(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const misc::GetLanguages& request, 
        const std::function<void(const accelbyte::Map<accelbyte::String,accelbyte::utils::JsonObjectString>&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief List time zones
    * @details List time zones.&lt;br&gt;Other detail info: &lt;ul&gt;&lt;li&gt;&lt;i&gt;Returns&lt;/i&gt;: time zones&lt;/li&gt;&lt;/ul&gt;
    * @details /basic/v1/public/namespaces/{namespace}/misc/timezones
    *
    */
    AB_basic_EXPORT static void get_time_zones(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const misc::GetTimeZones& request, 
        const std::function<void(const accelbyte::Vector<accelbyte::String>&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

};

}
}