// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/http/ModelObject.h"
#include "accelbyte/common/Optional.h"
#include "accelbyte/common/String.h"
#include "accelbyte/common/Map.h"
#include "accelbyte/common/Vector.h"
#include "accelbyte/common/DateTime.h"
#include "accelbyte/memory/memory.h"
#include "accelbyte/utils/JsonObjectString.h"
#include "accelbyte/ugc/ugc_export.h"

#include "accelbyte/ugc/models/PayloadURL.h"
#include "accelbyte/ugc/models/PreviewURL.h"

namespace accelbyte {
namespace ugc {
namespace model {

class CreateContent : public accelbyte::http::ModelObject
{
public:
    enum class ContentStatus : uint32_t {
        UNKNOWN,
        PUBLISHED,
        UNDER_REVIEW
    };
    /**
    * @brief default constructor.
    **/
	AB_ugc_EXPORT  CreateContent() = default;
	
    /**
    * @brief destructor.
    **/
    AB_ugc_EXPORT virtual ~CreateContent() = default;
	
	/**
    * @brief Return the object unique id (used for serialization)
    **/
    AB_ugc_EXPORT virtual const String& model_id() const override;
	
	/**
    * @brief Return the unique id that can be used to determine this class (used for serialization)
    **/
    AB_ugc_EXPORT static const String& model_object_id();
    
    // start of usefull parameters
	accelbyte::String channel_id{};
	accelbyte::Optional<ContentStatus> content_status{};
	accelbyte::Optional<accelbyte::String> content_type{};
	accelbyte::String created_time{};
	accelbyte::String creator_name{};
	accelbyte::Optional<accelbyte::utils::JsonObjectString> custom_attributes{};
	accelbyte::String file_extension{};
	accelbyte::String id{};
	bool is_hidden{false};
	bool is_official{false};
	accelbyte::String name{};
	accelbyte::String ab_namespace{};
	accelbyte::String parent_namespace{};
	accelbyte::Optional<accelbyte::Vector<PayloadURL>> payload_url{};
	accelbyte::String preview{};
	accelbyte::Optional<accelbyte::Vector<PreviewURL>> preview_url{};
	accelbyte::String share_code{};
	accelbyte::String sub_type{};
	accelbyte::Vector<accelbyte::String> tags{};
	accelbyte::String type{};
	accelbyte::String updated_time{};
	accelbyte::String user_id{};
};

}
}
}