// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/leaderboard/leaderboard_export.h"
#include "accelbyte/leaderboard/anonymization/ded82064d44180ederboardAdminV1.h"
#include "accelbyte/leaderboard/models/ArchiveLeaderboardRequest.h"
#include "accelbyte/leaderboard/models/05b0dbcc10abb13gnedURLResponse.h"
#include "accelbyte/leaderboard/models/UserIdsRequest.h"
#include "accelbyte/leaderboard/models/UserRanksV3.h"
#include "accelbyte/leaderboard/models/DailyConfig.h"
#include "accelbyte/leaderboard/models/DeleteLeaderboardFaileds.h"
#include "accelbyte/leaderboard/models/DeleteLeaderboardsRequest.h"
#include "accelbyte/leaderboard/models/DeleteLeaderboards.h"
#include "accelbyte/leaderboard/models/LeaderboardConfigs.h"
#include "accelbyte/leaderboard/models/LeaderboardConfigsV3.h"
#include "accelbyte/leaderboard/models/5c6d66ca9b3fcebConfigsResponse.h"
#include "accelbyte/leaderboard/models/49884110f36cbaanfigsResponseV3.h"
#include "accelbyte/leaderboard/models/GetAllUserLeaderboardsResponse.h"
#include "accelbyte/leaderboard/models/1628844c024b674oardsResponseV3.h"
#include "accelbyte/leaderboard/models/GetHiddenUserResponse.h"
#include "accelbyte/leaderboard/models/LeaderboardConfig.h"
#include "accelbyte/leaderboard/models/LeaderboardConfigV3.h"
#include "accelbyte/leaderboard/models/6a26ce252271a3cdConfigResponse.h"
#include "accelbyte/leaderboard/models/3053edb273ba316onfigResponseV3.h"
#include "accelbyte/leaderboard/models/Rank.h"
#include "accelbyte/leaderboard/models/GetUserVisibilityResponse.h"
#include "accelbyte/leaderboard/models/LeaderboardConfigRequest.h"
#include "accelbyte/leaderboard/models/LeaderboardConfigRequestV3.h"
#include "accelbyte/leaderboard/models/MonthlyConfig.h"
#include "accelbyte/leaderboard/models/Pagination.h"
#include "accelbyte/leaderboard/models/Pagination.h"
#include "accelbyte/leaderboard/models/SetUserVisibilityRequest.h"
#include "accelbyte/leaderboard/models/UpdateLeaderboardConfigRequest.h"
#include "accelbyte/leaderboard/models/65e7c78c62e7ad7ConfigRequestV3.h"
#include "accelbyte/leaderboard/models/AdminUpdateUserPointV1Request.h"
#include "accelbyte/leaderboard/models/AdminUpdateUserPointV1.h"
#include "accelbyte/leaderboard/models/UserCycleRank.h"
#include "accelbyte/leaderboard/models/UserLeaderboardRank.h"
#include "accelbyte/leaderboard/models/UserLeaderboardRankV3.h"
#include "accelbyte/leaderboard/models/UserPoint.h"
#include "accelbyte/leaderboard/models/UserRank.h"
#include "accelbyte/leaderboard/models/UserRankDetail.h"
#include "accelbyte/leaderboard/models/UserRankDetailV3.h"
#include "accelbyte/leaderboard/models/UserRankV3.h"
#include "accelbyte/leaderboard/models/WeeklyConfig.h"
#include "accelbyte/leaderboard/models/Error.h"
#include "accelbyte/leaderboard/models/EntryV2.h"
#include "accelbyte/leaderboard/models/LeaderboardConfigsV2.h"
#include "accelbyte/leaderboard/models/LeaderboardConfigV2.h"
#include "accelbyte/leaderboard/models/e270c5968551645RankingResponse.h"
#include "accelbyte/leaderboard/models/Pagination.h"
#include "accelbyte/common/Error.h"
#include "accelbyte/tls/SecurityAuthorization.h"

#include <functional>
#include "accelbyte/memory/memory.h"

namespace accelbyte {
namespace leaderboard {

class Anonymization
{
public:	
    /**
    * @brief Anonymize user's leaderboard
    * @details &lt;p&gt;This API will delete specified user leaderboard&lt;p&gt;
    * @details /leaderboard/v1/admin/namespaces/{namespace}/users/{userId}/anonymization/leaderboards
    *
    */
    AB_leaderboard_EXPORT static void admin_anonymize_user_leaderboard_admin_v1(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const anonymization::AdminAnonymizeUserLeaderboardAdminV1& request, 
        const std::function<void()>& on_204,
        const std::function<void (const accelbyte::Error&)>& on_error);   

};

}
}