// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/http/ModelObject.h"
#include "accelbyte/common/Optional.h"
#include "accelbyte/common/String.h"
#include "accelbyte/common/Map.h"
#include "accelbyte/common/Vector.h"
#include "accelbyte/common/DateTime.h"
#include "accelbyte/memory/memory.h"
#include "accelbyte/utils/JsonObjectString.h"
#include "accelbyte/platform/platform_export.h"


namespace accelbyte {
namespace platform {
namespace model {

class ExportStoreCSVRequest : public accelbyte::http::ModelObject
{
public:
    enum class CatalogType : uint32_t {
        UNKNOWN,
        APP,
        CATEGORY,
        ITEM,
        SECTION,
        VIEW
    };
    /**
    * @brief default constructor.
    **/
	AB_platform_EXPORT  ExportStoreCSVRequest() = default;
	
    /**
    * @brief destructor.
    **/
    AB_platform_EXPORT virtual ~ExportStoreCSVRequest() = default;
	
	/**
    * @brief Return the object unique id (used for serialization)
    **/
    AB_platform_EXPORT virtual const String& model_id() const override;
	
	/**
    * @brief Return the unique id that can be used to determine this class (used for serialization)
    **/
    AB_platform_EXPORT static const String& model_object_id();
    
    // start of usefull parameters
	CatalogType catalog_type{};
	accelbyte::Optional<accelbyte::Vector<accelbyte::String>> fields_to_be_included{};
	accelbyte::Optional<accelbyte::Vector<accelbyte::String>> ids_to_be_exported{};
	accelbyte::Optional<accelbyte::String> store_id{};
};

}
}
}