// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/http/ModelObject.h"
#include "accelbyte/common/Optional.h"
#include "accelbyte/common/String.h"
#include "accelbyte/common/Map.h"
#include "accelbyte/common/Vector.h"
#include "accelbyte/common/DateTime.h"
#include "accelbyte/memory/memory.h"
#include "accelbyte/utils/JsonObjectString.h"
#include "accelbyte/reporting/reporting_export.h"

#include "accelbyte/reporting/models/BanAccountAction.h"

namespace accelbyte {
namespace reporting {
namespace model {

class ModerationRuleActions : public accelbyte::http::ModelObject
{
public:
    /**
    * @brief default constructor.
    **/
	AB_reporting_EXPORT  ModerationRuleActions() = default;
	
    /**
    * @brief destructor.
    **/
    AB_reporting_EXPORT virtual ~ModerationRuleActions() = default;
	
	/**
    * @brief Return the object unique id (used for serialization)
    **/
    AB_reporting_EXPORT virtual const String& model_id() const override;
	
	/**
    * @brief Return the unique id that can be used to determine this class (used for serialization)
    **/
    AB_reporting_EXPORT static const String& model_object_id();
    
    // start of usefull parameters
	accelbyte::Optional<BanAccountAction> ban_account{};
	accelbyte::Optional<bool> delete_chat{};
	accelbyte::Optional<accelbyte::Vector<accelbyte::String>> extension_action_ids{};
	accelbyte::Optional<bool> hide_content{};
};

}
}
}