// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/group/group_export.h"
#include "accelbyte/group/configuration/AdminGetGroupConfigsV1.h"
#include "accelbyte/group/configuration/AdminCreateGroupConfigV1.h"
#include "accelbyte/group/configuration/AdminInitiateGroupConfigV1.h"
#include "accelbyte/group/configuration/AdminDeleteGroupConfigV1.h"
#include "accelbyte/group/configuration/AdminGetGroupConfigV1.h"
#include "accelbyte/group/configuration/AdminUpdateGroupConfigV1.h"
#include "accelbyte/group/configuration/AdminDeleteGlobalRuleConfigV1.h"
#include "accelbyte/group/configuration/AdminUpdateGlobalRuleConfigV1.h"
#include "accelbyte/group/models/AssignRoleMemberV1.h"
#include "accelbyte/group/models/CancelInvitationGroupV2.h"
#include "accelbyte/group/models/CreateGroupConfigRequestV1.h"
#include "accelbyte/group/models/CreateGroupConfigV1.h"
#include "accelbyte/group/models/CreateMemberRoleV1.h"
#include "accelbyte/group/models/GetGroupConfigResponseV1.h"
#include "accelbyte/group/models/GetGroupsV2.h"
#include "accelbyte/group/models/GetGroupMembersResponseV1.h"
#include "accelbyte/group/models/GetGroupsResponseV1.h"
#include "accelbyte/group/models/GetGroupsByIdResponseV1.h"
#include "accelbyte/group/models/GetMemberRequestsResponseV1.h"
#include "accelbyte/group/models/GetMemberRolesResponseV1.h"
#include "accelbyte/group/models/GetUserGroupInfoResponseV1.h"
#include "accelbyte/group/models/GroupMember.h"
#include "accelbyte/group/models/GroupV1.h"
#include "accelbyte/group/models/GroupRule.h"
#include "accelbyte/group/models/GroupCustomRule.h"
#include "accelbyte/group/models/GroupRuleV1.h"
#include "accelbyte/group/models/GroupCustomRuleV1.h"
#include "accelbyte/group/models/JoinGroupV1.h"
#include "accelbyte/group/models/KickGroupMemberV1.h"
#include "accelbyte/group/models/LeaveGroupV1.h"
#include "accelbyte/group/models/GetConfigsV1.h"
#include "accelbyte/group/models/MemberRequestGroupV1.h"
#include "accelbyte/group/models/MemberRequestV1.h"
#include "accelbyte/group/models/MemberRoleV1.h"
#include "accelbyte/group/models/Pagination.h"
#include "accelbyte/group/models/CreateGroupV1.h"
#include "accelbyte/group/models/RemoveRoleMemberV1.h"
#include "accelbyte/group/models/RolePermission.h"
#include "accelbyte/group/models/Rule.h"
#include "accelbyte/group/models/RuleInfo.h"
#include "accelbyte/group/models/Rule.h"
#include "accelbyte/group/models/UpdateGroupConfigGlobalRulesV1.h"
#include "accelbyte/group/models/UpdateGroupConfigRequestV1.h"
#include "accelbyte/group/models/UpdateGroupConfigV1.h"
#include "accelbyte/group/models/UpdateGroupCustomAttributesV1.h"
#include "accelbyte/group/models/UpdateGroupCustomRuleV1.h"
#include "accelbyte/group/models/UpdateGroupPredefinedRuleV1.h"
#include "accelbyte/group/models/UpdateGroupRequestV1.h"
#include "accelbyte/group/models/UpdateCustomAttributesGroupV1.h"
#include "accelbyte/group/models/UpdateMemberRolePermissionsV1.h"
#include "accelbyte/group/models/UpdateMemberRoleV1.h"
#include "accelbyte/group/models/UserInvitationV1.h"
#include "accelbyte/group/models/Error.h"
#include "accelbyte/common/Error.h"
#include "accelbyte/tls/SecurityAuthorization.h"

#include <functional>
#include "accelbyte/memory/memory.h"

namespace accelbyte {
namespace group {

class Configuration
{
public:	
    /**
    * @brief List Group Configuration
    * @details This endpoint is used to get existing configuration. This Configuration is used as the main rule of the service. Each namespace will have its own configuration

Action Code: 73101
		
    * @details /group/v1/admin/namespaces/{namespace}/configuration
    *
    */
    AB_group_EXPORT static void admin_get_group_configs_v1(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const configuration::AdminGetGroupConfigsV1& request, 
        const std::function<void(const model::GetConfigsV1&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief create new configuration
    * @details This endpoint is used to create new configuration. Before creating the configuration, make sure that member role for admin and group member are already created before.

For each of the global rule, it will be the rule detail that consists of these fields:

*   **ruleAttribute**: attribute of the player that needs to be checked
*   **ruleCriteria**: criteria of the value. The value will be in enum of EQUAL, MINIMUM, MAXIMUM
*   **ruleValue**: value that needs to be checked

Allowed Action can only be filled with any available action in the Group Service. For the configuration, the only value is **&#34;createGroup&#34;**

Action Code: 73103
		
    * @details /group/v1/admin/namespaces/{namespace}/configuration
    *
    */
    AB_group_EXPORT static void admin_create_group_config_v1(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const configuration::AdminCreateGroupConfigV1& request, 
        const std::function<void(const model::CreateGroupConfigV1&)>& on_201,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief initiate configuration
    * @details This endpoint is used to initiate configuration.  
This endpoint will automatically create default configuration and member roles with default permission  
Default Permission for admin role will cover these permission:  
- Permission to invite user to group
- Permission to accept or reject join request
- Permission to kick group member  

Default max member value will be 50 and global rules will be empty  
Action Code: 73104
    * @details /group/v1/admin/namespaces/{namespace}/configuration/initiate
    *
    */
    AB_group_EXPORT static void admin_initiate_group_config_v1(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const configuration::AdminInitiateGroupConfigV1& request, 
        const std::function<void(const model::CreateGroupConfigV1&)>& on_201,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Delete group configuration
    * @details This endpoint is used to delete group configuration. This Configuration is used as the main rule of the service. Each namespace will have its own configuration

Action Code: 73101
		
    * @details /group/v1/admin/namespaces/{namespace}/configuration/{configurationCode}
    *
    */
    AB_group_EXPORT static void admin_delete_group_config_v1(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const configuration::AdminDeleteGroupConfigV1& request, 
        const std::function<void()>& on_204,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief get existing configuration
    * @details This endpoint is used to get existing configuration. This Configuration is used as the main rule of the service. Each namespace will have its own configuration

Action Code: 73101
		
    * @details /group/v1/admin/namespaces/{namespace}/configuration/{configurationCode}
    *
    */
    AB_group_EXPORT static void admin_get_group_config_v1(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const configuration::AdminGetGroupConfigV1& request, 
        const std::function<void(const model::GetGroupConfigResponseV1&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief update existing configuration
    * @details This endpoint is used to update existing configuration. groupAdminRoleId and groupMemberRoleId won&#39;t be able to be updated. User can try to change the member role permission instead for each of those member role

Action Code: 73102
		
    * @details /group/v1/admin/namespaces/{namespace}/configuration/{configurationCode}
    *
    */
    AB_group_EXPORT static void admin_update_group_config_v1(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const configuration::AdminUpdateGroupConfigV1& request, 
        const std::function<void(const model::UpdateGroupConfigV1&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief delete existing configuration global rule based on allowed action
    * @details This endpoint is used to delete existing global rule configuration based on the allowed action. It will not give any error if the allowed action is not existed in the global rule

Action Code: 73105
		
    * @details /group/v1/admin/namespaces/{namespace}/configuration/{configurationCode}/rules/{allowedAction}
    *
    */
    AB_group_EXPORT static void admin_delete_global_rule_config_v1(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const configuration::AdminDeleteGlobalRuleConfigV1& request, 
        const std::function<void(const model::UpdateGroupConfigV1&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief update existing configuration global rule
    * @details This endpoint is used to update existing global rule configuration based on the allowed action. It will replace the permission with the request

Action Code: 73106
		
    * @details /group/v1/admin/namespaces/{namespace}/configuration/{configurationCode}/rules/{allowedAction}
    *
    */
    AB_group_EXPORT static void admin_update_global_rule_config_v1(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const configuration::AdminUpdateGlobalRuleConfigV1& request, 
        const std::function<void(const model::UpdateGroupConfigV1&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

};

}
}