// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/http/SendableObject.h"
#include "accelbyte/common/DateTime.h"
#include "accelbyte/utils/JsonObjectString.h"
#include "accelbyte/common/Optional.h"
#include "accelbyte/iam/iam_export.h"

#include "accelbyte/common/String.h"
#include "accelbyte/common/Map.h"
#include "accelbyte/common/Vector.h"

#include "accelbyte/iam/models/0186368831f34f6gressionRequest.h"

namespace accelbyte {
namespace iam {
namespace users {

/**
* @brief Force update other account&#39;s Platform Account relation to current User Account. 
This endpoint can transfer progression from 3rd platform binding account&#39;s to current account.
This endpoint need the same requestID which also used in [Get link status](#operations-Users-PublicGetAsyncStatus).


**Authentication:**
The _**userId**_ parameter should match the one in the access token.
*/
class ForceLinkPlatformProgression : public accelbyte::http::SendableObject
{
public:
    
    
    /**
    * @brief default constructor.
    **/
	AB_iam_EXPORT ForceLinkPlatformProgression() = default;
	
    /**
    * @brief destrutor.
    **/
    AB_iam_EXPORT virtual ~ForceLinkPlatformProgression() = default;
	
	/**
    * @brief Return the object unique id (used for serialization)
    **/
    AB_iam_EXPORT const String& sendable_id() const override;
	
	/**
    * @brief Return the unique id that can be used to determine this class (used for serialization)
    **/
    AB_iam_EXPORT static const String& sendable_object_id();
	
    // usefull parameters    
     /**
     * @brief None
    **/
    model::LinkPlatformAccountProgressionRequest body{};
     /**
     * @brief Namespace, only accept alphabet and numeric
if not set the user namespace will be used.
    **/
    accelbyte::Optional<accelbyte::String> ab_namespace{};
     /**
     * @brief Current user ID. Should match the one in the access token
    **/
    accelbyte::String user_id{};
};

}
}
}