// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/http/SendableObject.h"
#include "accelbyte/common/DateTime.h"
#include "accelbyte/utils/JsonObjectString.h"
#include "accelbyte/common/Optional.h"
#include "accelbyte/ehs/ehs_export.h"

#include "accelbyte/common/String.h"
#include "accelbyte/common/Map.h"
#include "accelbyte/common/Vector.h"


namespace accelbyte {
namespace ehs {
namespace utility {

/**
* @brief Required permission: `ADMIN:NAMESPACE:{namespace}:EXTEND:GRPCREFLECTION` (READ)

Do gRPC reflection to get list of services info served by a server. Please use one of these parameter `host` or `appName`.
Use query parameter `host` to get reflection for custom host/port address, or 
Use query parameter `appName` to get reflection for accelbyte hosted extend app
*/
class AdminGetGRPCReflectionInfo : public accelbyte::http::SendableObject
{
public:
    
    
    /**
    * @brief default constructor.
    **/
	AB_ehs_EXPORT AdminGetGRPCReflectionInfo() = default;
	
    /**
    * @brief destrutor.
    **/
    AB_ehs_EXPORT virtual ~AdminGetGRPCReflectionInfo() = default;
	
	/**
    * @brief Return the object unique id (used for serialization)
    **/
    AB_ehs_EXPORT const String& sendable_id() const override;
	
	/**
    * @brief Return the unique id that can be used to determine this class (used for serialization)
    **/
    AB_ehs_EXPORT static const String& sendable_object_id();
	
    // usefull parameters    
     /**
     * @brief AccelByte game namespace
if not set the user namespace will be used.
    **/
    accelbyte::Optional<accelbyte::String> ab_namespace{};
     /**
     * @brief extend app name on which reflection will be done
    **/
    accelbyte::Optional<accelbyte::String> app_name{};
     /**
     * @brief host and port of grpc server on which reflection will be done (e.g. mygrpc.tcp.ap.ngrok.io:19241)
    **/
    accelbyte::Optional<accelbyte::String> host{};
     /**
     * @brief security type for grpc client connection, values: `plaintext` | `tls` (optional, default to plaintext)
    **/
    accelbyte::Optional<accelbyte::String> security_type{};
};

}
}
}