// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/chat/chat_export.h"
#include "accelbyte/chat/topic/AdminFilterChatMessage.h"
#include "accelbyte/chat/topic/AdminChatHistory.h"
#include "accelbyte/chat/topic/AdminCreateNamespaceTopic.h"
#include "accelbyte/chat/topic/AdminTopics.h"
#include "accelbyte/chat/topic/AdminCreateTopic.h"
#include "accelbyte/chat/topic/AdminChannelTopics.h"
#include "accelbyte/chat/topic/AdminChannelTopicSummary.h"
#include "accelbyte/chat/topic/AdminQueryTopicLog.h"
#include "accelbyte/chat/topic/AdminDeleteTopic.h"
#include "accelbyte/chat/topic/AdminUpdateTopic.h"
#include "accelbyte/chat/topic/AdminBanTopicMembers.h"
#include "accelbyte/chat/topic/AdminChannelTopicInfo.h"
#include "accelbyte/chat/topic/AdminTopicChatHistory.h"
#include "accelbyte/chat/topic/AdminSendChat.h"
#include "accelbyte/chat/topic/AdminDeleteChat.h"
#include "accelbyte/chat/topic/AdminTopicMembers.h"
#include "accelbyte/chat/topic/AdminTopicShards.h"
#include "accelbyte/chat/topic/AdminUnbanTopicMembers.h"
#include "accelbyte/chat/topic/AdminRemoveTopicMember.h"
#include "accelbyte/chat/topic/AdminAddTopicMember.h"
#include "accelbyte/chat/topic/AdminQueryTopic.h"
#include "accelbyte/chat/topic/AdminQueryUsersTopic.h"
#include "accelbyte/chat/topic/GetMutedTopics.h"
#include "accelbyte/chat/topic/Topics.h"
#include "accelbyte/chat/topic/BanTopicMembers.h"
#include "accelbyte/chat/topic/ChatHistory.h"
#include "accelbyte/chat/topic/DeleteChat.h"
#include "accelbyte/chat/topic/MuteUser.h"
#include "accelbyte/chat/topic/UnbanTopicMembers.h"
#include "accelbyte/chat/topic/UnmuteUser.h"
#include "accelbyte/chat/models/AddMemberRequest.h"
#include "accelbyte/chat/models/CreateNamespaceTopicRequest.h"
#include "accelbyte/chat/models/CreateTopicRequest.h"
#include "accelbyte/chat/models/CreateTopicResponse.h"
#include "accelbyte/chat/models/MuteUserRequest.h"
#include "accelbyte/chat/models/MutedTopicResponse.h"
#include "accelbyte/chat/models/SendChatRequest.h"
#include "accelbyte/chat/models/UnmuteUserRequest.h"
#include "accelbyte/chat/models/UpdateTopicRequest.h"
#include "accelbyte/chat/models/LogAppMessageDeclaration.h"
#include "accelbyte/chat/models/LogconfigConfiguration.h"
#include "accelbyte/chat/models/AddUserTopicResponse.h"
#include "accelbyte/chat/models/DeleteTopicResponse.h"
#include "accelbyte/chat/models/AddInboxCategoryRequest.h"
#include "accelbyte/chat/models/AddInboxCategoryResponse.h"
#include "accelbyte/chat/models/BanTopicMemberParam.h"
#include "accelbyte/chat/models/BanTopicMemberResponse.h"
#include "accelbyte/chat/models/CategoryHook.h"
#include "accelbyte/chat/models/ChannelTopicResponse.h"
#include "accelbyte/chat/models/ChannelTopicSummaryResponse.h"
#include "accelbyte/chat/models/ChannelTopicPaginationResponse.h"
#include "accelbyte/chat/models/ChatMessageResponse.h"
#include "accelbyte/chat/models/ChatMessagePaginationResponse.h"
#include "accelbyte/chat/models/ChatSnapshotMessage.h"
#include "accelbyte/chat/models/ChatSnapshots.h"
#include "accelbyte/chat/models/Config.h"
#include "accelbyte/chat/models/ConfigExport.h"
#include "accelbyte/chat/models/Configs.h"
#include "accelbyte/chat/models/AdminConfigResponse.h"
#include "accelbyte/chat/models/Dictionary.h"
#include "accelbyte/chat/models/DictionaryChild.h"
#include "accelbyte/chat/models/DictionaryExport.h"
#include "accelbyte/chat/models/DictionaryExportItem.h"
#include "accelbyte/chat/models/DictionaryGroup.h"
#include "accelbyte/chat/models/DictionaryImportResponse.h"
#include "accelbyte/chat/models/DictionaryInsertsRequest.h"
#include "accelbyte/chat/models/DictionaryInsertRequest.h"
#include "accelbyte/chat/models/DictionaryQueryResponse.h"
#include "accelbyte/chat/models/DictionaryUpdateRequest.h"
#include "accelbyte/chat/models/DictionaryChildren.h"
#include "accelbyte/chat/models/DictionaryWordChanges.h"
#include "accelbyte/chat/models/GetInboxCategoriesResponseItem.h"
#include "accelbyte/chat/models/GetInboxMessagesResponse.h"
#include "accelbyte/chat/models/GetInboxMessagesResponseData.h"
#include "accelbyte/chat/models/GetInboxStatsResponse.h"
#include "accelbyte/chat/models/GetInboxUsersResponse.h"
#include "accelbyte/chat/models/ImportConfigResponse.h"
#include "accelbyte/chat/models/JSONSchemaType.h"
#include "accelbyte/chat/models/MessageRequest.h"
#include "accelbyte/chat/models/MessageResultAttributes.h"
#include "accelbyte/chat/models/MessageStats.h"
#include "accelbyte/chat/models/Pagination.h"
#include "accelbyte/chat/models/BanTopicMembersRequest.h"
#include "accelbyte/chat/models/BanTopicMembersResponse.h"
#include "accelbyte/chat/models/ConfigResponse.h"
#include "accelbyte/chat/models/UnbanTopicMembersRequest.h"
#include "accelbyte/chat/models/UnbanTopicMembersResponse.h"
#include "accelbyte/chat/models/SaveInboxMessageRequest.h"
#include "accelbyte/chat/models/SaveInboxMessageResponse.h"
#include "accelbyte/chat/models/SendInboxMessageRequest.h"
#include "accelbyte/chat/models/SendInboxMessageResponse.h"
#include "accelbyte/chat/models/TopicInfo.h"
#include "accelbyte/chat/models/TopicLogItem.h"
#include "accelbyte/chat/models/TopicLogPaginationResponse.h"
#include "accelbyte/chat/models/TopicMemberResponse.h"
#include "accelbyte/chat/models/TopicMemberPaginationResponse.h"
#include "accelbyte/chat/models/TopicResponse.h"
#include "accelbyte/chat/models/UnbanTopicMemberParam.h"
#include "accelbyte/chat/models/UnbanTopicMemberResponse.h"
#include "accelbyte/chat/models/UnsendInboxMessageRequest.h"
#include "accelbyte/chat/models/UnsendInboxMessageResponse.h"
#include "accelbyte/chat/models/UpdateInboxCategoryRequest.h"
#include "accelbyte/chat/models/UpdateInboxMessageRequest.h"
#include "accelbyte/chat/models/UserInbox.h"
#include "accelbyte/chat/models/ErrorResponse.h"
#include "accelbyte/chat/models/ErrorResponseBody.h"
#include "accelbyte/chat/models/TopicInfoMember.h"
#include "accelbyte/common/Error.h"
#include "accelbyte/tls/SecurityAuthorization.h"

#include <functional>
#include "accelbyte/memory/memory.h"

namespace accelbyte {
namespace chat {

class Topic
{
public:	
    /**
    * @brief Return filtered chat message
    * @details For testing purpose, doesn&#39;t send any message to the topic. Always do filter regardless of enableProfanityFilter configuration.
    * @details /chat/admin/namespaces/{namespace}/chat/filter
    *
    */
    AB_chat_EXPORT static void admin_filter_chat_message(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const topic::AdminFilterChatMessage& request, 
        const std::function<void(const model::MessageResultAttributes&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief admin get chat history
    * @details Get chat history in a namespace.
    * @details /chat/admin/namespaces/{namespace}/chats
    *
    */
    AB_chat_EXPORT static void admin_chat_history(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const topic::AdminChatHistory& request, 
        const std::function<void(const model::ChatMessagePaginationResponse&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Use to create namespace group. Message that send to this group send to connected user in a namespace
    * @details Create new namespace group topic in a namespace.
    * @details /chat/admin/namespaces/{namespace}/namespace-topic
    *
    */
    AB_chat_EXPORT static void admin_create_namespace_topic(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const topic::AdminCreateNamespaceTopic& request, 
        const std::function<void(const model::CreateTopicResponse&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief admin get list of topic
    * @details Get chat list of topic in a namespace.
    * @details /chat/admin/namespaces/{namespace}/topic
    *
    */
    AB_chat_EXPORT static void admin_topics(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const topic::AdminTopics& request, 
        const std::function<void(const accelbyte::Vector<model::TopicResponse>&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Use to create group. Only group admin can use this operation
    * @details Create new group topic in a namespace.
    * @details /chat/admin/namespaces/{namespace}/topic
    *
    */
    AB_chat_EXPORT static void admin_create_topic(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const topic::AdminCreateTopic& request, 
        const std::function<void(const model::CreateTopicResponse&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief admin get list of channel topic
    * @details Get channel chat list of topic in a namespace.
    * @details /chat/admin/namespaces/{namespace}/topic/channel
    *
    */
    AB_chat_EXPORT static void admin_channel_topics(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const topic::AdminChannelTopics& request, 
        const std::function<void(const model::ChannelTopicPaginationResponse&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief admin get channel topic summary
    * @details Get chat list of topic in a namespace.
    * @details /chat/admin/namespaces/{namespace}/topic/channel/summary
    *
    */
    AB_chat_EXPORT static void admin_channel_topic_summary(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const topic::AdminChannelTopicSummary& request, 
        const std::function<void(const model::ChannelTopicSummaryResponse&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief admin query topic log
    * @details Get chat log of topic in a namespace.
    * @details /chat/admin/namespaces/{namespace}/topic/log
    *
    */
    AB_chat_EXPORT static void admin_query_topic_log(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const topic::AdminQueryTopicLog& request, 
        const std::function<void(const model::TopicLogPaginationResponse&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Use to delete group. Only group admin can use this operation
    * @details Delete topic in a namespace.
    * @details /chat/admin/namespaces/{namespace}/topic/{topic}
    *
    */
    AB_chat_EXPORT static void admin_delete_topic(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const topic::AdminDeleteTopic& request, 
        const std::function<void(const model::DeleteTopicResponse&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Use to update group information. Only group admin can use this operation
    * @details Update group topic in a namespace.
    * @details /chat/admin/namespaces/{namespace}/topic/{topic}
    *
    */
    AB_chat_EXPORT static void admin_update_topic(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const topic::AdminUpdateTopic& request, 
        const std::function<void(const model::CreateTopicResponse&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief admins ban user in group topic
    * @details Ban users in some topic. banned user not assigned to shard for channel topic, and cannot send and query chat.
    * @details /chat/admin/namespaces/{namespace}/topic/{topic}/ban-members
    *
    */
    AB_chat_EXPORT static void admin_ban_topic_members(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const topic::AdminBanTopicMembers& request, 
        const std::function<void(const model::BanTopicMemberResponse&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief admin get channel topic detail
    * @details Get chat list of topic in a namespace.
    * @details /chat/admin/namespaces/{namespace}/topic/{topic}/channel
    *
    */
    AB_chat_EXPORT static void admin_channel_topic_info(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const topic::AdminChannelTopicInfo& request, 
        const std::function<void(const model::ChannelTopicResponse&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief admin get chat history
    * @details Get chat history in a namespace.
    * @details /chat/admin/namespaces/{namespace}/topic/{topic}/chats
    * @deprecated True
    *
    */
    AB_chat_EXPORT static void admin_topic_chat_history(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const topic::AdminTopicChatHistory& request, 
        const std::function<void(const model::ChatMessagePaginationResponse&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief admins send chat to group topic
    * @details Send message to chat topic as system.
    * @details /chat/admin/namespaces/{namespace}/topic/{topic}/chats
    *
    */
    AB_chat_EXPORT static void admin_send_chat(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const topic::AdminSendChat& request, 
        const std::function<void(const accelbyte::Vector<model::ChatMessageResponse>&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief admins delete chat
    * @details Delete chat.
    * @details /chat/admin/namespaces/{namespace}/topic/{topic}/chats/{chatId}
    *
    */
    AB_chat_EXPORT static void admin_delete_chat(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const topic::AdminDeleteChat& request, 
        const std::function<void()>& on_204,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief admin get topic member
    * @details Get topic members.
    * @details /chat/admin/namespaces/{namespace}/topic/{topic}/members
    *
    */
    AB_chat_EXPORT static void admin_topic_members(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const topic::AdminTopicMembers& request, 
        const std::function<void(const model::TopicMemberPaginationResponse&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief admin get shard list of topic
    * @details Get shard list from topic.
    * @details /chat/admin/namespaces/{namespace}/topic/{topic}/shards
    *
    */
    AB_chat_EXPORT static void admin_topic_shards(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const topic::AdminTopicShards& request, 
        const std::function<void(const accelbyte::Vector<accelbyte::String>&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief admins unban user in group topic
    * @details Unban users in some topic.
    * @details /chat/admin/namespaces/{namespace}/topic/{topic}/unban-members
    *
    */
    AB_chat_EXPORT static void admin_unban_topic_members(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const topic::AdminUnbanTopicMembers& request, 
        const std::function<void(const model::UnbanTopicMemberResponse&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief admin remove user from topic
    * @details Remove member from topic in a namespace.
    * @details /chat/admin/namespaces/{namespace}/topic/{topic}/user/{userId}
    *
    */
    AB_chat_EXPORT static void admin_remove_topic_member(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const topic::AdminRemoveTopicMember& request, 
        const std::function<void(const model::AddUserTopicResponse&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief admin add user to topic
    * @details Add new member for topic in a namespace.
    * @details /chat/admin/namespaces/{namespace}/topic/{topic}/user/{userId}
    *
    */
    AB_chat_EXPORT static void admin_add_topic_member(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const topic::AdminAddTopicMember& request, 
        const std::function<void(const model::AddUserTopicResponse&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief admin query topics
    * @details Get topics in a namespace.
    * @details /chat/admin/namespaces/{namespace}/topics
    *
    */
    AB_chat_EXPORT static void admin_query_topic(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const topic::AdminQueryTopic& request, 
        const std::function<void(const accelbyte::Vector<model::TopicInfo>&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief admin query user's topics
    * @details Get user&#39;s topics in a namespace.
    * @details /chat/admin/namespaces/{namespace}/users/{userId}/topics
    *
    */
    AB_chat_EXPORT static void admin_query_users_topic(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const topic::AdminQueryUsersTopic& request, 
        const std::function<void(const model::TopicLogPaginationResponse&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief public get muted at topics
    * @details get chat muted topics in a namespace.
    * @details /chat/public/namespaces/{namespace}/muted
    *
    */
    AB_chat_EXPORT static void get_muted_topics(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const topic::GetMutedTopics& request, 
        const std::function<void(const accelbyte::Vector<model::MutedTopicResponse>&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief public get list of topic
    * @details get chat list of topic in a namespace.
    * @details /chat/public/namespaces/{namespace}/topic
    *
    */
    AB_chat_EXPORT static void topics(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const topic::Topics& request, 
        const std::function<void(const accelbyte::Vector<model::ChatMessageResponse>&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief public ban topic members in a group topic
    * @details Ban topic members in a group topic.
    * @details /chat/public/namespaces/{namespace}/topic/{topic}/ban-members
    *
    */
    AB_chat_EXPORT static void ban_topic_members(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const topic::BanTopicMembers& request, 
        const std::function<void(const model::BanTopicMembersResponse&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief public get chat history
    * @details get chat history in a namespace.
    * @details /chat/public/namespaces/{namespace}/topic/{topic}/chats
    *
    */
    AB_chat_EXPORT static void chat_history(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const topic::ChatHistory& request, 
        const std::function<void(const accelbyte::Vector<model::ChatMessageResponse>&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief public delete chat
    * @details Delete chat.
    * @details /chat/public/namespaces/{namespace}/topic/{topic}/chats/{chatId}
    *
    */
    AB_chat_EXPORT static void delete_chat(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const topic::DeleteChat& request, 
        const std::function<void()>& on_204,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief public mute user in a topic
    * @details Mute user.
    * @details /chat/public/namespaces/{namespace}/topic/{topic}/mute
    *
    */
    AB_chat_EXPORT static void mute_user(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const topic::MuteUser& request, 
        const std::function<void()>& on_204,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief public unban topic members in a group topic
    * @details Unban topic members in a group topic.
    * @details /chat/public/namespaces/{namespace}/topic/{topic}/unban-members
    *
    */
    AB_chat_EXPORT static void unban_topic_members(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const topic::UnbanTopicMembers& request, 
        const std::function<void(const model::UnbanTopicMembersResponse&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief public unmute user in a topic
    * @details Unmute user.
    * @details /chat/public/namespaces/{namespace}/topic/{topic}/unmute
    *
    */
    AB_chat_EXPORT static void unmute_user(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const topic::UnmuteUser& request, 
        const std::function<void()>& on_204,
        const std::function<void (const accelbyte::Error&)>& on_error);   

};

}
}