// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/ugc/ugc_export.h"
#include "accelbyte/ugc/admin_content_v2/AdminGetContentByChannelIDV2.h"
#include "accelbyte/ugc/admin_content_v2/AdminCreateContentV2.h"
#include "accelbyte/ugc/admin_content_v2/AdminDeleteOfficialContentV2.h"
#include "accelbyte/ugc/admin_content_v2/AdminUpdateOfficialContentV2.h"
#include "accelbyte/ugc/admin_content_v2/AdminCopyContent.h"
#include "accelbyte/ugc/admin_content_v2/187175d10560e40entFileLocation.h"
#include "accelbyte/ugc/admin_content_v2/500c3299a1e5606tentUploadURLV2.h"
#include "accelbyte/ugc/admin_content_v2/AdminGetContentsV2.h"
#include "accelbyte/ugc/admin_content_v2/AdminGetContentByIdsV2.h"
#include "accelbyte/ugc/admin_content_v2/AdminGetContentByShareCodesV2.h"
#include "accelbyte/ugc/admin_content_v2/AdminGetContentByShareCodeV2.h"
#include "accelbyte/ugc/admin_content_v2/AdminGetContentByContentIDV2.h"
#include "accelbyte/ugc/admin_content_v2/AdminRollbackContentVersionV2.h"
#include "accelbyte/ugc/admin_content_v2/AdminUploadContentScreenshotV2.h"
#include "accelbyte/ugc/admin_content_v2/AdminUpdateScreenshotsV2.h"
#include "accelbyte/ugc/admin_content_v2/AdminDeleteContentScreenshotV2.h"
#include "accelbyte/ugc/admin_content_v2/AdminGetContentVersionsV2.h"
#include "accelbyte/ugc/admin_content_v2/8e494f7e0649a66ntByShareCodeV2.h"
#include "accelbyte/ugc/admin_content_v2/26b39c4c7a15c1fntByShareCodeV2.h"
#include "accelbyte/ugc/admin_content_v2/AdminDeleteUserContentV2.h"
#include "accelbyte/ugc/admin_content_v2/AdminUpdateUserContentV2.h"
#include "accelbyte/ugc/admin_content_v2/04df55df24c7b25entFileLocation.h"
#include "accelbyte/ugc/admin_content_v2/386253bd5938a3atentUploadURLV2.h"
#include "accelbyte/ugc/admin_content_v2/AdminGetContentByUserIDV2.h"
#include "accelbyte/ugc/admin_content_v2/AdminUpdateContentHideStatusV2.h"
#include "accelbyte/ugc/models/DownloadCount.h"
#include "accelbyte/ugc/models/AdminContentRequestV2.h"
#include "accelbyte/ugc/models/AdminGetContentsRequest.h"
#include "accelbyte/ugc/models/AdminUpdateContentRequest.h"
#include "accelbyte/ugc/models/AdminUpdateContentRequestV2.h"
#include "accelbyte/ugc/models/ApproveStagingContentRequest.h"
#include "accelbyte/ugc/models/AdminChannelRequest.h"
#include "accelbyte/ugc/models/Channel.h"
#include "accelbyte/ugc/models/AdminConfigResponse.h"
#include "accelbyte/ugc/models/ContentDownload.h"
#include "accelbyte/ugc/models/ContentDownloadV2.h"
#include "accelbyte/ugc/models/ContentDownloader.h"
#include "accelbyte/ugc/models/ContentLikeRequest.h"
#include "accelbyte/ugc/models/Like.h"
#include "accelbyte/ugc/models/Likers.h"
#include "accelbyte/ugc/models/ContentRequestV2.h"
#include "accelbyte/ugc/models/ContentSnapshot.h"
#include "accelbyte/ugc/models/ContentVersion.h"
#include "accelbyte/ugc/models/CopyContentRequest.h"
#include "accelbyte/ugc/models/CreateContentRequest.h"
#include "accelbyte/ugc/models/AdminCreateContentRequestS3.h"
#include "accelbyte/ugc/models/CreateContent.h"
#include "accelbyte/ugc/models/CreateContentV2.h"
#include "accelbyte/ugc/models/CreateGroupRequest.h"
#include "accelbyte/ugc/models/Group.h"
#include "accelbyte/ugc/models/CreateScreenshotRequest.h"
#include "accelbyte/ugc/models/Screenshots.h"
#include "accelbyte/ugc/models/CreateTagRequest.h"
#include "accelbyte/ugc/models/Tag.h"
#include "accelbyte/ugc/models/CreateTypeRequest.h"
#include "accelbyte/ugc/models/Type.h"
#include "accelbyte/ugc/models/CreatorFollowState.h"
#include "accelbyte/ugc/models/CreatorOverview.h"
#include "accelbyte/ugc/models/Creator.h"
#include "accelbyte/ugc/models/1297a459abe6758ploadURLRequest.h"
#include "accelbyte/ugc/models/ContentUpload.h"
#include "accelbyte/ugc/models/GetContentByShareCodesRequest.h"
#include "accelbyte/ugc/models/GetContentPreviewResponse.h"
#include "accelbyte/ugc/models/HideContentRequest.h"
#include "accelbyte/ugc/models/LikeState.h"
#include "accelbyte/ugc/models/GetContentVersionsResponse.h"
#include "accelbyte/ugc/models/ContentDownloadPagination.h"
#include "accelbyte/ugc/models/ContentDownloadV2Pagination.h"
#include "accelbyte/ugc/models/ContentDownloaderPagination.h"
#include "accelbyte/ugc/models/ContentLikersPagination.h"
#include "accelbyte/ugc/models/CreatorOverviewPagination.h"
#include "accelbyte/ugc/models/GetChannelPagination.h"
#include "accelbyte/ugc/models/GetConfigsPagination.h"
#include "accelbyte/ugc/models/GetTagPagination.h"
#include "accelbyte/ugc/models/GetTypePagination.h"
#include "accelbyte/ugc/models/GroupPagination.h"
#include "accelbyte/ugc/models/StagingContentsPagination.h"
#include "accelbyte/ugc/models/CursorPagination.h"
#include "accelbyte/ugc/models/PayloadURL.h"
#include "accelbyte/ugc/models/PreviewURL.h"
#include "accelbyte/ugc/models/ChannelRequest.h"
#include "accelbyte/ugc/models/CreateContentS3Request.h"
#include "accelbyte/ugc/models/GetContentsRequest.h"
#include "accelbyte/ugc/models/Screenshot.h"
#include "accelbyte/ugc/models/StagingContent.h"
#include "accelbyte/ugc/models/UpdateChannelRequest.h"
#include "accelbyte/ugc/models/UpdateConfigRequest.h"
#include "accelbyte/ugc/models/UpdateContentRequest.h"
#include "accelbyte/ugc/models/UpdateContentRequestV2.h"
#include "accelbyte/ugc/models/UpdateContentV2.h"
#include "accelbyte/ugc/models/UpdateContentShareCodeRequest.h"
#include "accelbyte/ugc/models/UpdateFileLocationRequest.h"
#include "accelbyte/ugc/models/UpdateScreenshotRequest.h"
#include "accelbyte/ugc/models/ScreenshotUpdate.h"
#include "accelbyte/ugc/models/UpdateStagingContentRequest.h"
#include "accelbyte/ugc/models/UserFollowRequest.h"
#include "accelbyte/ugc/models/Follow.h"
#include "accelbyte/ugc/models/CreateScreenshotRequestItem.h"
#include "accelbyte/ugc/models/PreviewMetadata.h"
#include "accelbyte/ugc/models/UpdateScreenshot.h"
#include "accelbyte/ugc/models/Error.h"
#include "accelbyte/common/Error.h"
#include "accelbyte/tls/SecurityAuthorization.h"

#include <functional>
#include "accelbyte/memory/memory.h"

namespace accelbyte {
namespace ugc {

class AdminContentV2
{
public:	
    /**
    * @brief List contents specific to a channel
    * @details List content specific to a channel
    * @details /ugc/v2/admin/namespaces/{namespace}/channels/{channelId}/contents
    *
    */
    AB_ugc_EXPORT static void admin_get_content_by_channel_idv2(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const admin_content_v2::AdminGetContentByChannelIDV2& request, 
        const std::function<void(const model::ContentDownloadV2Pagination&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Create a content
    * @details Create official content
    * @details /ugc/v2/admin/namespaces/{namespace}/channels/{channelId}/contents
    *
    */
    AB_ugc_EXPORT static void admin_create_content_v2(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const admin_content_v2::AdminCreateContentV2& request, 
        const std::function<void(const model::CreateContentV2&)>& on_201,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Delete official content
    * @details Delete existing official content
    * @details /ugc/v2/admin/namespaces/{namespace}/channels/{channelId}/contents/{contentId}
    *
    */
    AB_ugc_EXPORT static void admin_delete_official_content_v2(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const admin_content_v2::AdminDeleteOfficialContentV2& request, 
        const std::function<void()>& on_204,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Update official content
    * @details Update existing official content
    * @details /ugc/v2/admin/namespaces/{namespace}/channels/{channelId}/contents/{contentId}
    *
    */
    AB_ugc_EXPORT static void admin_update_official_content_v2(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const admin_content_v2::AdminUpdateOfficialContentV2& request, 
        const std::function<void(const model::UpdateContentV2&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Copy contents from a channel to another
    * @details Copy existing content from source channel to target channel.
    * @details /ugc/v2/admin/namespaces/{namespace}/channels/{channelId}/contents/{contentId}/copy
    *
    */
    AB_ugc_EXPORT static void admin_copy_content(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const admin_content_v2::AdminCopyContent& request, 
        const std::function<void(const model::ContentDownloadV2&)>& on_201,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Update content file location
    * @details This endpoint should be used after calling generate official content upload url endpoint to commit the changes
    * @details /ugc/v2/admin/namespaces/{namespace}/channels/{channelId}/contents/{contentId}/fileLocation
    *
    */
    AB_ugc_EXPORT static void admin_update_official_content_file_location(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const admin_content_v2::AdminUpdateOfficialContentFileLocation& request, 
        const std::function<void(const model::UpdateContentV2&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Generate official content upload URL
    * @details Generate official content upload URL
    * @details /ugc/v2/admin/namespaces/{namespace}/channels/{channelId}/contents/{contentId}/uploadUrl
    *
    */
    AB_ugc_EXPORT static void admin_generate_official_content_upload_urlv2(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const admin_content_v2::AdminGenerateOfficialContentUploadURLV2& request, 
        const std::function<void(const model::ContentUpload&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief List contents
    * @details For advance tag filtering supports &amp; as AND operator and | as OR operator and parentheses ( ) for priority. e.g:  


*tags=red*
*tags=red&amp;animal*
*tags=red|animal*
*tags=red&amp;animal|wild*
*tags=red&amp;(animal|wild)*

The precedence of logical operator is AND &gt; OR, so if no parentheses, AND logical operator will be executed first.  

Allowed character for operand: alphanumeric, underscore _ and dash -  

Allowed character for operator: &amp; | ( )


**Please note that value of tags query param should be URL encoded**
    * @details /ugc/v2/admin/namespaces/{namespace}/contents
    *
    */
    AB_ugc_EXPORT static void admin_get_contents_v2(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const admin_content_v2::AdminGetContentsV2& request, 
        const std::function<void(const model::ContentDownloadV2Pagination&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Bulk get content by content IDs
    * @details Maximum contentId per request 100
    * @details /ugc/v2/admin/namespaces/{namespace}/contents/bulk
    *
    */
    AB_ugc_EXPORT static void admin_get_content_by_ids_v2(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const admin_content_v2::AdminGetContentByIdsV2& request, 
        const std::function<void(const accelbyte::Vector<model::ContentDownloadV2>&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Bulk get content by content sharecodes
    * @details Maximum sharecodes per request 100
    * @details /ugc/v2/admin/namespaces/{namespace}/contents/sharecodes/bulk
    *
    */
    AB_ugc_EXPORT static void admin_get_content_by_share_codes_v2(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const admin_content_v2::AdminGetContentByShareCodesV2& request, 
        const std::function<void(const accelbyte::Vector<model::ContentDownloadV2>&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Get content by sharecode
    * @details Get content by share code
    * @details /ugc/v2/admin/namespaces/{namespace}/contents/sharecodes/{shareCode}
    *
    */
    AB_ugc_EXPORT static void admin_get_content_by_share_code_v2(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const admin_content_v2::AdminGetContentByShareCodeV2& request, 
        const std::function<void(const model::ContentDownloadV2&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Get content by content ID
    * @details Get content by content ID
    * @details /ugc/v2/admin/namespaces/{namespace}/contents/{contentId}
    *
    */
    AB_ugc_EXPORT static void admin_get_content_by_content_idv2(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const admin_content_v2::AdminGetContentByContentIDV2& request, 
        const std::function<void(const model::ContentDownloadV2&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Rollback content's payload version
    * @details Rollback content&#39;s payload to specified version
    * @details /ugc/v2/admin/namespaces/{namespace}/contents/{contentId}/rollback/{versionId}
    *
    */
    AB_ugc_EXPORT static void admin_rollback_content_version_v2(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const admin_content_v2::AdminRollbackContentVersionV2& request, 
        const std::function<void(const model::ContentDownload&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Upload screenshots for content
    * @details This endpoint used to request upload URL from content&#39;s screenshot.  
If *contentType* is not specified, it will use *fileExtension* value.
Supported file extensions: pjp, jpg, jpeg, jfif, bmp, png.
Maximum description length: 1024
    * @details /ugc/v2/admin/namespaces/{namespace}/contents/{contentId}/screenshots
    *
    */
    AB_ugc_EXPORT static void admin_upload_content_screenshot_v2(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const admin_content_v2::AdminUploadContentScreenshotV2& request, 
        const std::function<void(const model::Screenshots&)>& on_201,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Update screenshot of content
    * @details Maximum description length: 1024
    * @details /ugc/v2/admin/namespaces/{namespace}/contents/{contentId}/screenshots
    *
    */
    AB_ugc_EXPORT static void admin_update_screenshots_v2(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const admin_content_v2::AdminUpdateScreenshotsV2& request, 
        const std::function<void(const model::ScreenshotUpdate&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Delete screenshots content
    * @details Delete screenshot from a content
    * @details /ugc/v2/admin/namespaces/{namespace}/contents/{contentId}/screenshots/{screenshotId}
    *
    */
    AB_ugc_EXPORT static void admin_delete_content_screenshot_v2(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const admin_content_v2::AdminDeleteContentScreenshotV2& request, 
        const std::function<void()>& on_204,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief List content's payload versions
    * @details Content&#39;s payload versions created when UGC is created or updated with &lt;code&gt;updateContentFile&lt;/code&gt; set to true. Only list up to 10 latest versions.
    * @details /ugc/v2/admin/namespaces/{namespace}/contents/{contentId}/versions
    *
    */
    AB_ugc_EXPORT static void admin_get_content_versions_v2(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const admin_content_v2::AdminGetContentVersionsV2& request, 
        const std::function<void(const model::GetContentVersionsResponse&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Update content to S3 bucket by share code
    * @details *shareCode* format should follows:  

				&#34;Max length: 7
				&#34;Available characters: abcdefhkpqrstuxyz
    * @details /ugc/v2/admin/namespaces/{namespace}/users/{userId}/channels/{channelId}/contents/s3/sharecodes/{shareCode}
    *
    */
    AB_ugc_EXPORT static void admin_update_content_by_share_code_v2(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const admin_content_v2::AdminUpdateContentByShareCodeV2& request, 
        const std::function<void(const model::CreateContentV2&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Delete content by share code
    * @details Delete content by share code
    * @details /ugc/v2/admin/namespaces/{namespace}/users/{userId}/channels/{channelId}/contents/sharecodes/{shareCode}
    *
    */
    AB_ugc_EXPORT static void admin_delete_content_by_share_code_v2(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const admin_content_v2::AdminDeleteContentByShareCodeV2& request, 
        const std::function<void()>& on_204,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Delete user content
    * @details Delete user content by content ID
    * @details /ugc/v2/admin/namespaces/{namespace}/users/{userId}/channels/{channelId}/contents/{contentId}
    *
    */
    AB_ugc_EXPORT static void admin_delete_user_content_v2(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const admin_content_v2::AdminDeleteUserContentV2& request, 
        const std::function<void()>& on_204,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Update user content
    * @details Update existing user content
    * @details /ugc/v2/admin/namespaces/{namespace}/users/{userId}/channels/{channelId}/contents/{contentId}
    *
    */
    AB_ugc_EXPORT static void admin_update_user_content_v2(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const admin_content_v2::AdminUpdateUserContentV2& request, 
        const std::function<void(const model::UpdateContentV2&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Update user content file location
    * @details This endpoint should be used after calling generate user content upload url endpoint to commit the changes
    * @details /ugc/v2/admin/namespaces/{namespace}/users/{userId}/channels/{channelId}/contents/{contentId}/fileLocation
    *
    */
    AB_ugc_EXPORT static void admin_update_user_content_file_location(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const admin_content_v2::AdminUpdateUserContentFileLocation& request, 
        const std::function<void(const model::UpdateContentV2&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Generate user content upload URL
    * @details generate user content upload URL
    * @details /ugc/v2/admin/namespaces/{namespace}/users/{userId}/channels/{channelId}/contents/{contentId}/uploadUrl
    *
    */
    AB_ugc_EXPORT static void admin_generate_user_content_upload_urlv2(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const admin_content_v2::AdminGenerateUserContentUploadURLV2& request, 
        const std::function<void(const model::ContentUpload&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Get user's generated contents
    * @details Get user cotent
    * @details /ugc/v2/admin/namespaces/{namespace}/users/{userId}/contents
    *
    */
    AB_ugc_EXPORT static void admin_get_content_by_user_idv2(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const admin_content_v2::AdminGetContentByUserIDV2& request, 
        const std::function<void(const model::ContentDownloadV2Pagination&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Hide/Unhide user's generated contents
    * @details Hide/Unhide user&#39;s generated contents
    * @details /ugc/v2/admin/namespaces/{namespace}/users/{userId}/contents/{contentId}/hide
    *
    */
    AB_ugc_EXPORT static void admin_update_content_hide_status_v2(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const admin_content_v2::AdminUpdateContentHideStatusV2& request, 
        const std::function<void(const model::CreateContentV2&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

};

}
}