// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/ugc/ugc_export.h"
#include "accelbyte/ugc/admin_channel/AdminGetOfficialChannel.h"
#include "accelbyte/ugc/admin_channel/AdminCreateChannel.h"
#include "accelbyte/ugc/admin_channel/AdminDeleteOfficialChannel.h"
#include "accelbyte/ugc/admin_channel/AdminUpdateOfficialChannel.h"
#include "accelbyte/ugc/admin_channel/AdminGetUserChannel.h"
#include "accelbyte/ugc/admin_channel/AdminDeleteChannel.h"
#include "accelbyte/ugc/admin_channel/AdminUpdateChannel.h"
#include "accelbyte/ugc/models/DownloadCount.h"
#include "accelbyte/ugc/models/AdminContentRequestV2.h"
#include "accelbyte/ugc/models/AdminGetContentsRequest.h"
#include "accelbyte/ugc/models/AdminUpdateContentRequest.h"
#include "accelbyte/ugc/models/AdminUpdateContentRequestV2.h"
#include "accelbyte/ugc/models/ApproveStagingContentRequest.h"
#include "accelbyte/ugc/models/AdminChannelRequest.h"
#include "accelbyte/ugc/models/Channel.h"
#include "accelbyte/ugc/models/AdminConfigResponse.h"
#include "accelbyte/ugc/models/ContentDownload.h"
#include "accelbyte/ugc/models/ContentDownloadV2.h"
#include "accelbyte/ugc/models/ContentDownloader.h"
#include "accelbyte/ugc/models/ContentLikeRequest.h"
#include "accelbyte/ugc/models/Like.h"
#include "accelbyte/ugc/models/Likers.h"
#include "accelbyte/ugc/models/ContentRequestV2.h"
#include "accelbyte/ugc/models/ContentSnapshot.h"
#include "accelbyte/ugc/models/ContentVersion.h"
#include "accelbyte/ugc/models/CopyContentRequest.h"
#include "accelbyte/ugc/models/CreateContentRequest.h"
#include "accelbyte/ugc/models/AdminCreateContentRequestS3.h"
#include "accelbyte/ugc/models/CreateContent.h"
#include "accelbyte/ugc/models/CreateContentV2.h"
#include "accelbyte/ugc/models/CreateGroupRequest.h"
#include "accelbyte/ugc/models/Group.h"
#include "accelbyte/ugc/models/CreateScreenshotRequest.h"
#include "accelbyte/ugc/models/Screenshots.h"
#include "accelbyte/ugc/models/CreateTagRequest.h"
#include "accelbyte/ugc/models/Tag.h"
#include "accelbyte/ugc/models/CreateTypeRequest.h"
#include "accelbyte/ugc/models/Type.h"
#include "accelbyte/ugc/models/CreatorFollowState.h"
#include "accelbyte/ugc/models/CreatorOverview.h"
#include "accelbyte/ugc/models/Creator.h"
#include "accelbyte/ugc/models/1297a459abe6758ploadURLRequest.h"
#include "accelbyte/ugc/models/ContentUpload.h"
#include "accelbyte/ugc/models/GetContentByShareCodesRequest.h"
#include "accelbyte/ugc/models/GetContentPreviewResponse.h"
#include "accelbyte/ugc/models/HideContentRequest.h"
#include "accelbyte/ugc/models/LikeState.h"
#include "accelbyte/ugc/models/GetContentVersionsResponse.h"
#include "accelbyte/ugc/models/ContentDownloadPagination.h"
#include "accelbyte/ugc/models/ContentDownloadV2Pagination.h"
#include "accelbyte/ugc/models/ContentDownloaderPagination.h"
#include "accelbyte/ugc/models/ContentLikersPagination.h"
#include "accelbyte/ugc/models/CreatorOverviewPagination.h"
#include "accelbyte/ugc/models/GetChannelPagination.h"
#include "accelbyte/ugc/models/GetConfigsPagination.h"
#include "accelbyte/ugc/models/GetTagPagination.h"
#include "accelbyte/ugc/models/GetTypePagination.h"
#include "accelbyte/ugc/models/GroupPagination.h"
#include "accelbyte/ugc/models/StagingContentsPagination.h"
#include "accelbyte/ugc/models/CursorPagination.h"
#include "accelbyte/ugc/models/PayloadURL.h"
#include "accelbyte/ugc/models/PreviewURL.h"
#include "accelbyte/ugc/models/ChannelRequest.h"
#include "accelbyte/ugc/models/CreateContentS3Request.h"
#include "accelbyte/ugc/models/GetContentsRequest.h"
#include "accelbyte/ugc/models/Screenshot.h"
#include "accelbyte/ugc/models/StagingContent.h"
#include "accelbyte/ugc/models/UpdateChannelRequest.h"
#include "accelbyte/ugc/models/UpdateConfigRequest.h"
#include "accelbyte/ugc/models/UpdateContentRequest.h"
#include "accelbyte/ugc/models/UpdateContentRequestV2.h"
#include "accelbyte/ugc/models/UpdateContentV2.h"
#include "accelbyte/ugc/models/UpdateContentShareCodeRequest.h"
#include "accelbyte/ugc/models/UpdateFileLocationRequest.h"
#include "accelbyte/ugc/models/UpdateScreenshotRequest.h"
#include "accelbyte/ugc/models/ScreenshotUpdate.h"
#include "accelbyte/ugc/models/UpdateStagingContentRequest.h"
#include "accelbyte/ugc/models/UserFollowRequest.h"
#include "accelbyte/ugc/models/Follow.h"
#include "accelbyte/ugc/models/CreateScreenshotRequestItem.h"
#include "accelbyte/ugc/models/PreviewMetadata.h"
#include "accelbyte/ugc/models/UpdateScreenshot.h"
#include "accelbyte/ugc/models/Error.h"
#include "accelbyte/common/Error.h"
#include "accelbyte/tls/SecurityAuthorization.h"

#include <functional>
#include "accelbyte/memory/memory.h"

namespace accelbyte {
namespace ugc {

class AdminChannel
{
public:	
    /**
    * @brief Get Channels
    * @details Get official channel paginated
    * @details /ugc/v1/admin/namespaces/{namespace}/channels
    *
    */
    AB_ugc_EXPORT static void admin_get_official_channel(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const admin_channel::AdminGetOfficialChannel& request, 
        const std::function<void(const model::GetChannelPagination&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Create Channel
    * @details Create official channel
    * @details /ugc/v1/admin/namespaces/{namespace}/channels
    *
    */
    AB_ugc_EXPORT static void admin_create_channel(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const admin_channel::AdminCreateChannel& request, 
        const std::function<void(const model::Channel&)>& on_201,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Delete Channel
    * @details Delete official channel
    * @details /ugc/v1/admin/namespaces/{namespace}/channels/{channelId}
    *
    */
    AB_ugc_EXPORT static void admin_delete_official_channel(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const admin_channel::AdminDeleteOfficialChannel& request, 
        const std::function<void()>& on_204,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Update Channel
    * @details Update official channel
    * @details /ugc/v1/admin/namespaces/{namespace}/channels/{channelId}
    *
    */
    AB_ugc_EXPORT static void admin_update_official_channel(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const admin_channel::AdminUpdateOfficialChannel& request, 
        const std::function<void(const model::Channel&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Get Channels
    * @details Get user channel paginated
    * @details /ugc/v1/admin/namespaces/{namespace}/users/{userId}/channels
    *
    */
    AB_ugc_EXPORT static void admin_get_user_channel(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const admin_channel::AdminGetUserChannel& request, 
        const std::function<void(const model::GetChannelPagination&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Delete Channel
    * @details Delete user channel
    * @details /ugc/v1/admin/namespaces/{namespace}/users/{userId}/channels/{channelId}
    *
    */
    AB_ugc_EXPORT static void admin_delete_channel(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const admin_channel::AdminDeleteChannel& request, 
        const std::function<void()>& on_204,
        const std::function<void (const accelbyte::Error&)>& on_error);   

    /**
    * @brief Update Channel
    * @details Update user channel
    * @details /ugc/v1/admin/namespaces/{namespace}/users/{userId}/channels/{channelId}
    *
    */
    AB_ugc_EXPORT static void admin_update_channel(
        const accelbyte::tls::SecurityAuthorization& authorization,
        const admin_channel::AdminUpdateChannel& request, 
        const std::function<void(const model::Channel&)>& on_200,
        const std::function<void (const accelbyte::Error&)>& on_error);   

};

}
}