// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/http/ModelObject.h"
#include "accelbyte/common/Optional.h"
#include "accelbyte/common/String.h"
#include "accelbyte/common/Map.h"
#include "accelbyte/common/Vector.h"
#include "accelbyte/common/DateTime.h"
#include "accelbyte/memory/memory.h"
#include "accelbyte/utils/JsonObjectString.h"
#include "accelbyte/basic/basic_export.h"


namespace accelbyte {
namespace basic {
namespace model {

class NamespaceInfo : public accelbyte::http::ModelObject
{
public:
    enum class Status : uint32_t {
        UNKNOWN,
        ACTIVE,
        DELETED,
        INACTIVE
    };
    /**
    * @brief default constructor.
    **/
	AB_basic_EXPORT  NamespaceInfo() = default;
	
    /**
    * @brief destructor.
    **/
    AB_basic_EXPORT virtual ~NamespaceInfo() = default;
	
	/**
    * @brief Return the object unique id (used for serialization)
    **/
    AB_basic_EXPORT virtual const String& model_id() const override;
	
	/**
    * @brief Return the unique id that can be used to determine this class (used for serialization)
    **/
    AB_basic_EXPORT static const String& model_object_id();
    
    // start of usefull parameters
	accelbyte::Optional<accelbyte::String> client_id{};
	accelbyte::Optional<accelbyte::DateTime> created_at{};
	accelbyte::String display_name{};
	accelbyte::String ab_namespace{};
	accelbyte::Optional<accelbyte::String> parent_namespace{};
	accelbyte::Optional<Status> status{};
	accelbyte::Optional<accelbyte::DateTime> updated_at{};
};

}
}
}