// Copyright (c) 2024 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// This code is generated by tool. DO NOT EDIT.
#pragma once

#include "accelbyte/http/ModelObject.h"
#include "accelbyte/common/Optional.h"
#include "accelbyte/common/String.h"
#include "accelbyte/common/Map.h"
#include "accelbyte/common/Vector.h"
#include "accelbyte/common/DateTime.h"
#include "accelbyte/memory/memory.h"
#include "accelbyte/utils/JsonObjectString.h"
#include "accelbyte/seasonpass/seasonpass_export.h"

#include "accelbyte/seasonpass/models/SeasonSummary.h"

namespace accelbyte {
namespace seasonpass {
namespace model {

class ClaimableSeason : public accelbyte::http::ModelObject
{
public:
    /**
    * @brief default constructor.
    **/
	AB_seasonpass_EXPORT  ClaimableSeason() = default;
	
    /**
    * @brief destructor.
    **/
    AB_seasonpass_EXPORT virtual ~ClaimableSeason() = default;
	
	/**
    * @brief Return the object unique id (used for serialization)
    **/
    AB_seasonpass_EXPORT virtual const String& model_id() const override;
	
	/**
    * @brief Return the unique id that can be used to determine this class (used for serialization)
    **/
    AB_seasonpass_EXPORT static const String& model_object_id();
    
    // start of usefull parameters
	accelbyte::Map<accelbyte::String,accelbyte::Map<accelbyte::String,accelbyte::Vector<accelbyte::String>>> claiming_rewards{};
	bool cleared{false};
	accelbyte::DateTime created_at{};
	int current_exp{0};
	int current_tier_index{0};
	accelbyte::DateTime enrolled_at{};
	accelbyte::Vector<accelbyte::String> enrolled_passes{};
	accelbyte::String id{};
	int last_tier_index{0};
	accelbyte::String ab_namespace{};
	int required_exp{0};
	accelbyte::Optional<SeasonSummary> season{};
	accelbyte::String season_id{};
	accelbyte::Map<accelbyte::String,accelbyte::Map<accelbyte::String,accelbyte::Vector<accelbyte::String>>> to_claim_rewards{};
	accelbyte::Optional<long> total_exp{};
	accelbyte::Optional<long> total_paid_for_exp{};
	accelbyte::Optional<long> total_sweat_exp{};
	accelbyte::DateTime updated_at{};
	accelbyte::String user_id{};
};

}
}
}